### ISSUE TITLE
Runtime Error with Self in Expression Block with X#2.12

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1058] opened 2022-06-22 15:54 UTC
This example outputs 42 with the version 2.11 but throws a "no method found" exception in 2.12. 

```
using System
using System.Text

function Start() as void strict
    Console.WriteLine(Dummy{}.Test())
    Console.ReadKey()
return

class Dummy inherit BaseDummy

    method Test() as real8
        return self:GetOrAddRecFieldBufferNum(#GetTestData)

    method GetTestData() as int
        return 42
        
end class

class BaseDummy

    method GetOrAddRecFieldBufferNum(symMethodFieldGet as symbol) as real8
        return SqlRecFieldBufferValue<real8>{}:GetOrAddRecFieldBuffer({ => Send(self, symMethodFieldGet)})

end class

class SqlRecFieldBufferValue<T>

    method GetOrAddRecFieldBuffer(methodFieldGet as System.Func<T>) as T
        return methodFieldGet()

end class
```

The compiler generates different output: 

Version 2.11

```
public virtual double GetOrAddRecFieldBufferNum(__Symbol symMethodFieldGet)
{
   return new SqlRecFieldBufferValue<double>().GetOrAddRecFieldBuffer(() => Functions.Send(this, symMethodFieldGet));
}
```

Version 2.12

```
public virtual double GetOrAddRecFieldBufferNum(__Symbol symMethodFieldGet)
{
   <>c__DisplayClass0_0 CS$<>8__locals0 = new <>c__DisplayClass0_0();
   CS$<>8__locals0.<>4__this = this;
   CS$<>8__locals0.symMethodFieldGet = symMethodFieldGet;
   return new SqlRecFieldBufferValue<double>().GetOrAddRecFieldBuffer(() => Functions.Send(CS$<>8__locals0, CS$<>8__locals0.symMethodFieldGet));
}
```

This is a possible workaround for this issue:
```
method GetOrAddRecFieldBufferNum(symMethodFieldGet as symbol) as real8
   var thisInstance := self
   return SqlRecFieldBufferValue<real8>{}:GetOrAddRecFieldBuffer({ => Send(thisInstance, symMethodFieldGet)})
```

Here is the solution to reproduce the issue: [XSharpTestsSelfCodeBlock.zip](https://github.com/X-Sharp/XSharpPublic/files/8959357/XSharpTestsSelfCodeBlock.zip)

**Comment by cpyrgas** [comment] 2022-06-22 22:59
Can't reproduce this with our current build, it does print 42. I think this was also taken care of by another fix recently.

**Comment by RobertvanderHulst** [comment] 2022-06-23 06:07
This was fixed with my fix for #1049

**Comment by hpetriffer** [comment] 2022-06-23 06:18
Is there already a plan to release a new version in the near future?

**Comment by cpyrgas** [comment] 2022-06-25 13:58
@hpetriffer Yes, I think you must have received a test version already

**Comment by hpetriffer** [comment] 2022-06-27 05:33
yes we have received the test version of the compiler. At the moment are other bugs, so we don't have finished to test it

**Closed** 2022-06-27 12:18 UTC
Labels: bug, Compiler
