### ISSUE TITLE
Bogus warning about unbalanced ">>" in TEXT...ENDTEXT

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#452] opened 2020-07-22 09:58 UTC
Following produces a warning XS9085: Unbalanced textmerge delimiters '<<' and '>>'.

```
FUNCTION Start() AS VOID
LOCAL lcBatch AS STRING
TEXT TO lcBatch TEXTMERGE NOSHOW PRETEXT 1+2
	@echo off


	REM ----------------------------------------
	REM variable declaration
	REM ----------------------------------------
	set PATH1="<<JUSTPATH( ADDBS( lcOutputPath ) )>>"
	set OLDERTHEN=-14
	set FILEFILTER=*.*
	set LOGFILE="<<PROPER( ADDBS( JUSTPATH( FULLPATH( 'cleanup.exe' ) ) ) ) >> _log\%DATE:~6,4%%DATE:~3,2%%DATE:~0,2%\cleanupbatch.log"

	REM ----------------------------------------
	REM starting batch run
	REM ----------------------------------------
	echo starting batch > %LOGFILE%
	echo ************************** >> %LOGFILE%
	echo deleting protocol >> %LOGFILE%

	REM ----------------------------------------
	REM select files
	REM ----------------------------------------
	forfiles /P "%PATH1%" /S /M %FILEFILTER% /D %OLDERTHEN% /C "cmd /c del @file | echo loesche @file vom @fdate :: %LOGFILE%"
	
	REM ----------------------------------------
	REM END of batch run
	REM ----------------------------------------
	echo ************************** >> %LOGFILE%
	echo END of batch run >> %LOGFILE%
	
ENDTEXT 

? lcBatch

```

**Comment by RobertvanderHulst** [comment] 2020-07-22 10:04
I think this is a valid warning. 
When somebody willingly puts an unmatched `>>` in a TEXT ENDTEXT then they should also add a compiler pragma to hide the warning. 
I do not want to loose this warning for other cases where people make mistakes and have an unmatched marker by accident.

Robert

**Comment by cpyrgas** [comment] 2020-07-22 10:17
Robert, oh, so this ">>" is treated as a special control sequence in TEXT..END TEXT constructs? I thought it is always treated as simple text, like in

cMyString := "A simple string containing the >> characters"

**Comment by cpyrgas** [comment] 2020-07-22 12:04
I am also seeing this, I think it is a bug, but not sure, really need to properly understand how this TEXT..ENDTEXT works:

```
System.FormatException
Input string was not in a correct format.

Callstack : 
StringBuilder System.Text.StringBuilder.AppendFormatHelper(System.IFormatProvider provider, System.String format, System.ParamsArray args)() 
static String System.String.FormatHelper(System.IFormatProvider provider, System.String format, System.ParamsArray args)() 
static String System.String.Format(System.String format, System.Object[] args)()
``` 

```
FUNCTION Start() AS VOID
LOCAL c AS STRING
TEXT TO c
Hello,1,TRUE, "<< some STRING >>"
ENDTEXT 
? c

```

**Comment by RobertvanderHulst** [comment] 2020-07-23 07:35
To my knowledge the contents of the TEXT .. ENDTEXT are taken literally, with the exception of things between `<< `and `>>` characters. The parts between these characters are expressions that are evaluated and the result is embedded into the string. You will see that in the original ticket in line SET PATH1=...
Quotes inside the delimiters become part of the expression. Quotes outside the delimiters, such as in your last example, are not part of the "expression".
In the compiler I am converting this to a String.Format, where I am replacing the contents of the delimiters with {0}, {1} etc and I am using the contents of the delimiters  such as `JUSTPATH( ADDBS( lcOutputPath ) )` in the first example) as expressions.
Your example does not compile because  `some STRING` has no meaning in your code.
The only real problem here is that I am counting opening and closing delimiters and that I am throwing a warning for the closing delimiter that is used as output redirection symbol in the batch file because it does not match any `<<` token

**Comment by cpyrgas** [comment] 2020-07-23 11:21
Thanks, I understand what's going on now. Yeah, only issue is that warning indeed. The original code does work as expected apart from that.

**Comment by RobertvanderHulst** [comment] 2020-07-24 18:14
So this is not a bug and we'll leave the code the way it is.

**Closed by RobertvanderHulst** 2020-07-24 18:14 UTC
Labels: Compiler, FoxPro, bug

**Comment by JohanNel** [comment] 2020-07-24 19:03
Robert,

Sorry for chirping in late, I assume it also holds for a mismatched "<<" ?

Johan
