### ISSUE TITLE
Preprocessor bug in WP (XBase++ dialect)

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1288] opened 2023-06-27 11:47 UTC
**Describe the bug**
Preprocessor translates incorrectly UDC. I believe that this error is similar to the one described in the [ticket](https://github.com/X-Sharp/XSharpPublic/issues/1284)

**To Reproduce .prg**
```
// watch point
#xcommand WP [/<x:S,F,SF,FS>] [/<y:CAPS,C>] [/<m:MUTE,M>] [/OBJ <obj> = <mes> [,<objn> = <mesn> ]] <list,...> [<file>] ;
=> wpRouter({<list>},<(x)>,<file>,<(y)>,<(m)>,{[{<"obj">,{|o| <mes>}}] [,{<"objn">,{|o| <mesn>} }] })

procedure Main()
    local a, b, c

    wp a,b,c
    wp /sf /m a,b,c
    return
```

**Expected behavior (xBase++ ppo**
Output
```
procedure Main()
    local a, b, c

    wpRouter({a,b,c},,,,,{  })
    wpRouter({a,b,c},"SF",,,"M",{  })
    return
```

**Actual behavior (X# ppo)**
I do not pretend to change the case of strings `"sf"`, `"m"`.
```
procedure Main()
    local a, b, c

wpRouter({a,b,},,c,,,{  })
wpRouter({a,b,},"sf",c,,"m",{  })
    return
```
**Additional context**
X# Compiler version 2.16.0.5 (public)
-dialect:xBase++ -xpp1 -lb -memvar -vo1 -vo3 -vo5 -vo10 -vo15 -vo16

**Comment by RobertvanderHulst** [comment] 2023-06-27 14:04
After todays fixes to the preprocessor the output looks like this:
```
procedure Main()
    local a, b, c

wpRouter({a,b,},,c,,,{  })
wpRouter({a,b,},"sf",c,,"m",{  })
    return
```

So I think this is fixed because it is indeed a duplicate of #1284

**Comment by DenGhostYY** [comment] 2023-09-12 07:18
Hello. Preprocessor version 2.17.0.3 (release) still does not process WP correctly.
**X# .ppo**
```
// watch point
//PP #xcommand WP [/<x:S,F,SF,FS>] [/<y:CAPS,C>] [/<m:MUTE,M>] [/OBJ <obj> = <mes> [,<objn> = <mesn> ]] <list,...> [<file>] ;
//PP => wpRouter({<list>},<(x)>,<file>,<(y)>,<(m)>,{[{<"obj">,{|o| <mes>}}] [,{<"objn">,{|o| <mesn>} }] })

procedure Main()
    local a, b, c

wpRouter({a,b,},,c,,,{  })
wpRouter({a,b,},"sf",c,,"m",{  })
    return
```

**Comment by RobertvanderHulst** [comment] 2023-09-12 14:46
I think the preprocessor matches the "C" with the "C" in the <y:CAPS,C> marker and it ignores that that match marker should start with a /

**Comment by RobertvanderHulst** [comment] 2023-09-12 15:40
More info: the reason that this happens is that the first token in the optional marker (the `/`) is also found in other tokens. When processing the Preprocessor Rule we try to determine potential "stop tokens" so we know when the match for the list has to end and when an optional match marker is found.
This allows to write both
`wp a,b,c /sf`
and 
`wp /sf a,b,c `

There was a logical error in the code that finds "stoptokens". Because the `/` in the `[/<y:CAPS,C> ] ` marker was already found in the `[/<x:S,F,SF,FS>]` marker, it started to add CAPS and C as stoptokens. This should not have happened.
As a result the 'C' in the UDC was seen as the end of the list `a,b,c` which resulted in a list `a,b,` and the preprocessor also thought that the <y> marker was found because it matched the `c` with that marker.
This is now fixed.

**Comment by cpyrgas** [comment] 2023-09-21 07:49
It's fixed, with a minor issue(?), @DenGhostYY specifies as the expected output:

```
wpRouter({a,b,},,c,,,{  })
wpRouter({a,b,c},"SF",,,"M",{  })
```

while X# now produces:

```
wpRouter({a,b,c},,,,,{  })
wpRouter({a,b,c},"sf",,,"m",{  })
```

so the casing is different. Not sure if this is really important, but leaving it here for your consideration.

**Comment by RobertvanderHulst** [comment] 2023-09-21 08:47
The matching of tokens for the UDC is case insensitive. Apparently XBase++ achieves this by converting the tokens to upper case.
We do not do that, so the token is written to the output stream in the original case.
If uppercase is needed then the UDC can be modified and a call to Upper() can be inserted.

**Comment by cpyrgas** [comment] 2023-09-21 14:27
OK, agreed

**Closed by cpyrgas** 2023-09-21 14:27 UTC
Labels: bug, duplicate, Compiler, Preprocessor
