### ISSUE TITLE
Add optional parameter to Program( [,lShowSignature default=.f.] )

### ISSUE THREAD

**Issue by lazy-fox** [X-Sharp/XSharpPublic#712] opened 2021-07-05 18:09 UTC
In vfp we don't have overloaded methods but just fumble along with optional parameters. So when Program() is called resulting in string return, the Object.Method return value always identifies correct method - only if object factories and facade approaches are used, adding class info is needed.
Not so in x#! Here we can have oodles of overloaded methods in class and class heritage. So perhaps adding an optional parameter resulting in adding method signature to Class.Method might help pinpoint the method intended in code/runtime.

tia
thomas

**Comment by RobertvanderHulst** [comment] 2021-07-05 18:15
Thomas,
I really have no idea what you are asking...

**Comment by lazy-fox** [comment] 2021-07-06 08:15
from Getword, there are several overloads
FUNCTION GetWordNum( cString AS STRING, nIndex AS INT) AS STRING
   goLog.Log(Program())
    LOCAL loSrch := GetDefaultWordHandler() AS GetWordHandler
    RETURN loSrch:oActiveObjc:GetWordNum( cString, nIndex)

/// <include file="VfpRuntimeDocs.xml" path="Runtimefunctions/getwordnum/*" />
FUNCTION GetWordNum( cString AS STRING, nIndex AS INT, cDelimiters AS STRING) AS STRING
   goLog.Log(Program())
    *-- Checked: throws on .Null.
    LOCAL lnRefSwitch := 0 AS INT
    LOCAL lcTrack := "" AS STRING
    RETURN  GetWordNum( cString, nIndex, cDelimiters, REF lnRefSwitch, REF lcTrack)

INTERNAL FUNCTION GetWordNum( cString AS STRING, nIndex AS INT, cDelimiters AS STRING, tnSwitch REF INT, tcTrack REF STRING) AS STRING
    *-- Checked: throws on .Null., lcReturn still here to debug
   goLog.Log(Program())

would always log "GetWordNum()". My proposal is to add optional Parameter and allow
   goLog.Log(Program(,.t.)) to be called in all 3 places,
returning/logging respectively
GetWordNum( cString AS STRING, nIndex AS INT)
GetWordNum( cString AS STRING, nIndex AS INT, cDelimiters AS STRING)
GetWordNum( cString AS STRING, nIndex AS INT, cDelimiters AS STRING, tnSwitch REF INT, tcTrack REF STRING)

indicating in which of the existing overloads with identical function name the call to Program(  ,.t.) was run to be logged.

For GetWordNum it would *not* make much sense, but for the different overloads needed for alines() it makes more sense, as the search-functionality evoked will have more differences due to the fact that alines() allows not only for several separator chars but several separator strings.

Hope my ER is clearer now
thomas

**Comment by Karl1155** [comment] 2021-07-06 18:04
Thomas,

change your

goLog.Log(Program())

to

goLog.Log( MethodBase.GetCurrentMethod().Tostring() )

Now you should see in your logfile the signature of the called functions

e.g.

```
USING System.Reflection

FUNCTION Start() AS VOID

TestSignature ( 1 , "34" )	
TestSignature ( 1 , "34" , {"Test"} )	
TestSignature ( 1 , "34" , 1 )

RETURN

FUNCTION TestSignature( iValue AS INT , cValue AS STRING  ) AS INT
? MethodBase.GetCurrentMethod().ToString() 
RETURN 1

FUNCTION TestSignature ( iValue1 AS INT , cValue AS STRING , iValue2 AS INT  ) AS INT 
? MethodBase.GetCurrentMethod().ToString()
RETURN 1

FUNCTION TestSignature( iValue AS INT , cValue AS STRING , aValue AS ARRAY  ) AS INT 
? MethodBase.GetCurrentMethod().ToString()
RETURN 1


```
The results are: 

Int32 TestSignature(Int32, System.String)
Int32 TestSignature(Int32, System.String, XSharp.__Array)
Int32 TestSignature(Int32, System.String, Int32)

regards
Karl-Heinz

**Comment by RobertvanderHulst** [comment] 2021-07-07 12:57
When we implement program we will most likely use System.Diagnostics.StackTrace. This will allow to pass the nLevel parameter t for Program. Maybe we'll add a second parameter to control if you will get just the program name or the complete signature.

**Comment by lazy-fox** [comment] 2021-07-08 22:50
Hi Karl-Heinz,
thx for pointing me in the direction of Methodbase. Have read a bit and for automatic insertion this is swell. Have not measured reflection overhead, but I have a direction to spelunk more, as there are alternatives mentioned if reflection blurs timing. 

In really timecritical profiles I could copy signature by hand, but now I know where to look further, esp. combined with Roberts further hint, for less manual effort.

Beauty of combining with the stacklevel is the option to create a log with more info not directly getting info within the method, but at a defined stack level "away", either via raised event or method call with less parameters.

thx again
thomas

**Comment by Karl1155** [comment] 2021-07-20 11:41
Thomas,

i´m looking at the Program() function. Because my Foxpro version doesn´t support the -1 param, one question:  According the VFP help Program(-1) returns the current stack position, so i guess that both Program() calls return "Test", right ?   

```
do Test()

procedure Test
 ? Program()   			// "Test" 
 ? Program ( Program ( -1 ) )   // "Test" 
```

Karl-Heinz

**Comment by RobertvanderHulst** [comment] 2021-07-20 12:43
Karl,
After some edits this worked in FoxPro (FoxPro does not like the () after Do and it does not like the // comments).
The result is TEST for each of the lines (name is in upper case)

**Comment by Karl1155** [comment] 2021-07-20 16:29
Robert,

here´s what i´ve tried so far.


- i added to the Program() function the optional param 'lShowSignature' 

- to make it work with the 2.8c build i typed the Program() function as 
      `FUNCTION Program ( nLevel := NIL AS USUAL , lShowSignature := FALSE AS LOGIC ) AS USUAL `
      instead of  	
      `FUNCTION Program ( nLevel , lShowSignature )`
     see: https://github.com/X-Sharp/XSharpPublic/issues/720

- To get the numeric stack position - required if the nLevel param is -1 - i´m using a for next loop to compare the stack values with the current position.


```
USING System.Diagnostics

FUNCTION Start( ) AS VOID

	? "Program start"
	? "-------------"
	? "Program(1)           " + Program ( 1 ) 
	? "Program(0)           " + Program ( 0 )
	? "Program()            " + Program()   	  
	? "Program ( , .t. )    " + Program(,.t.) 
	? "Program (2)          " + Program(2) 
	? "Program(-1)          " + Program ( Program( -1 ) )	 
	?
		
	=Test1()

RETURN

FUNCTION Test1() 
PARAMETERS  x , y 
?
? "Enter Test1()"
? "-------------"
? "Program(1)           " + Program ( 1 ) 
? "Program(0)           " + Program ( 0 )
? "Program()            " + Program()   
? "Program ( , .t. )    " + Program(,.t.) 
? "Program (2)          " + Program(2) 
? "Program(-1)          " + Program ( Program( -1 ) )
=Test2()
? "ReEnter Test1()" 
? "---------------"
? "Program(1)           " + Program ( 1 ) 
? "Program(0)           " + Program ( 0 )  
? "Program()            " + Program()   
? "Program ( , .t. )    " + Program(,.t.) 
? "Program (2)          " + Program(2) 
? "Program(-1)          " + Program ( Program( -1 ) )
RETURN 

FUNCTION Test2() 
?
? "Enter Test2()"
? "-------------" 
? "Program(1)           " + Program ( 1 ) 
? "Program(0)           " + Program ( 0 )  
? "Program()            " + Program()   
? "Program ( , .t. )    " + Program(,.t.) 
? "Program (2)          " + Program(2) 
? "Program(-1)          " + Program ( Program( -1 ) )
=Test3()
? "ReEnter Test2()"
? "---------------" 
? "Program(1)           " + Program ( 1 ) 
? "Program(0)           " + Program ( 0 )  
? "Program()            " + Program()   
? "Program ( , .t. )    " + Program(,.t.) 
? "Program (2)          " + Program(2) 
? "Program(-1)          " + Program ( Program( -1 ) )
?

RETURN 

FUNCTION Test3() 
? 
? "Enter Test3()"
? "-------------" 
? "Program(1)           " + Program ( 1 ) 
? "Program(0)           " + Program ( 0 )  
? "Program()            " + Program()   
? "Program ( , .t. )    " + Program(,.t.) 
? "Program (2)          " + Program(2) 
? "Program(-1)          " + Program ( Program( -1 ) )
?
? "Current Stack:"
? "--------------"
=ListStack() 
?
RETURN 

FUNCTION Program ( nLevel := NIL AS USUAL , lShowSignature := FALSE AS LOGIC ) AS USUAL  	
// FUNCTION Program ( nLevel , lShowSignature )  	
LOCAL uRet := "" AS USUAL
LOCAL st := StackTrace{ TRUE } AS StackTrace
 

	IF IsNil ( nLevel )
		 
		nLevel := 1 
		
	ELSEIF IsNumeric ( nLevel )
		
		// note: i don´t know if a value smaller than -1 throws an error ?
		
		IF nLevel < 0 //  - 1  
			
			//  get the values of the current stack position 
			
 			VAR cMethod := st:GetFrame(1).GetMethod().ToString()           
			VAR cDeclarationType := st:GetFrame(1).GetMethod().DeclaringType.FullName  
			
 			FOR VAR i := 0 UPTO st:FrameCount - 1
				       
 				IF st:GetFrame(i).GetMethod().ToString() == cMethod .AND. ;
 					st:GetFrame(i).GetMethod().DeclaringType.FullName == cDeclarationType 
 					
 					uRet := st:FrameCount - i  // note: uRet holds a numeric value now 
 					
 					EXIT 
 					 
 				ENDIF
 				
 			NEXT 
 				
               // If you specify 0 or 1 for nLevel, PROGRAM() returns the name of the master program. 
		ELSEIF nLevel == 0 .OR. nLevel == 1   
			nLevel := st:FrameCount - 1 
		ELSE
			nLevel := st:FrameCount - nLevel
 		ENDIF
 		
	ELSE 

		THROW ArgumentException {"wrong parameter type", nameof ( nLevel ) }
		
	ENDIF 	

     
	IF ( nLevel < st:FrameCount .AND. nLevel > 0 ) 
		
		IF lShowSignature
			uRet := st:GetFrame(nLevel).GetMethod().ToString().ToUpper()	
		ELSE		
			uRet := st:GetFrame(nLevel).GetMethod().Name.ToUpper()   
		ENDIF
		
	ENDIF 
	
	RETURN uRet
	

	
	
FUNCTION ListStack() 	 
LOCAL st := StackTrace{ TRUE } AS StackTrace 

	FOR VAR i := 0 UPTO st:FrameCount - 1
		? i , st:GetFrame(i).GetMethod().ToString().ToUpper() // shows the signature 
		// ? i , st:GetFrame(i).GetMethod().Name.ToUpper()
	NEXT
	
	RETURN		

```

Karl-Heinz

**Comment by lazy-fox** [comment] 2021-07-20 20:11
Hi Karl-Heinz,
sorry, was not at home base... vfp help, if you don't have it:

> Parameters
>nLevel 
>Specifies the number of program levels to search for the program name. The nLevel >parameter can range from 0 to the program nesting depth. For more information about >program nesting levels, see maximum number of DO calls in Visual FoxPro System >Capacities. 
>When nLevel is omitted, PROGRAM( ) returns the name of the currently executing >program. If you specify 0 or 1 for nLevel, PROGRAM( ) returns the name of the master >program, or the highest-level program. 
>If you specify –1 for nLevel, PROGRAM( ) returns the current program level as a numeric >value. However, using PROGRAM(–1) in the Command window always returns zero (0). 
>If nLevel exceeds the program nesting depth, PROGRAM( ) returns an empty string (""). 

One vfp kink: Stacklevel is not only returned for -1, but a few negative numbers I tried - will test if it does stop at some byte/shortint, but current coding <0 smells fine - am a bit bushed, will deepen tomorrow.

Passing non-numeric parameters as argument will cause 
runtime error :
function argument type or value invalid
same does  vfp .Null. . 

As I am still not totally clear on VO / X# NIL vs. vfp .Null. I leave it at that...

Seems you already got part of the meat for AStackInfo as well, perhaps break out for reuse.

Have to think a bit, but current SWAG is, here we have a case where distinct different overloads (aka no defaults in method signature) are better if vfp NULL passing needs to be mirrored to avoid any "magic number" signifying vfp pcount()=0.

best regards
thomas

**Comment by lazy-fox** [comment] 2021-07-21 10:23
Not tested, only thinking:

*-- Core functions also called into if method signature uses Usual / not Core-only used
function program_I ( nLevel  AS Int ) AS DWord
return stacklevel

function program_C ( nLevel  AS DWord , lShowSig := FALSE AS Logic ) AS String 
if nLevel == 0
   *-- eases logic later...
   nLevel := 1
endif
return method name

function program_C (cEmpty := "" as String, lShowSig := FALSE AS Logic ) AS String
return program_C (program_I(-1), lShowSignature);

*--- Functions Calling into Core using Usuals
function program( nLevel  AS Int , lShowSig := FALSE AS Logic ) AS Usual
local uRet as Usual
if nLevel<0
   uRet := program_I(-1)
else
   uRet :=  program_C(nLevel, lShowSig)
endif
return uRet

function program(cEmpty := "" as Usual, lShowSig := FALSE AS LOGIC ) AS Usual
*-- mirror error throws of vfp on other data types if pCount()==1 ...
local uRet as Usual
uRet :=  program_C(program_I(-1), lShowSignature);
return uRet

Added Benefit of making functionality available to projects trying to stay in CORE with easy to remember names based on return value.

**Comment by lazy-fox** [comment] 2021-07-21 10:24
Urks, sorry forgot to mark code

**Comment by Karl1155** [comment] 2021-07-21 17:28
Thomas,

**_[...]
As I am still not totally clear on VO / X# NIL vs. vfp .Null. I leave it at that...
[...]_**

Here´s some code to compare the type detection results. It works with the 'VO' and 'Foxpro' dialect. The only compiler setting needed is /memvar. The reference dlls are Xsharp.Core, Xsharp.RT and XSharp.VFP

```
FUNCTION Start( ) AS VOID  
	
	
	? "Selected dialect is:" ,  __DIALECT__ 
    ? 
 	
	DO Test WITH 123 , , "test" // omit the second param 
	?
    #ifdef __DIALECT_FOXPRO__
		DO Test WITH 123 , .NULL.  // omit the third param 			
	#else		                                    
		DO Test WITH 123 , NULL   // omit the third param
	#endif
	
	?						
	
RETURN  

PROCEDURE Test
PARAMETERS one, two, three 
	    
? "PCount():" , PCount()
? "Values:" , one , two , three
? "IsNil():" , IsNil (one) , IsNil ( two) , IsNil ( three ) 
? "Type():" , Type ( "one" ) , Type ( "two" ) , Type ( "three" ) 
? "ValType():" , ValType ( one ) , ValType ( two ) , ValType ( three ) 

RETURN

```
What i do not understand: How do you detect with VFP omited params ? Type() returns in such cases .f.  , but it might also be a "real" logic ? 

Karl-Heinz

**Comment by RobertvanderHulst** [comment] 2021-07-21 17:47
Thomas,
Some remarks about your code suggestions:
If a function returns different types depending on the parameters then you can create a function that returns an OBJECT in the Core dialect and a USUAL in the other dialects. I personally do not like the program_I and program_c names, but others may have a different opinion of course. And your program_I is called with negative nLevel always in your code, so you can easily handle that in the same function and compare with 0 to switch to the alternative behavior.
You created 2 versions of functions (Program_I and Program_C) where one version has an nLevel parameter of type Int and the other version a Dword parameter. I think it makes more sense to use Int in both cases. 

If a function is not used a lot in the code (and I think this function is mostly used during debugging) then it does not make much difference if you use untyped parameters and PCount() or typed parameters.
I think for simplicity in this case Program should have 2 untyped parameters and have a parameter type check at runtime.
That will also make compilation easier and will help resolve problems when the parameters that are sent into Program() are usuals themselves.
For example 

```
LOCAL uLevel
uLevel = SomeFunctionThatReturnsALevel()
? Program(uLevel)
```
In code like this the compiler will not know if it needs to use the Program() with an Int parameter or the Program() with the string parameter and will throw a warning or error. 
Having a single function with a usual parameter will solve this. Inside the function we can check the parameter type and decide what to do.
The original test code from Karl uses literals , so the compiler knows to call the overload with the Int parameter.

**Comment by lazy-fox** [comment] 2021-07-22 02:00
Karl-Heinz:
older versions: Parameters()

> Returns the number of parameters passed to the most recently called program, 
> procedure, or user-defined function.
> PARAMETERS( ) is useful for determining how many parameters are passed to a 
> program, procedure, or user-defined function.
> The value returned by PARAMETERS() is reset every time a program, procedure, 
> or user-defined function is called or when ON KEY LABEL is executed. Unlike 
> PARAMETERS(), the PCOUNT() function does not get reset, so PCOUNT() may be 
> preferable in most programming situations.

newer versions, pcount(), as mentioned above. 
But often # of parameters is not necessary, there are situations where either different vartype() - which cannot fail in that case and is faster - or often a value check with empty()/evl() is enough.

regards
thomas

**Comment by RobertvanderHulst** [comment] 2021-07-22 06:22
Thomas,
In X# vartype() is definitely not faster than pcount().
The compiler translates pcount() into the equivalent of args:Length where args is the parameter array.

Robert

**Comment by Karl1155** [comment] 2021-07-22 10:46
Thomas,

In X#  Parameters() is marked as obsolete. Looking at this link 

https://hackfox.github.io/section4/s4g440.html

Parameters() doesn´t always seem to work as expected. With my Foxpro 2.0 i´m able to reproduce the described problem

```
PROCEDURE rtn1

PARAMETERS a, b, c

? "Parameters() returns", PARAMETERS()      && 3
? "Now I'll use a function"
= myudf(a)
? "Now parameters() returns", PARAMETERS()  && 1! <---------------------

RETURN
```

Is Parameters() still widely used in the VFP world ?

Karl-Heinz

**Comment by lazy-fox** [comment] 2021-07-24 08:02
Karl-Heinz,

> Is Parameters() still widely used in the VFP world ?
Only if 

- the code stems from a version created when PCount() was not available - and yes, there still are some stable things coded in FPW running in vfp mostly unchanged
- the developer has not learned about pCount() 

both encountered in the wild...

**Comment by lazy-fox** [comment] 2021-07-24 08:06
Robert,
> In X# vartype() is definitely not faster than pcount().
I wrote about it from vfp POV - Karl-Heinz might be asked to maintain or port vfp apps and it does help to know the reasons for coding things there, at least that I guessed as reason for his question

**Comment by lazy-fox** [comment] 2021-07-24 11:23
Robert,

> Some remarks about your code suggestions:...

I confess I am not totally happy with the ideas mysef, but let me explain some of my ideas leading to it.

Wolfgang showing examples only using Core / RDD are part of it. Core is the bedrock of X#, but not using Usuals has a smack of better optimized code. The GetWord* and aLines stuff I picked was done as a well defined subset of vfp  adding to the "swiss army knife" capability I often use in vfp and hope to get a well optimized implementation of.

Dotnet5 String.Split() added another of vfp flags, but is still lagging vfp alines() capability. The method signatures  of GetWord* and alines() allow implementation without Usual - and thereby should perform better. If well-typed vfp functions are not added to Core functionality (not inflating is also worthwhile...), it might be beneficial to split vfp specific functionality into a vfp_core and a vfp_usual dlls, allowing projects following Wolfgangs aim for always comiple-time checked and faster variables with some functions of vfp. Those vfp_core functions might also be used in VO based projects or mobile targeting future projects.

Now Program() seldom needs utmost speed - but the functionality offered is great in a library or 4GL to use in error handlers or logging. So having such well-typed **functionality** might interest VO coders (or Wolfgang-pureCore followers) or potential mobile targeters as well - But strong typing overloads HAVE some murky areas as you mention yourself, get murkier with defaults as my other ticket describes, as DotNet defines the need to have clearly different signatures to allow different return values and so on.

Vfp makes it even worse: Program(-1) returning Stacklevel and Program(nLevel) with cardinal nLevel returning function name IMO are not polymorph, (if such a thing exists for functions...). Vfp SHOULD have added a StackCount() function and not added the -1 functionality to program - which is the essence of the Program_C and Program_I.

On top comes my wish to keep programs runnable under both runtimes if porting - this continuing ability made porting from FPD or FPW to vfp a success where others failed expensively, as well as porting vfp to other Win runtimes by splitting vfp into COM segments and not forcing a total rewrite from scratch to play catchup to added maintainance, minimizing testing effort, allowing flexible budgeting by via pushing back time of last section port and other benefits.

My attitude of things to cover you can imagine: 
[](https://www.youtube.com/watch?v=hFDcoX7s6rE)
But after a bit of weighing vfp Program(-1) ugliness, I think following might tempt VO devs or at least make general code more succinct:

```
#define DWORDMAX 4294967295
function Program_StackCount() as DWord
function Program_Name(nLevel := DWORDMAX as DWord, lShowSig := FALSE AS Logic ) as String
if nLevel ==  DWORDMAX
   nLevel :=  Program_StackCount() -1
elseif nLevel == 0
   nLevel :=  1
endif
local cReturn as String
*-- well typed implementation
return cReturn
```
to put into vfp_core or even Core. Yes, even with the ugliness of magic number - it avoids other drawbacks. Optimal would be to define  Program_StackCount() as default for nLevel - but C# docs say constant needed for default IIRC. For ability to run such X# modified code back in vfp add there a simple X_2_Vfp.Prg with analogous function names coded to use in vfp:

```
***---- add library to vfp native projects 
function Program_StackCount()
    return Program(-1)-1
function Program_Name(nLevel, lShowSig) as String
if vartype(nLevel) == "L"
   nLevel :=  Program(-1)-1
endif 
return Program( nLevel) 

```
eliminating the wart of program(-1) and covering the added parameter  lShowSig which in vfp does nothing but needs to kept in source for X# needs. 
X# Developers porting vfp code or less interested in well-typed code still get a fully functional vfp implementation calling into vfp_core/Core defined better function interface:

function Program() as Usual
     return Program_Name(Program_StackCount()-1)
function Program(nLevel)  as Usual
     local uReturn
     if nLevel < 0
         uReturn = Program_StackCount()-1
     else
          uReturn = Program_Name(nLevel)
     endif
     return uReturn

and if developers find they need  lShowSig in X# implementation, they are prodded to the better interface found in vfp_core or Core, keeping the code runnable in vfp runtime with the minimal effort of loading the X_2_Vfp.Prg library.

Too much text, I know - but difficult to touch all topics with less and stay coherent (hoping this post still is, as I sometimes miss mentioning some reasons/ideas/motivations)

**Comment by lazy-fox** [comment] 2021-07-24 11:30
Hmmm, why is the link above gone after

> My attitude of things to cover you can imagine:

[](https://www.youtube.com/watch?v=hFDcoX7s6rE)

again not visible if checking in preview, but if added in raw version, so:
https://www.youtube.com/watch?v=hFDcoX7s6rE

**Comment by Karl1155** [comment] 2021-07-24 16:53
Thomas,

my Foxpro 2.0 doesn´t know PCount(), only Parameters(). I leave it up to the DevTeam to decide how to deal with the currently as obsolete marked Parameters() function. 

https://github.com/X-Sharp/XSharpPublic/blob/07d1f3456576f46aeb81e07352ad902b99502805/Runtime/XSharp.VFP/NotSupported.prg#L232

I didn´t dive in deeper, but IMHO a option to implement a Parameters() function is such a header declaration: 

#XTRANSLATE PARAMETERS() => PCount()

At least, this works 

```
#XTRANSLATE PARAMETERS() => PCount()

FUNCTION Start() AS VOID 

do test with 1 , , "test"  

RETURN

Procedure Test
Parameters para1 , para2  

? PCount() , Parameters()   // 3 , 3 

return
```

regards
Karl-Heinz

**Comment by lazy-fox** [comment] 2021-07-24 20:07
Karl-Heinz,
I am not so certain. If a function is implemented in X#, it should follow the basic - even sometimes erroneous - implementation found in todays vfp9.

If there is a program still using FPW/FPD that needs to be ported, I'd argue for moving to vfp9 first - and there replacing all parameters() with pCount() with GoFish or some other project wide search and replace tool - unless a good use case can be made NOT to port/test under vfp9 first. Yes, there are a few incompatibilities, but those should be found FIRST on fox side as to not murky the water with the implementation here - unless there is a real biz use case.

To buy vfp might be cheaper than to fund leeettle such things in X# - and if there is not enough reason to buy vfp9 development system, perhaps using ONLY the latest vfp runtime is enough. Back in vfp6 days there were tools to get a command window and a few basic tasks done **with runtime only** if  you went client side and did NOT want to install your own copy of vfp there to debug.

Strong Hint at dirty tricks mind: vfp9 runtime can compile single prg from runtime, can execscript and eval()!

I am not certain which COM capabilities are possible from such a command window and how much more vfp developer system adds in COM area - it has been a looong time since I played with Createobject("VisualFoxpro.Application"), Which gives an externally controlled activeX similar to CreateObject("InternetExplorer.Application") gave you controlled IE.

Best site for Runtime used to be wOOdy (probably linked on vfpX),
then check X# foxpro thread cmd with FoxPro in Forum for more of my hints.

If you are interested, and plan to install vfp9 runtimes, I can check if Ed Leafes Window can be made standalone exe fast...

Then you would have "poor mans vfp9", but still good enough to compile and run single prg files, which can house many procedures and functions... should be better for "vfp9 testing"

regards
thomas

**Comment by cpyrgas** [comment] 2022-01-24 10:32
It looks good to me, but I think I'd better let @lazy-fox confirm if this is indeed working as expected

**Closed** 2022-02-02 14:00 UTC
Labels: enhancement, Runtime, FoxPro
