### ISSUE TITLE
BLOBDirectPut function does not work

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#832] opened 2021-10-27 15:16 UTC
When testing an application transported from VO to X#, I found that the BLOBDirectPut (and possibly BLOBDirectGet) function does not work with the DBFCDX driver (and possibly other RDDs). After examining the X# SDK, I found that this operation is redirected to VoDbInfo(BLOB_DIRECT_PUT, ...), but the DBF RDD does not process this command. How can I quickly fix this problem?

**Comment by leon-ts** [comment] 2021-10-29 18:25
Chris,
There was a newsletter recently that a beta testing program is starting. I think it will be convenient for me and for other developers who have agreed to participate in this program to get a full-fledged installer with the beta version of X#.

**Comment by RobertvanderHulst** [comment] 2021-10-29 18:30
Leonid,
I'll try to finish the installer on Tuesday.

**Comment by leon-ts** [comment] 2021-10-29 18:47
Robert,
Yes, there will be time to test it next week.

**Comment by cpyrgas** [comment] 2021-10-31 12:34
Confirmed fixed

**Comment by cpyrgas** [comment] 2021-10-31 22:20
Talked to early, provided sample code seems to corrupt memory, will investigate why this is happening.

**Comment by cpyrgas** [comment] 2021-11-01 22:50
Strange, I cannot reproduce the problem anymore. Closing it again for now, Leonid please let us know if you see any problem with this function in your application.

**Closed by cpyrgas** 2021-11-01 22:50 UTC
Labels: bug, RDD

**Comment by leon-ts** [comment] 2021-11-02 06:41
Chris,
How does this problem manifest?
What do I need to pay attention to?

**Comment by cpyrgas** [comment] 2021-11-02 07:43
Leonid, when I added the test in our runtime suite, I started getting some strange unexplainable exceptions in a couple other completely different tests, which were going away when I removed again the whole or part of the test. But yesterday as I was trying to narrow down exactly what's causing it, the errors went completely away and I could not reproduce the problem at all no matter how many times I tried. Maybe it was a coincidence, something else going off, maybe not. If there's indeed a problem, I am sure you will see some kind of strange missfunction in your app after you call the function (or is it the rest of the sample code the culprit?). It should become very obvious.

**Comment by leon-ts** [comment] 2021-11-02 08:02
Chris,
Was it an AccessViolationException error?

**Comment by cpyrgas** [comment] 2021-11-02 08:08
Sorry, I don't remember anymore. I think that was one of the errors, but not sure, I had been dealing also with other problems from other people at the same time, so I might have that mixed up.

**Comment by leon-ts** [comment] 2021-11-02 08:22
Chris,
I'll explain why I'm asking about this particular error. Earlier in this ticket, it was suggested to replace the call to the Marshal.Copy function with MemCopy, passing in a pointer to a managed array.
> I changed
Marshal.Copy((IntPtr)pRecord, aRecordBuf, 0, nRecSize)
to
MemCopy(@aRecordBuf, pRecord, nRecSize)

This can cause problems. The garbage collector in NET works in a background thread, and can change the address of an array while the MemCopy function has not finished working. I myself ran into such a problem recently in my application. I had the following code transported from VO (approximate):
```
CLASS MyClass
    
    HIDDEN uData IS MYUNION // some union
    
    METHOD DoSomething() AS VOID
        ...
        MemCopy(@uData, pSomeSrcData, ... )
        ...
        RETURN

END CLASS
```
The uData field is actually located in dynamic memory and was moved during garbage collection. In VO, the garbage collector runs on the main thread, so the problem was potentially present, but never showed up. And in X# (.NET), it immediately began to appear.
Therefore, I would not recommend using the MemCopy function to copy managed objects.

**Comment by cpyrgas** [comment] 2021-11-02 08:49
Leonid, I used the original version of your sample, which is using Marshal.Copy(). I think you can see this in the commit here: https://github.com/X-Sharp/XSharpPublic/commit/75636e4eb2557fa0d90550c8853323cc0c7a00d2

**Comment by RobertvanderHulst** [comment] 2021-11-02 09:16
To avoid GC errors you could use a BEGIN FIXED .. END FIXED and get a Fixed pointer to the address of the array

**Comment by leon-ts** [comment] 2021-11-02 09:34
Robert,
The question is still in the internal structure of the managed array. For example, is the byte array allocated on the managed heap in a contiguous sequence and the same size as the unmanaged byte array, etc.

**Comment by RobertvanderHulst** [comment] 2021-11-02 12:02
The internal structure of the managed array of bytes is really an array of bytes.
But you have to be careful to take the address of the first element if you want to treat it like an unmanaged byte array.
In memory the first byte is prefixed with a header describing the type and other GC related things.

```
LOCAL aBytes as Byte[]
LOCAL pByte as BYTE PTR
.
.
// pByte := @aBytes This will not work
pByte := @aBytes[1] // This points the byte PTR to the first element in the array

```

**Comment by leon-ts** [comment] 2021-11-05 13:39
Guys,
It works well now!
