### ISSUE TITLE
Feature request: Indentation in Exception Descriptions

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#856] opened 2021-11-12 16:09 UTC
![screenshot1](https://user-images.githubusercontent.com/64518775/141497626-29925174-1990-42d0-8321-36be88285470.png)

Please add a space after the colon. Otherwise, the two sentences merge.

**Comment by cpyrgas** [comment] 2021-11-19 16:50
Well, change was made (and problem fixed in the ELSE part), but I do not see this method used anywhere, is this as intended?

**Closed by cpyrgas** 2021-11-19 16:50 UTC
Labels: enhancement, Runtime

**Comment by RobertvanderHulst** [comment] 2021-11-19 16:56
Leonid uses this.

**Comment by leon-ts** [comment] 2021-11-19 17:13
Guys,
I'm sorry, but I probably misplaced it. Just by searching, I found a similar text in this method.
In a real situation, it looks like this (exmaple):
```
LOCAL oError AS USUAL

BEGIN SEQUENCE
	
	LOCAL x AS INT
	x /= 0
		
RECOVER USING oError
	ErrorDialog( (Error)oError )
END SEQUENCE
```

**Exception message:**
> Exception raised by CLR or external code:Attempted to divide by zero.

**Comment by leon-ts** [comment] 2021-12-07 14:56
Guys,
Is it possible to remove this text altogether?
> Exception raised by CLR or external code:

It is added to all error messages (generated internally by BEGIN SEQUENCE), but in my opinion it is completely useless. You have to skip it with your eyes in order to read to that part of the text where the real reason for the error is described. Honestly, there is no useful information in it.
