### ISSUE TITLE
The "Find and Replace dialog" does not find all results

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#824] opened 2021-10-25 06:17 UTC
The "Find and Replace dialog" does not find all occurences (new version with fixes)

The problem is reproducable:
- Open two files of the solution
- Go to file one
- Close the solution
- Open the solution again
- Now file one is displayed. Now you have to search for something that occurs in file two.
- All results, except that of file two, are found.

**Comment by RobertvanderHulst** [comment] 2023-12-07 19:40
This seems to be fixed now. It was a problem in VS.

**Comment by cpyrgas** [comment] 2024-01-09 18:28
Judging from comment https://github.com/X-Sharp/XSharpPublic/issues/742#issuecomment-1244954332, I think it's safe to say this is confirmed fixed as well.

**Closed as completed by cpyrgas** 2024-01-09 18:28 UTC
Labels: bug, vs editor
