### ISSUE TITLE
Intellisense showing random class in some situations

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#843] opened 2021-11-04 14:35 UTC
![image](https://user-images.githubusercontent.com/9467830/140331990-e3ba0198-59b1-466b-8c2b-4dfa1bee77a3.png)
X# version is the latest beta.
The situation is on the screenshot. That hint for a string class is not expected. It may take one or two times of typing and deleting the last comma to get there. Though sometimes it shows a normal hint for the third argument as expected. It seems that it matters whether I'm typing or just navigating cursor to an already typed string, something like that.

**Comment by cpyrgas** [comment] 2021-11-04 17:08
Serggio, thanks for your report, but we would need some way to reproduce the problem in order to fix it. CAn you please see if you can reproduce it with this code in a small new prg and/or project?

**Comment by Serggio** [comment] 2021-11-04 18:54
Here you are: [TestISense.zip](https://github.com/X-Sharp/XSharpPublic/files/7477499/TestISense.zip)

**Comment by cpyrgas** [comment] 2021-11-04 22:58
Ah, thanks, now I understand the problem. Robert, it seems that when one of the arguments is a method call is another method/function call, then the parameter tip shows the incorrect argument number. For example, for this:

![intel23](https://user-images.githubusercontent.com/14542129/140431537-c9df3140-2e78-4821-9dea-0c48d218fdbb.png)

it makes bold the 2nd argument, instead of the 3rd one. In order to reproduce it, just copy & paste this code (do not type it, this way the behavior is different) and then type again the final comma:

```
FUNCTION Start()
LOCAL c AS STRING
SubStr( c, SLen(c) ,

```

**Comment by RobertvanderHulst** [comment] 2021-11-18 15:03
The problem was caused by the parentheses in the argument list. This is fixed now.

**Comment by Serggio** [comment] 2021-11-18 18:42
Nice to hear! May I ask you to check also situation when there is a string literal argument with parentheses inside it?
Something like: ```Substr("lalala(lala", 5)```
Because parentheses inside a string literal should not be taken into account, but it seems that they are analyzed either.
And also situation when expression is broken into several lines with ";" like this:
```
Substr("test";
          , 2, 3)
```

**Comment by cpyrgas** [comment] 2021-11-19 10:46
Original problem is fixed, but indeed parens inside literals do invoke and affect the tooltip, which shouldn't happen.
Also indeed there's no params tooltip when the expression is split in multiple lines (maybe this should be a separate ticket).

**Comment by RobertvanderHulst** [comment] 2021-11-19 12:40
Parens inside strings are taken care of.
I’ll look into multi line statements later

**Comment by cpyrgas** [comment] 2021-11-19 16:36
Wow amazing!

It does not work well with comments though :)
Following has the same problem with the previous problem with strings:

FUNCTION Start() AS VOID
Str("abcde" /* t,est */ , )

**Comment by RobertvanderHulst** [comment] 2021-11-19 17:15
This was fixed in an earlier commit today.

**Comment by cpyrgas** [comment] 2021-11-19 18:04
Robert, this commit has fixed the problem with strings and multiple lines, but the problem with block comments still remains.

**Comment by cpyrgas** [comment] 2021-12-21 16:59
Confirmed fixed!

**Closed by cpyrgas** 2021-12-21 16:59 UTC
Labels: bug, vs editor
