### ISSUE TITLE
The code that hangs the program

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#810] opened 2021-10-14 13:47 UTC
The following code hangs the program:

```
FUNCTION Start() AS VOID STRICT

	LOCAL o AS TestClass
	o := TestClass{}
	o:Start()
	
	RETURN

CLASS TestClass

	CONSTRUCTOR() STRICT
		RETURN
	
	PROTECT METHOD BadMethod(oParam AS OBJECT, dwParam AS DWORD, uParam AS USUAL /* Intentional mistake (typo): uParam must be REF or OUT */) AS VOID STRICT
		uParam := oParam
		RETURN

	METHOD DoSomething(lCallBadMethod AS LOGIC) AS LOGIC STRICT
		
		LOCAL uValue AS USUAL
		LOCAL lOk := FALSE AS LOGIC
		
		BEGIN SEQUENCE
			
			uValue := "Some string value"
			IF lCallBadMethod
				SELF:BadMethod(NULL, 0, @uValue)
			ENDIF
			
			lOk := TRUE // Here the program hangs!
			
		END SEQUENCE
		
		RETURN lOk

	METHOD Start() AS VOID STRICT
		SELF:DoSomething(FALSE)
		RETURN

END CLASS
```

The hang is reproducible when the method has a parameter of type USUAL, which, due to a typo, is declared as AS, instead of REF or OUT. At the same time, in the code, when this method is called, the parameter is passed by reference, as intended by the algorithm. A hang occurs when before exiting a TRY block (BEGIN SEQUENCE). When the program is executed, the problematic method is not called, but simply present in the code.

P.S. X# compiler ver. 2.9

**Comment by leon-ts** [comment] 2021-10-29 18:22
Guys,
I confirm that the problem is not critical. Solved by correcting a typo in the code. Another thing is that it was extremely difficult to detect. Thus, this problem is more interesting than critical.

> That's is because when you use the @ operator in an argument and /vo7 is enabled, then this must always be treated as "BY REF" operator, not addressof. If you want to use addressof on a param when vo7 is enabled, then you either need to use the (PTR) cast, or break the method call in two steps using a temp local for holding the address of.

I fully support this remark!

**Comment by RobertvanderHulst** [comment] 2021-10-29 18:34
Ok, guys. So what you are saying is:
- When VO7 is enabled
- When a parameter in a function / method call is prefixed with an @ sign
- Then it MUST be treated as REF
- If you want to pass the address of something, then you must either assign it to a local first or you must add the (PTR) cast

The good news is that this will be relatively easy to implement !

**Comment by leon-ts** [comment] 2021-10-29 19:05
Robert,
for my part, I confirm this, but with the clarification that we are talking about the USUAL type:
```
FUNCTION Test1 (uParam AS USUAL) AS VOID
    RETURN

FUNCTION Start () AS VOID
    LOCAL uValue AS USUAL
    Test1( @uValue) // error: unexpected REF
    Test1( (PTR)@uValue) // correct: passing the address of a variable uValue
    RETURN
```
But in the following example, both operations must be correct:
```
FUNCTION Test1 (ptrParam AS PTR) AS VOID
    RETURN

FUNCTION Start () AS VOID
    LOCAL nValue AS DWORD
    Test1( @nValue ) // correct: implicit passing the address of a variable nValue
    Test1( (PTR)@nValue ) // correct: explicit passing the address of a variable nValue
    RETURN
```

**Comment by RobertvanderHulst** [comment] 2021-10-29 19:05
I did a quick and dirty test and found that a change like that would break some of our existing test cases.
For example C291, which compiles with /vo7+
```
VOSTRUCT _WINWIN32_FIND_DATA
	MEMBER DIM cFileName[ 10 ] AS BYTE

FUNCTION Start() AS VOID
	LOCAL pData IS _WINWIN32_FIND_DATA
	pData:cFileName[1] := 65
	pData:cFileName[2] := 66
	pData:cFileName[3] := 67
	
    LOCAL cTemp AS STRING
    cTemp := Psz2String(@pData:cFileName)   // Error  A REF or OUT value must be an assignable variable
    ? cTemp
```
In this case we are indeed passing the address of pData:cFileName as a pointer.
My "quick and dirty" solution had changed this to
`    cTemp := Psz2String( REF pData:cFileName)   // Error  A REF or OUT value must be an assignable variable`
Which is not correct for situations like these

**Comment by RobertvanderHulst** [comment] 2021-10-29 19:07
To do this (change @ to REF) only for the USUAL type we cannot do this in the earlier phase of the compiler, since the types are not known there. We would have to change this later and that is more work.
I'll wait with this until after 2.9.1

**Comment by leon-ts** [comment] 2021-10-29 19:12
Robert,
I agree, this is not critical now. It is better to do this later only for the USUAL type. For strongly typed parameters with pointer types, this is definitely not necessary!

**Comment by cpyrgas** [comment] 2021-10-29 23:20
I agree, leave it for after this release. But what is the rule now then? When does the compiler treat @ as an addressof and when as the byref operator? Also the answer to this can wait...

**Comment by RobertvanderHulst** [comment] 2021-11-01 07:47
Chris,
There is no easy and short answer to this. But let's try to do this anyway:
- The parser parses the @ operator as a so called "prefixexpression", just like ++i or +i
- This particular prefix expression will be translated to the AddressOfSyntax for Roslyn
- Inside the parser rule that matches arguments for function and method calls there is a check for the dialect. FoxPro, Harbour and XBase++ do not know the @ operator, so when the @ operator is detected inside an argument we change the @ operator and replace it with the REF keyword. In the other dialects (Core, VO and Vulcan) we leave the operator as is. In those dialects we sometimes do want to pass the address.
- Later in the compiler when the binder tries to match arguments passed to method/ function calls and the declared parameters there is a check to see if REF and AS are matched correctly. When /vo7 is enabled then this code will treat the @ operator as an alternative to REF when the declared parameter is declared as REF or OUT. In the example above the parameter was declared "AS USUAL" so that translation did not take place. And as a result the compiler was trying to pass the address of the argument to the function call.
- The code that was created was clearly not OK. I would have expected the compiler to create a new usual of type PTR, but that did not happen.

If we want to change something in this code we should probably change the rule translates @ to REF and only allow the AddressOf to be passed to parameters that are declared with a pointer type (such as PTR, IntPtr, a VOSTRUCT, PSZ or any kind of type PTR). In other cases we should probably always replace @ with REF and let the compiler produce an error about passing a REF to a parameter that is declared as AS

**Comment by cpyrgas** [comment] 2021-11-01 08:32
Robert, thanks, although there must be more to it, because the compiler seems is "smart" enough in some cases with untyped calls to recognize if the intended use of @ is the address of or byref operator. In this sample, in the first case it uses byref and in the second addressof, which is indeed the intended use:


```
// vo7+
FUNCTION Untyped(a)
? "Received:",a
a := "updated"
RETURN NIL

VOSTRUCT sss
MEMBER m AS INT

FUNCTION Start() AS VOID
LOCAL u AS USUAL
u := "start"
Untyped(@u)
? u

LOCAL s IS sss
s.m := 123
Untyped(@s)
? s
```

It seems that the current behavior is mostly working, because I can't recall any recent related reports, or having seen myself problems anymore when testing existing VO code etc, so I think let's just leave it exactly as it is, at least for now.

**Comment by cpyrgas** [comment] 2021-11-01 08:41
What maybe could be changed, is to make the compiler throw an error in cases where @ is used on a usual var, with the meaning of adressof? Because from what I see (as probably expected) this does not work in VO and also in X# I get strange runtime errors using it:

```
FUNCTION Start() AS VOID
LOCAL u AS USUAL

// Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
u := 123
? @u

// Unhandled Exception: System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
u := "abc"
? @u
```

So also in the original code from Leonid, an error should be reported by the compiler, because it is calling a strongly typed function and in this case the @ operator can be translated to BYREF (since the param is typed with AS), neither it can be used as the addressof operator on a USUAL var. But this is low priority, let's leave it for now and deal with it in another build.

**Comment by RobertvanderHulst** [comment] 2021-11-01 08:55
Chris,
Yes there is more to it. That is why I wrote that there is no short answer.
For clipper calling convention the compiler does not really create REF parameters.
- Instead it creates an array of usuals and fills this array with the values of the arguments. For values that are passed by reference it also sets the flag in the usual that the parameter was passed by reference.
- Inside the code of your untyped function the compiler generates code to write back the changed value of 'a' into the array of usuals. It does that for all arguments that were changed in the context of the method / function, regardless if the parameter was passed by reference or not. We could optimize that and only assign back when variable has the 'byreference' flag set, but that would not make the code faster.
- After the call to untyped() the values inside the array are assigned back to the passed arguments, for the arguments that were passed by reference. At that moment there may be a runtime error, for example when you assigned a string to a parameter but the value that was passed by reference was of a different type.

For late bound code something similar happens, but of course the call to Untyped is then replaced with a call to the Send() or __InternalSend() function

**Comment by cpyrgas** [comment] 2021-11-01 17:40
Robert,

> Chris, Yes there is more to it. That is why I wrote that there is no short answer. For clipper calling convention the compiler does not really create REF parameters.
> 
>     * Instead it creates an array of usuals and fills this array with the values of the arguments. For values that are passed by reference it also sets the flag in the usual that the parameter was passed by reference.
> 

Yeah, I meant regarding the decision of the compiler if it interprets @ as byref or addressof. So in late bound calls and/or early bound calls of untyped methods, does the compiler always treat @ as byref? Meaning it always sets the flag in the usual param? Or are there again exceptions in which cases those arguments are treated as addressog, so the usual param flag is not set, but the usual param contains the addressof the original var?

**Comment by RobertvanderHulst** [comment] 2021-11-02 10:22
Chris,
There are very many references to the AddressOf operator the the /vo7 compiler option all over the compiler code. I do not have a short answer. I would have to run several tests through the debugger to answer this.

**Comment by cpyrgas** [comment] 2021-11-02 15:52
OK, I suspected this is the case. Please leave it as it is then. If we come across some problem in the future, we can revisit all this, but for the time being it's looking to be working well (considering it's impossible to make it work perfectly, due to the fundamental difference between VO and .Net in regards to REF/addressof)

**Comment by cpyrgas** [comment] 2021-11-24 21:00
Same problem causes also this: https://www.xsharp.eu/forum/private-product/2776-x-2-9-1-1-bbrowser-hangs-when-start-from-vs

Still can't see a way to "fix" the problem universally though, without also breaking existing code...

**Comment by RobertvanderHulst** [comment] 2021-11-24 22:37
At this moment the compiler detects that the @ character is used to pass a value by reference when the receiving function / method has a REF parameter.
I'll try to change the code to also treat the @ character as a REF when the receiving function has a parameter AS USUAL and when the value is a USUAL.
In that case the compiler will generate the same error that you would get when you had used the REF in the code.

**Comment by cpyrgas** [comment] 2021-11-25 00:19
Right, this makes sense and should no break any existing code. I hope nobody in VO is passing the address of a usual to a function...

Btw, VO allows even this:

```
FUNCTION Start() AS INT
LOCAL n AS INT
n := 123
test(@n)
? n

PROCEDURE test(u AS USUAL)
u := 345
```

and the value 345 does go back to the caller...!

in X#, this also compiles, but at runtime throws a NullReferenceException. Not sure if this can also be intercepted and make the compiler report an error here as well...

**Comment by RobertvanderHulst** [comment] 2021-11-25 11:19
Please note that I had to change one test case (C325) where we were printing the address of a usual.
This test case had /vo7 enabled and now the ? @pData:ftCreationTime was calling the QOut function with the parameter 
REF pData:ftCreationTime.
I have hardcoded an exception in the compiler that allows to pass the address of a variable to the QOut() and QQOut() functions when this function is called by the ? or ?? commands.
If you call QOut() or QQOut() directly then you first need to assign the address to a variable of type PTR and pass that variable to these functions.

**Comment by cpyrgas** [comment] 2021-11-25 12:33
OK, this sounds good, too!

**Comment by cpyrgas** [comment] 2021-11-29 10:45
Unfortunately it seems this fix has sideefects, tests C780 and R729 are now failing at runtime.

Robert, this are is really tricky area and making one small change might lead to runtime errors in user code that might be very difficult to find, so maybe it's better to just rewind all the changes and leave it as it was before, which was mostly working ok (well, compatible to VO in most cases at least). We can document the behavior that is still not compatible and can't really be and I swear not to log a related ticket again in the future :)

**Comment by RobertvanderHulst** [comment] 2021-11-29 11:01
C780 and R729 run fine here.
Did you rebuild the compiler yourself?
Or did you use the latest build on GitHub.
I see that I had not merged my latest changes with the main branche yet. I have done that now.

**Comment by cpyrgas** [comment] 2021-11-29 18:53
Ah, that's it then, no I can't compile the compiler, I'm always downloading it from https://github.com/X-Sharp/XSharpDev/actions
Seems the one with your latest changes in not available yet, will wait for it.

**Comment by cpyrgas** [comment] 2021-11-30 08:47
Yeap, they run fine also here now! Let me do some more testing and I will confirm the fix.

**Comment by cpyrgas** [comment] 2021-11-30 23:14
I have found several errors in existing code. For example this is from Karl's code that he sent me today:

```
// error XS9109: Argument 2 may not be passed with the '@' prefix
FUNCTION Start() AS VOID
LOCAL nHandle	AS IntPtr
LOCAL sInstall	IS ADS_MGMT_INSTALL_INFO
LOCAL nInstall	AS WORD
AdsMgGetInstallInfo(nHandle,@sInstall,@nInstall)
```

This is from my own old VO app:

```
// error XS9109: Argument 3 may not be passed with the '@' prefix
// error XS9109: Argument 4 may not be passed with the '@' prefix
FUNCTION Start() AS VOID
LOCAL DIM buf[ BUFLEN ] 	AS BYTE	
IF ! ( LoadString( _GetInst(), 123, @buf, 456) == 0 )
	AppendMenu( NULL_PTR, 123, 456, @buf )
ENDIF
```

**Comment by RobertvanderHulst** [comment] 2021-12-01 10:20
I'll look into this. In general taking the address of a managed structure should be avoided at all times, with only a few exceptions.
At first sight I need to add the following 'exceptions' when taking the address should be allowed:
- local declared with `IS <VostructOrUnion>`. I need to check if this requires special handling to 'fix' this
- local declared with DIM (this gets compiled into a fixed buffer)
- address of an element inside a `<VostructOrUnion>` (regardless if this is declared with AS or IS)

**Comment by cpyrgas** [comment] 2021-12-01 10:37
Robert, dozens of error come from the SDK itself, so it's no surprise that I've found 100s of occurrences in users' code as well. I tried to include as many separate cases as I could, but probably there are more that I have missed.

**Comment by RobertvanderHulst** [comment] 2021-12-01 17:35
Chris,
I am committing this to the main branch now, so you can test again.
I fixed the issues in C815 and tested compiling all tests and the Runtime.
The code generation for code that has a DIM array is changed a bit.
We were already created a FIXED variable that points to the first element of the array, but we were not using this variable.
I am now using this FIXED pointer in the @ operation.

**Comment by cpyrgas** [comment] 2021-12-01 23:32
Robert,
Oh, that's great, it works almost alway now! I have only found this case (in existing code) so far that fails, but I am not so sure if it was really working before either:

```

CLASS TestClass
	METHOD Test(n AS INT, rf REF INT) AS VOID
		rf := 456
END CLASS

FUNCTION Start() AS VOID STRICT
LOCAL o AS OBJECT
o := TestClass{}
LOCAL rf := 123 AS INT
// error XS1615: Argument 4 may not be passed with the 'ref' keyword
Send(o, "Test", 1, @rf)
? rf
```

I'll do some further testing...

**Comment by cpyrgas** [comment] 2021-12-01 23:58
Also found this one (used several times in an app), but I guess this wasn't working correctly before either, right? (I will test with older versions tomorrow)

```
FUNCTION Test( cDesc AS STRING, cString ) AS VOID STRICT
cString := "modifed"

FUNCTION Start() AS VOID
LOCAL cTest := "passed" AS STRING
// error XS1615: Argument 2 may not be passed with the 'ref' keyword
Test( "abc", @cString )
? cString
```

**Comment by cpyrgas** [comment] 2021-12-02 00:12
A couple more:

```
FUNCTION Start() AS VOID
LOCAL nInt AS INT
LOCAL nDword AS INT
// error XS1503: Argument 2: cannot convert from 'out int*' to 'out USUAL'
VoDbSelect( 123,  @nInt ) 
VoDbSelect( 123,  @nDword )
```

and

FUNCTION TestRef(cBuffer REF STRING) AS VOID
cBuffer := "modified"

```
FUNCTION Start() AS VOID
LOCAL uBuffer := "init" AS USUAL
// error XS1503: Argument 1: cannot convert from 'ref System.IntPtr*' to 'ref string'
TestRef( @uBuffer)
? uBuffer
```

**Comment by cpyrgas** [comment] 2021-12-02 10:13
I have edited the above comments with info about what was happening in the previous builds, apparently there's only one new problem (the one with the OUT parameter) and the other compiler errors are now good, because they point to code that was not working previously at runtime as intended. The final one is still a mystery to me, I am still investigating.

I have updated C815 with a couple more test cases and added runtime testing to it. I have also added C816 which must report errors at compile time (now it does, but it didn't in previous builds).

**Comment by cpyrgas** [comment] 2021-12-02 11:05
One more case, this reports an error XS9109: Argument 2 may not be passed with the '@' prefix:

```
FUNCTION Start() AS VOID
LOCAL pHandle, pByte AS BYTE
FRead3(pHandle, @pByte, 1)
```

But the problem happens only when XSharp.Core.dll is before XSharp.RT.dll in the list of the project references. If they have been entered the other way around (you can easily do this in XIDE), then there is no error message. Apparently this happens because those two libraries have 2 overloads of the FRead3() function. But should the order of references have any effect really?

**Comment by RobertvanderHulst** [comment] 2021-12-03 15:44
The reason why the test case with FRead3() failed when the references are in a different order, is that in this case there are several overloads for FRead3().
The Roslyn code was calling a method that we have adjusted several times to determine the right overloads and then finally one more time for the correct overload to adjust the arguments to match the parameters.

I was not checking for this and was already adjusting the arguments during the phase where Roslyn is trying to figure out the right argument.

**Comment by cpyrgas** [comment] 2021-12-05 11:48
Robert, it looks good now, although there are two side effects I see in existing code, both with having /vo3 DISABLED:

1. Taken form C091, this now warning XS0114: 'ChildClass.OnTest()' hides inherited member 'ParentClass.OnTest()', while before it was overriding the parent method (for vulcan compatibility). I think the new X# behavior is correct, just mentioning that we might be breaking some existing code (ported from vulcan mainly).

```
CLASS ParentClass
	VIRTUAL METHOD OnTest() AS STRING
		? "parent"
	RETURN "parent"
END CLASS

CLASS ChildClass INHERIT ParentClass
	METHOD OnTest() AS STRING
		? "child"
	RETURN "child"
END CLASS

```

2. The following now reports error XS0154: The property or indexer 'Child.Text' cannot be used in this context because it lacks the get accessor. Found this in a couple dozen places. The solution is easy, define an ACCESS in the child class as well, but not sure why this was working before and if it should be still working in the new build now

```
FUNCTION Start() AS VOID
LOCAL o AS Child
? o:Text
RETURN

CLASS Parent
PROPERTY Text AS STRING AUTO
END CLASS

CLASS Child INHERIT Parent
ASSIGN Text(c AS STRING) AS VOID
END CLASS
```

**Comment by cpyrgas** [comment] 2021-12-24 16:41
Nice, looks very good to me now!

**Closed by cpyrgas** 2021-12-24 16:41 UTC
Labels: bug, Compiler
