### ISSUE TITLE
XBase++ preprocessor: #command and #translate unexpected behaviour

### ISSUE THREAD

**Issue by Danila2903** [X-Sharp/XSharpPublic#915] opened 2022-01-17 07:02 UTC
I've tried to test XSharp preprocessor for translating examples from Xbase++ documentation. You can find them in the Example section: https://doc.alaska-software.com/content/fdc_xpplrm_hashcommand_pipe_hashtranslate.html
I've tested in X# v29a, with xsc.exe with -ppo parameter.

**To Reproduce**
1. Create CH and PRG file (e.g. _test.ch_ and _test.prg_)
2. Copy text from the needed section in files respectively.
3. Include test.ch in test.prg
4. Call
`xsc.exe -ppo test.prg` 
5. Compare result

## Test 1

**List match marker => Smart stringify result marker**

_** CH file_ 
```
#command  COPY STRUCTURE TO <(dbFile)> [FIELDS <fields,...>] ; 
   =>  DbCopyStruct( <(dbFile)>, {<(fields)>} ) 
```

_** PRG file_ 
```
COPY STRUCTURE TO (cFileName) FIELDS (cField1), (cField2) 
```

**Expected behavior**
`DbCopyStruct( (cFileName), { (cField1), (cField2) } ) `

**Result**
`DbCopyStruct( "cFileName" , {cField1 ), ( cField2 } )`

## Test 2
**Extended expression match marker => Smart stringify result**
Actually, the example from documentation works well, but I have problems when I put extended expression match maker in brackets. This example works in standart Xbase++ preprocessor, but doesn't in XSharp:

_** CH file_ 
`#translate RENAME(<(oldFile)>)  =>  RENAMEDFILE(<(oldFile)>)`

_** PRG file_ 
`RENAME(Temp.dbf)`

**Expected behavior**
`RENAMEDFILE("Temp.dbf")`

**Result**
`RENAME(Temp.dbf)`

## Test 3
**Control structure REPEAT...UNTIL**
_** CH file_ 
```
#command  REPEAT ; 
      =>  DO WHILE .T. 

#command  UNTIL <lExp> ; 
      =>  IF (<lExp>) ;; 
             EXIT ;; 
          ENDIF ;; 
          ENDDO 
```

_** PRG file_ 
```
REPEAT 

   nKey := Inkey(0) 

UNTIL nKey == K_ESC 
```

**Expected behavior**
```
DO WHILE .T. 

   nKey := Inkey(0) 

IF (nKey == K_ESC) ; EXIT ; ENDIF ; ENDDO 
```

**Result**
```
DO WHILE .T.

      nKey := Inkey(0)

IF (nKey==K_ESC ) 
EXIT 
ENDIF 
 ENDDO
IF (nKey==K_ESC ) ;EXIT ;ENDIF ; ENDDO
```

## Test 4
This test I've found in XSharp preprocessor documentation. File is: _XSharpDev/XSharp/src/Compiler/XSharpCodeAnalysis/Preprocessor/preprocessor.txt_ (https://github.com/X-Sharp/XSharpDev/blob/main/XSharp/src/Compiler/XSharpCodeAnalysis/Preprocessor/preprocessor.txt)

_** CH file_ 
```
#command LIST [<list,...>]                                              ;
         [<off:OFF>]                                                    ;
         [<toPrint: TO PRINTER>]                                        ;
         [TO FILE <(toFile)>]                                           ;
         [FOR <for>]                                                    ;
         [WHILE <while>]                                                ;
         [NEXT <next>]                                                  ;
         [RECORD <rec>]                                                 ;
         [<rest:REST>]                                                  ;
         [ALL]                                                          ;
                                                                        ;
      => __dbList(                                                      ;
                   <.off.>, { <{list}> }, .t.,                          ;
                   <{for}>, <{while}>, <next>, <rec>, <.rest.>,         ;
                   <.toPrint.>, <(toFile)>                              ;
                 )
```

_** PRG file_
`LIST FIRSTNAME, LASTNAME TO PRINTER WHILE LastName < "K"`

**Expected behavior**
```
__dbList(.F., { { || FIRSTNAME}, {|| LASTNAME} }, .t., , 
	         {||LastName < "K"}, , , .F., .T. ,)
```

**Result**
```
__dbList( .F., { { || FIRSTNAME, LASTNAME} }, .t.,  , 
	         {||LastName<"K"} ,  ,  , .F. , .T. ,  )
```

**Comment by RobertvanderHulst** [comment] 2022-01-18 12:42
We will look at this asap

**Comment by RobertvanderHulst** [comment] 2022-01-27 10:07
Test 1: Confirmed
Test2: Confirmed. If you put a space after the filename then it works
Test 3: REPEAT UNTIL is a standard command in X# and no UDC is needed. However in the current X# 2.10 build this works as expected
Test 4: Confirmed

I will fix this asap.

**Comment by RobertvanderHulst** [comment] 2022-01-27 10:08
BTW I have inspected this with the X# UDC Tester (Tools/XSharp/X# UDC Tester in the VS menu)

**Comment by Danila2903** [comment] 2022-01-27 11:14
Robert,

Thank you for your answer!
1) About test 2: will it work without spaces after the filename in next releases? We have lots of usages of it.
2) About test 3: where can I get X# 2.10? It is still only 2.9a Cahors version on xsharp.eu.
P.S. We still compile with xsc.exe, so for now we can't use X# UDC Tester. :)

**Comment by RobertvanderHulst** [comment] 2022-01-27 11:50
Danila,
test2: will be fixed in 2.11
X# 2.10 is available for subscribers only now. A public release will become available in a few days.
The X# UDC tester is only there to help debug UDC problems. Not to compile your program

**Comment by kpa174** [comment] 2022-02-15 07:21
> Test 3: REPEAT UNTIL is a standard command in X# and no UDC is needed. However in the current X# 2.10 build this works as expected

X# Compiler version 2.10.0.3 (public)

**source:**
#command IBSKIP(<oIBrowse>) ;
=>  if eval(<oIBrowse>:SkipBlock,1,<oIBrowse>) != 1 ;;
        Exit ;;
    endif

    while .t.
        IBSKIP(o)
    enddo

**expected (xbase compiler):**
    while .t.
        if eval(o:SkipBlock,1,o) != 1 ;Exit ;endif
    enddo

**actual (x# compiler):**
    while .t.
if eval(o :SkipBlock,1,o ) != 1 
Exit 
 endif
if eval(o :SkipBlock,1,o ) != 1 ;Exit ; endif
    enddo

**Comment by RobertvanderHulst** [comment] 2022-02-15 07:27
This is a known problem in the current X# compiler in the PPO output. The actual code (that you can inspect with a tool like ILSpy) is Ok. The problem is already fixed in the current development build.
The problem is that for UDCs that expand to multiple statements these statements are included in the PPO output twice.

**Comment by cpyrgas** [comment] 2022-02-21 10:09
Confirmed fixed

**Closed by cpyrgas** 2022-02-21 10:09 UTC
Labels: enhancement, Compiler, Xbase++
