### ISSUE TITLE
Intellisense shows function parameters incorrectly in some cases

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#728] opened 2021-07-14 16:04 UTC
1. If, after entering the parenthesis, no parameters have been entered yet, or the parameter string begins with a space, then Intellisense correctly displays the function signature.
2. If the first parameter is another function, then Intellisense does not show the signature of the base function, but shows the signature of the function that comes in the first parameter.

```
FUNCTION Start() AS VOID STRICT
 	
	// CORRECT
	MyFunc1( // singnature of function MyFunc1 shows correctly
	
	// NOT CORRECT
	MyFunc1(MyFunc2()) // If you rewrite the opening parenthesis of the function MyFunc1, the signature of the function Func2 will be shown
	
	// CORRECT
	MyFunc1( MyFunc2()) // If you rewrite the opening parenthesis of the function MyFunc1 when there is a space between the parenthesis and the string MyFunc2, then will show the correct signature of the function MyFunc1
	
	RETURN

FUNCTION MyFunc1(nParam AS INT) AS STRING
	RETURN nParam:ToString()

FUNCTION MyFunc2() AS INT
	RETURN 1
```

**Screenshot:**
![FuncParams](https://user-images.githubusercontent.com/64518775/125654627-b4c25be0-66b5-45f2-9568-342d2524abbd.png)

**Comment by cpyrgas** [comment] 2021-07-30 15:48
I still see the problem. Note that the problem does not happen when typing the code normally, but for this already existing code:

MyFunc1(MyFunc2())

try deleting and re-typing either of the two open parens, in both cases the tooltip refers to the wrong function

**Comment by cpyrgas** [comment] 2021-10-30 15:12
It's fixed now!

**Comment by leon-ts** [comment] 2021-11-19 09:34
Guys,
This problem has not been resolved!
X# 2.9.1.1 (last official release)

**Comment by cpyrgas** [comment] 2021-11-19 09:53
I had given it much testing after the latest fix and it looked fine, also tested again now and still looks fine. Leonid, can you still reproduce the problem with the original instructions you posted, or is it a little different now?

**Comment by leon-ts** [comment] 2021-11-19 10:04
Chris,
I got the situation in a real project, and then I double-checked with the original example in this ticket. After the original example showed the problem as well, I wrote a previous post.

**Screenshot:**
![screenshot1](https://user-images.githubusercontent.com/64518775/142604043-52531169-2119-4067-a566-b132b2812f23.png)

The problem also occurs for any parameter if there is no space between the opening parenthesis and the parameter. For example: `MyFunc(1)` does not show the parameters of the MyFunc function at all. But if you put a space between the open parenthesis and 1, then the parameters are displayed.

**Comment by leon-ts** [comment] 2021-11-19 10:06
Addition: VS 2019 16.11.7 (if it matters)

**Comment by cpyrgas** [comment] 2021-11-19 10:11
That's strange, it works perfectly here in both VS2017 and VS2019. Let's see if Robert can reproduce this.

**Comment by RobertvanderHulst** [comment] 2021-11-19 11:41
I could reproduce it.

**Comment by RobertvanderHulst** [comment] 2021-11-19 16:14
The fix is included in another commit

**Comment by cpyrgas** [comment] 2021-11-19 16:18
I could not reproduce the problem either before, so I will let Leonid confirm this fix.

**Closed** 2021-12-29 17:47 UTC
Labels: bug, vs editor
