### ISSUE TITLE
Compiler crash (beta version 2.17.0.2)

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#1306] opened 2023-08-01 16:40 UTC
The attached application crashes the compiler.
I have not looked further into it.
[Application1.zip](https://github.com/X-Sharp/XSharpPublic/files/12232018/Application1.zip)

**Comment by wriedmann** [comment] 2023-08-01 16:46
I have now looked better, and problem seems to be this property:

property IDataErrorInfo.Item[cColumnName as string] as string
	get
		local cReturn			as string

		cReturn				:= ""

		return cReturn
	end get
end property

that is a part of the IDataErrorInfo interface implementation

**Comment by wriedmann** [comment] 2023-08-01 16:51
The problem seems to be the missing "using System.ComponentModel" clause.

**Comment by RobertvanderHulst** [comment] 2023-08-02 12:43
C# only has support the `this` property with an indexer. There was a problem in our code that adds this support for properties with another name, in combination with the explicit interface declaration and the fact that the interface could not be found due to a missing `using` statement.
Another customer had reported something similar, but could not produce a simple example.

**Comment by RobertvanderHulst** [comment] 2023-08-02 12:44
This will be included in the 2.17.0.3 build

**Comment by cpyrgas** [comment] 2023-08-02 20:17
Confirmed fixed

**Closed by cpyrgas** 2023-08-02 20:17 UTC
Labels: bug, Compiler
