### ISSUE TITLE
VS 2022 and XS 2.13.2.0 First builds not starting together with Nuget usage

### ISSUE THREAD

**Issue by ArneOrtlinghaus** [X-Sharp/XSharpPublic#1114] opened 2022-09-08 13:27 UTC
**Describe the bug**
Same as before with Bug VS 2022 and XS 2.13.1.1 First builds not starting together with Nuget usage
Volkmar wrote:
I tested the new Beta Version 2.13.2 with our AcsLib solution. The problem is not fixed.

He installed XSharpSetupFox2.13.2.0.exe

**Comment by RobertvanderHulst** [comment] 2022-09-08 14:24
That's really strange. Over here the new version of X# does fix the issue.
Can we do a online session tomorrow (Sept 9) , after 10:00

**Comment by fxxm** [comment] 2022-10-08 11:41
@RobertvanderHulst @ArneOrtlinghaus Are there simple steps to reproduce this? 

Fix https://github.com/X-Sharp/XSharpPublic/commit/2119d1dab7b17a724881e5447f5efd119b32b4af seems to cause other issues that I'm looking into.

**Comment by RobertvanderHulst** [comment] 2022-10-08 11:54
Fergus,
What Arne experiences was that after opening the solution the first (re)build took for ever to start (this was when the option to automatically restore missing packages). After aborting the build, for example by trying to close VS, then a second attempt to (re) build started normally.
What other issues are you seeing

**Comment by fergus-azyra** [comment] 2022-10-08 12:03
It reintroduces the error in VS2022 that presumably you were fixing in bf1e4cfbd0cb18adad955270fa8dc7e4609b7a28

I would like to point out that the only reason I know about this error is that I turned on the serilog output in the registry. It appears to be having no impact on us.

2022-10-07 20:39:35.417 +01:00 [ERR] 0016 BuildFinishedHandler
System.Runtime.InteropServices.COMException (0x8001010E): GetNativeEnvironmentInterop must be called on the UI thread.
   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
   at Microsoft.VisualStudio.CommonIDE.Solutions.NativeExtensions.GetNativeEnvironmentInterop()
   at Microsoft.VisualStudio.CommonIDE.Solutions.BuildManager.SolutionBuildManager.CSUIBuilder.OutputStringThreadSafe(String pszOutputString)
   at Microsoft.VisualStudio.Project.IDEBuildLogger.FlushBuildOutput() in C:\XSharp\DevPublic\VisualStudio\ProjectBase\IDEBuildLogger.cs:line 383
   at Microsoft.VisualStudio.Project.IDEBuildLogger.BuildFinishedHandler(Object sender, BuildFinishedEventArgs buildEvent) in C:\XSharp\DevPublic\VisualStudio\ProjectBase\IDEBuildLogger.cs:line 198
   at XSharp.Project.XSharpIDEBuildLogger.BuildFinishedHandler(Object sender, BuildFinishedEventArgs buildEvent) in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\XSharpIDEBuildLogger.cs:line 89
2022-10-07 20:39:35.420 +01:00 [DBG] 0001 SetBuildConfigurationProperties Debug|Any CPU

**Comment by fxxm** [comment] 2022-10-08 12:06
It reintroduces the error in VS2022 that presumably you were fixing in https://github.com/X-Sharp/XSharpPublic/commit/bf1e4cfbd0cb18adad955270fa8dc7e4609b7a28

I would like to point out that the only reason I know about this error is that I turned on the serilog output in the registry. It appears to be having no impact on us.

2022-10-07 20:39:35.417 +01:00 [ERR] 0016 BuildFinishedHandler
System.Runtime.InteropServices.COMException (0x8001010E): GetNativeEnvironmentInterop must be called on the UI thread.
at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
at Microsoft.VisualStudio.CommonIDE.Solutions.NativeExtensions.GetNativeEnvironmentInterop()
at Microsoft.VisualStudio.CommonIDE.Solutions.BuildManager.SolutionBuildManager.CSUIBuilder.OutputStringThreadSafe(String pszOutputString)
at Microsoft.VisualStudio.Project.IDEBuildLogger.FlushBuildOutput() in C:\XSharp\DevPublic\VisualStudio\ProjectBase\IDEBuildLogger.cs:line 383
at Microsoft.VisualStudio.Project.IDEBuildLogger.BuildFinishedHandler(Object sender, BuildFinishedEventArgs buildEvent) in C:\XSharp\DevPublic\VisualStudio\ProjectBase\IDEBuildLogger.cs:line 198
at XSharp.Project.XSharpIDEBuildLogger.BuildFinishedHandler(Object sender, BuildFinishedEventArgs buildEvent) in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\XSharpIDEBuildLogger.cs:line 89
2022-10-07 20:39:35.420 +01:00 [DBG] 0001 SetBuildConfigurationProperties Debug|Any CPU

**Comment by RobertvanderHulst** [comment] 2022-10-08 12:20
Fergus,
Thanks for pointing this out. I will have a look if I can prevent this exception.

**Comment by fxxm** [comment] 2022-10-08 12:28
My attempt to fix it does make the error go away but presumably it would rebreak this (#1114) for Arne
private void ReportQueuedOutput()
        {
            // NOTE: This may run on a background thread!
            ThreadHelper.JoinableTaskFactory.Run(async delegate
            {
                await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
                FlushBuildOutput();
            });
        }

**Comment by RobertvanderHulst** [comment] 2022-10-24 14:18
Fergus,
Our code calls OutputStringThreadSafe(). you would expect that VS takes care of thread switching in that case.
Apparently it does not.
I will remove the VS2022 specific code that uses the new method OutputStringThreadSafe()

**Comment by fxxm** [comment] 2022-10-24 14:52
> Fergus, Our code calls OutputStringThreadSafe(). you would expect that VS takes care of thread switching in that case. Apparently it does not. I will remove the VS2022 specific code that uses the new method OutputStringThreadSafe()

Yeah, looks like it *might* just be doing simple locking

![image](https://user-images.githubusercontent.com/38910169/197555446-ef6f88af-0de4-4f06-9c35-80b8297d8f09.png)

**Comment by RobertvanderHulst** [comment] 2022-11-16 13:37
This was fixed by switching to IVsOutputWindowPaneNoPump.OutputStringNoPump() whenever possible.

**Closed** 2022-11-17 16:04 UTC
Labels: vs projectsystem, MsBuild
