### ISSUE TITLE
The VODBInfo function does not return a result like VO

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#886] opened 2021-12-10 10:08 UTC
In VO, the VODBInfo function returns TRUE or FALSE depending on whether the requested information is supported by the driver. For example, the DBFCDX driver:

**VO**
```
LOCAL uValue AS USUAL
uValue := NIL
? VODBInfo(DBI_FULLPATH, @uValue) // returns TRUE, file path in uValue
uValue := NIL
? VODBInfo(DBI_USER + 100, @uValue) // returns FALSE, not supported (or unknown)
```

In this way, you can determine if a driver supports a particular functionality.

In X#, the VODBInfo function always returns TRUE, except for an invalid work area. Thus, if the RDD does not support a particular functionality, then calling the VODBInfo function in X# does not return FALSE and, alternatively, does not throw a NotSupportedException.

**X#**
```
LOCAL uValue AS USUAL
uValue := NIL
? VODBInfo(DBI_FULLPATH, REF uValue) // returns TRUE, file path in uValue
uValue := NIL
? VODBInfo(DBI_USER + 100, REF uValue) // returns TRUE, despite the fact that RDD doesn't know anything about the parameter DBI_USER + 100
```

**Comment by leon-ts** [comment] 2021-12-10 11:48
**Important addition:**
If VODBinfo returns FALSE, VO also populates the ERRINFO structure with the cause of the error. In my example, this structure is filled with error code 30 (Operation not supported) and error subcode 1153 (Operation not supported by current RDD).

**Comment by RobertvanderHulst** [comment] 2021-12-10 14:03
This now returns false and generates an error in the RuntimeState:LastRddError:

```
Description :	Operation not supported
Subsystem :	DBFNTX
GenCode :	EG_UNSUPPORTED Operation not supported
SubCode :	1153 Operation not supported by current RDD
FuncSym :	Info
Severity :	ES_ERROR
Can Default :	True
Can Retry :	False
Can Substitute :	False
Argument Number :	1
Argument :	nOrdinal
Arguments :	{1100,(NULL)}
Stack Trace :	
 WORKAREA:INFO (Line: 1114)
 DBF:INFO (Line: 2019)
 DBFDBT:INFO (Line: 86)
 COREDB:DO (Line: 234)
 COREDB:INFO (Line: 1070)
 VODB:INFO (Line: 58)
 VODBINFO (Line: 244)
 START (Line: 10)
```

Please note that (when the VO Error format is selected for the StackTrace) that I am now also suppressing lines from lambda expressions that you can recognize by the "<>" characters,
In .Net stack trace mode (that you can enable with `SetErrorStackVOFormat(FALSE)` )  the stack trace looks like this:

```
Stack Trace :	
   at XSharp.RDD.Workarea.Info(Int32 nOrdinal, Object oNewValue) in C:\XSharp\DevRt\Runtime\XSharp.Core\RDD\Workarea.prg:line 1114
   at XSharp.RDD.DBF.Info(Int32 nOrdinal, Object oNewValue) in C:\XSharp\DevRt\Runtime\XSharp.Rdd\Dbf\DBF.prg:line 2019
   at XSharp.RDD.DBFDBT.Info(Int32 nOrdinal, Object oNewValue) in C:\XSharp\DevRt\Runtime\XSharp.Rdd\DbfDbt\DbfDbt.prg:line 86
   at XSharp.CoreDb.<>c__DisplayClass61_0.<Info>b__0() in C:\XSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 1079
   at XSharp.CoreDb.Do[T](Func`1 action) in C:\XSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 234
   at XSharp.CoreDb.Info(UInt32 nOrdinal, Object& oValue) in C:\XSharp\DevRt\Runtime\XSharp.Core\RDD\CoreDb.prg:line 1070
   at XSharp.VoDb.Info(UInt32 nOrdinal, __Usual& oValue) in C:\XSharp\DevRt\Runtime\XSharp.RT\RDD\Vodb.prg:line 58
   at XSharp.RT.Functions.VoDbInfo(UInt32 kInfoType, __Usual& ptrRetVal) in C:\XSharp\DevRt\Runtime\XSharp.RT\RDD\VoDbFunctions.prg:line 244
   at ConsoleApplication2.Exe.Functions.Start() in C:\XSharp\DevRt\Tests\General\Program.prg:line 10

```

**Comment by cpyrgas** [comment] 2021-12-10 18:19
Confirmed fixed. There's still a difference, in VO after VODBInfo(DBI_USER + 100, @uValue), uValue contains NIL, while in X# contains NULL_OBJECT, but I think that's not really a problem. Or is it?

To be precise,
? AsString(uValue)

prints
VO: NIL
X#: {(0x0000)0x00000000} CLASS

**Comment by RobertvanderHulst** [comment] 2021-12-10 18:32
Chris,
That is one of the disadvantages of having a Core runtime without USUAL type.
I have changed the return value from Workarea.Info now to DBNull.Value. This gets converted to NIL in the Usual constructor.
There may be other places in the runtime where this is a good idea too.

**Comment by cpyrgas** [comment] 2021-12-10 18:37
Ah, no, there are side effects. For example any use of DBLocate() :

DbUseArea(,,"C:\dbf\test.dbf")
DbLocate({||1==1} ) 

results to an exception now. The reason is this code that is called from DBLocate()

FUNCTION __DbPushOptimize(lNoOpt AS USUAL) AS LOGIC
    IF ! lNoOpt:IsNil
        LOCAL lNoOptimize := lNoOpt AS LOGIC
        RETURN DbInfo(DBI_OPTIMIZE, !lNoOptimize)
    ENDIF
    RETURN DbInfo(DBI_OPTIMIZE)

Wondering why this throws an exception dialog now, the change should not had caused that I would think....

```
Description :	Operation not supported
Subsystem :	DBFNTX
GenCode :	EG_UNSUPPORTED Operation not supported
SubCode :	1153 Operation not supported by current RDD
FuncSym :	DbInfo
Severity :	ES_ERROR
Can Default :	True
Can Retry :	False
Can Substitute :	False
Argument Number :	1
Argument :	nOrdinal
Arguments :	{61,(NULL)}
Stack Trace :	
 DBF:INFO (Line: 0)
 DBFDBT:INFO (Line: 0)
 COREDB:DO (Line: 0)
 COREDB:INFO (Line: 0)
 VODB:INFO (Line: 0)
 DBINFO (Line: 0)
 __DBPUSHOPTIMIZE (Line: 0)
 DBLOCATE (Line: 0)
 START (Line: 3)


```

**Comment by cpyrgas** [comment] 2021-12-10 21:21
The issue with NIL/NULL is indeed fixed now

**Comment by cpyrgas** [comment] 2021-12-10 22:22
The optimize thing is fixed, but there's another issue which I am not sure if it's due to this one, or due to https://github.com/X-Sharp/XSharpPublic/issues/585

Taken from C795:

in VFP dialect only:

```
FUNCTION Start() AS VOID
LOCAL cFileName AS STRING
cFileName := "testvfp"
DbCreate(cFileName , {{"FLD","N",5,0}})
DbUseArea(,,cFileName)
DbAppend()
DbAppend()
DbGoTop()

DbEval({|| EvalFunc( RecNo())} )

FUNCTION EvalFunc(n AS DWORD) AS VOID
? n

```

this results to a dialog:


```

---------------------------
ERROR
---------------------------
Description :	Unknown Error occurred

Subsystem :	BASE

GenCode :	EG_EXCEPTION Exception raised by CLR or external code

FuncSym :	DbEval

Severity :	ES_ERROR

Can Default :	False

Can Retry :	False

Can Substitute :	False

Stack Trace :	

   at XSharp.RT.Functions._DbThrowErrorOnFailure(String funcName, Boolean resultToCheck)

   at XSharp.RT.Functions.DbEval(__Usual[] Xs$Args)

   at fox.Exe.Functions.Start() in C:\VIDE\Projects\Project3\Applications\fox\Prg\fox.prg:line 13




---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by RobertvanderHulst** [comment] 2021-12-11 18:24
Chris,
The reason why this fails is because the EvalFunc is VOID. This gets translated to NIL and in FoxPro the NIL has a value of FALSE. And that FALSE aborts the loop and also triggers the exception (which it should not).
If you change the EvalFunc to return TRUE then the program runs as expected.
I'll see what I can do about this (so I can detect that in this case NIL  <> FALSE, so the loop will not be aborted.
And even when the function DOES return a FALSE then the loop should be aborted, but no exception should be thrown.

**Closed** 2021-12-29 17:47 UTC
Labels: enhancement, Runtime, RDD

**Comment by cpyrgas** [comment] 2022-01-06 18:55
Confirmed fixed
