### ISSUE TITLE
Displaying information from XML documentation does not always work.

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#434] opened 2020-07-08 07:07 UTC
1. The attachment is a small project where the first problem is demonstrated. The ClassLibrary1.dll library, which has the ClassLibrary1.xml documentation, is attached to the ConsoleApplication1 project. The library has three methods, each of which is documented. When you enter a call to methods of the class Class1, the text of the documentation is not displayed for the DoSomething1 method. For other methods (DoSomething2 and DoSomething3) the documentation is displayed.
[ConsoleApplication1.zip](https://github.com/X-Sharp/XSharpPublic/files/4889009/ConsoleApplication1.zip)

2. A similar problem also appears for the system libraries that ship with XSharp. For example, the documentation for XSharp.CoreDb.FieldGet and some others is not displayed.

3. The prompts do not display the **'remarks'** section (I don’t remember whether they should be displayed).

4. Perhaps there is an error in the file XSharp.RT.XML in the description of the XSharp.RT.Functions.VoDbGetScope function, which is why the description is not displayed for it.

**Comment by RobertvanderHulst** [comment] 2020-07-08 14:17
Leonid,
1) I can't reproduce this. Your example code has a file reference to ClassLibrary1.dll. Did you have a file reference on your side as well, or did you have a project reference and is the problem caused by the fact that we are not picking up changes in the XML if you regenerate the other project ?
2) There is a problem with methods with "byRef" parameters. The type definition is for example `System.Object&` but in the XML file this is stored as System.Object@ because the ampersand is not allowed inside an XML file. I have fixed this.
3) This should be shown. I see it here. Maybe the same problem as 1) ?
4) This works here. Are you sure you had the XSharp.RT assembly included in the references list.

**Comment by leon-ts** [comment] 2020-07-08 14:44
Robert,

1. The ClassLibrary1.dll library is included in the ConsoleApplication1 project and is in the archive I attached. It is located in the folder: ConsoleApplication1\lib\ClassLibrary1\ClassLibrary1.dll. The ConsoleApplication1 project has a link to this DLL in the References section. Thus, I transferred a completely autonomous solution archive (VS2019), on which the problem can be reproduced.

2. Thanks!

3. When you hover over the method name, the description from the '**remarks**' section is displayed. But in the prompt when entering the method name and opening the bracket for entering parameters, the '**remarks**' section is not displayed. But to be honest, I don’t remember if it should be displayed in this case.

4. The assembly of XSharp.RT is included in the project. A description for many other functions from this assembly is displayed. I pointed out a possible error in XML, because I saw that the tag ending '**summary**' is in the wrong position and the tags '**returns**' and '**remarks**' are also included in it (see screenshot). 
![tag](https://user-images.githubusercontent.com/64518775/86932229-c166db80-c141-11ea-81c7-844c41e4f03c.png)

**Comment by RobertvanderHulst** [comment] 2020-07-08 15:04
1) I noticed that and it works with this on my machine. I am not sure why it does not work on your machine.
2) Ok
3) C# does not show remarks at all ! In fact the reference assemblies folder does not include <remarks> in any of its XML files. We support <remarks> for code parsed inside the editor. I understand why this is not included: the text in the remarks section may get quite long !

4) This is clearly a typo in the documentation source. Will be fixed in next build.

**Comment by leon-ts** [comment] 2020-07-08 15:41
Robert,

1. I don’t know if this information will help, but I noticed that this problem seems to occur with the first methods in the class. I have a real project where I first encountered this problem, and there the description was not displayed for the first method in the class either. Additionally, I attach a short video where I demonstrate this problem on the test project that I previously attached to this ticket. 
[ScreenRecorderProject1.zip](https://github.com/X-Sharp/XSharpPublic/files/4891693/ScreenRecorderProject1.zip)

**Comment by RobertvanderHulst** [comment] 2020-07-13 12:32
Ok, I found it. VS 2019 behaves differently from earlier versions of VS. It returns an "ID" of 0 for the first item in the XML file. Earlier versions were always returning IDs > 0.  And we had a check to see if the ID was > 0....

**Comment by leon-ts** [comment] 2020-07-16 06:34
Robert,
The problem partially remained. The method description is now displayed, but the current input parameter is not displayed.
See screenshot:
![no_params](https://user-images.githubusercontent.com/64518775/87635248-66d40d80-c747-11ea-8dc4-e3f316a1409d.png)

**Comment by RobertvanderHulst** [comment] 2020-07-16 07:01
Same problem, different location....

- Copy the attached files to c:\Program Files (x86)\XSharp\Extension\Project
- Run the deploy<n>.cmd files inside c:\Program Files (x86)\XSharp\Uninst as admin
This should fix it.

[XSharpProject.zip](https://github.com/X-Sharp/XSharpPublic/files/4929814/XSharpProject.zip)

**Comment by leon-ts** [comment] 2020-07-16 07:11
Robert,
The parameters are now displayed.
Many thanks!

**Closed** 2020-07-16 07:40 UTC
Labels: bug, vs editor
