### ISSUE TITLE
Add StackAlloc

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1084] opened 2022-07-31 09:09 UTC
like in C#

**Comment by RobertvanderHulst** [comment] 2023-01-05 14:13
I have implemented StackAlloc with 2 different syntaxes:
```
StackAlloc<T>(<nNumElements>)
StackAlloc(<nNumElements>)

```
The first expression allocates elements of the specified type.
The second variant assumes that T is Byte

When running in an unsafe environment, then the return value of StackAlloc is a pointer. (`T PTR`)
When NOT running in a safe environment then the compiler assumes a return value of `Span<T>` . This will only work for .Net Core and later.

**Comment by cpyrgas** [comment] 2023-01-06 23:33
Looks good! Although c# requires an unsafe context (for .Net 4), while X# doesn't at the moment.

**Comment by cpyrgas** [comment] 2023-01-09 07:48
I was looking into this as well, problem is that Span is only available in .Net >= 5. I'm sure it will be supported for those versions.

**Comment by leon-ts** [comment] 2023-01-09 07:52
Hi Chris,
I meant the array initialization syntax, which can also be used to pass as a parameter (as in the example in the IndexOfAny method).

**Comment by cpyrgas** [comment] 2023-01-09 08:06
Hi Leonid,
Oh, that's already supported in X#! It just uses a slightly different syntax (remnant from the Vulcan.NET days):

```
FUNCTION Start() AS VOID
LOCAL aArray AS INT[]
aArray := <INT>{1,2,3,4,5}
? aArray[2]
```

It just doesn\t work well with multi-dim arrays, I thought we had a ticket about this, but can't find it right now..

**Comment by leon-ts** [comment] 2023-01-09 08:12
Chris,
I know about this syntax and even actively use it in X # (where I use native .NET arrays). I meant in combination with the expression (operator) stackalloc:
`stackalloc[] { 2, 4, 6, 8 }`

**Comment by cpyrgas** [comment] 2023-01-09 08:15
Leonid, ah OK, in that case the docs say that the result of stackalloc can only be assigned to a Span or ReadOnlySpan (or a pointer), but those types are only available in .Net version >=5

**Comment by leon-ts** [comment] 2023-01-09 08:18
Will .NET 5 be available to us in X# 3?

**Comment by cpyrgas** [comment] 2023-01-09 08:27
Yes! Just not absolutely sure if the VOSDK classes will work well with it, but that's to be seen (and get worked on).

**Comment by RobertvanderHulst** [comment] 2023-01-09 09:15
Leonid,
> Chris, I know about this syntax and even actively use it in X# (in places of code where I use native .NET arrays). I meant in combination with the expression (operator) **stackalloc**: `stackalloc[] { 2, 4, 6, 8 }`
At this moment we are only parsing 

```
stackalloc(n)
stackalloc<T>(n)
```
So `stackalloc` is parsed as a pseudo function call (like PCount() and _GetInst()), so we do not need to add a `stackalloc` keyword.
The initializer syntax will require some extra work on the parser.

**Comment by cpyrgas** [comment] 2023-01-09 09:33
Robert,

It's highly unlikely that STACKALLOC is used by anyone as an identifier (and I don't think there's such a named function, either), so maybe it's better to use the keyword syntax also in X#, so it will also be closer to that of c#? In c# it's more verbose so more descriptive of what the code is doing, it's one of the rare cases where I like what they have done :)

**Comment by RobertvanderHulst** [comment] 2023-01-09 16:32
I have modeled the current implementation on what Don had done with _LocalAlloc() and I added the generic parameter to specify the size of the elements that are allocated. But since this is new we can also decide to change it.
So I can also add `STACKALLOC `as a keyword 

```
LOCAL aArray AS INT[]
aArray := STACKALLOC <INT>{1,2,3,4,5}
```
and
```
aArray := STACKALLOC INT[]{length}
```
Would you guys prefer that ?
Of course, in that case I will make Stackalloc "positional" by adding it to the list of keywords that can be used as identifier

**Comment by leon-ts** [comment] 2023-01-09 16:38
> ... So I can also add `STACKALLOC `as a keyword
> 
> ```
> LOCAL aArray AS INT[]
> aArray := STACKALLOC <INT>{1,2,3,4,5}
> ```
> 
> and
> 
> ```
> aArray := STACKALLOC INT[]{length}
> ```
> 
> Would you guys prefer that ?

Great!
Personally, I like it!

**Comment by cpyrgas** [comment] 2023-01-09 23:50
Yeah, I also agree!

**Comment by RobertvanderHulst** [comment] 2023-01-16 16:04
I have implemented this now.
From my sample code:

```
VAR x := STACKALLOC <dword>{1,2,3,4,5,6,7,8,9,10}`
```
You can also omit the type. The compiler will then infer the types from the initializer.
```
VAR x := STACKALLOC {1,2,3,4,5,6,7,8,9,10} // this will be an array of signed integers (System.Int32)
```
You can also declare an array with a size that is not initialized:
```
VAR y := STACKALLOC dword[]{10}
```
and an incorrect expression, such as 

`VAR z := STACKALLOC 10`

produces an error:

` error XS9212: The STACKALLOC keyword needs to be followed by a literal array or an array creation expression.`

However STACKALLOC is a positional keyword, so this still works:

`local STACKALLOC := "sometext" as string`

**Comment by cpyrgas** [comment] 2023-01-19 09:24
Robert, this works fine, 

`VAR x := STACKALLOC <dword>{1,2,3,4,5,6,7,8,9,10}`

but this reports error XS0518: Predefined type 'System.Span`1' is not defined or imported, is this to be expected? 

```
LOCAL x AS DWORD[]
x := STACKALLOC <DWORD>{1,2,3,4,5,6,7,8,9,10}
? x[3]
```

**Comment by RobertvanderHulst** [comment] 2023-01-19 10:06
Chris, strictly speaking, the return value of the STACKALLOC is a DWORD PTR in this case. But even when you change the declaration of x then it still reports the error. I'll look into this.

**Comment by RobertvanderHulst** [comment] 2023-01-24 11:04
Roslyn insists that this will only work with an inline assignment in the declaration.
So this works:
`LOCAL x := STACKALLOC <DWORD>{1,2,3,4,5,6,7,8,9,10} AS DWORD PTR`
or
`VAR x := STACKALLOC <DWORD>{1,2,3,4,5,6,7,8,9,10}`
or
`LOCAL x := STACKALLOC DWORD[]{10} AS DWORD PTR`
or
`VAR x := STACKALLOC DWORD[]{10}`

Maybe I can 'cheat' and silently convert

`LOCAL x := STACKALLOC DWORD[]{10} AS DWORD[]`
to
`LOCAL x := STACKALLOC DWORD[]{10} AS DWORD PTR`
but I am not sure if that is a good idea.

In C# this only works in an unsafe context. We are silently adding the 'unsafe' modifier to the code for this.

**Comment by cpyrgas** [comment] 2023-01-24 11:13
Ah, OK, if the inline syntax works, then it's fine. I thought that the LOCAL syntax is not supported at all.

But maybe a better error message should be reported when trying to divide the expression in two expressions, because the "error XS0518: Predefined type 'System.Span`1' is not defined or imported" is not really helpful. But it's not very important.

**Comment by cpyrgas** [comment] 2023-02-02 09:09
Confirmed done

**Closed by cpyrgas** 2023-02-02 09:09 UTC
Labels: enhancement, Compiler
