### ISSUE TITLE
Comments in the file are confusing the compiler when indicating an error

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#609] opened 2021-04-23 12:59 UTC
When compiling this code, the compiler error does not indicates the line where the error is, but the line below.
`// Application : ____TestLib
// TestMod.prg , Created : 23.04.2021   14:51
// User : Wolfgang

begin namespace xxx

//  <country-code>AT</country-code>
//  <zipcode>7000</zipcode>

// 	<place>Eisenstadt</place>
// 	<state>Burgenland</state>
//	<state-code>01</state-code>
//	<province>Eisenstadt Stadt</province>
//	<province-code>101</province-code>
//	<community>Eisenstadt</community>
//	<community-code>10101</community-code>
//	<latitude>47.8457</latitude>
//	<longitude>16.5233</longitude>

function Hallo() as string
	local cHallo			as string

	cHallo			:= 'e'

	return cHallo

end namespace`

**Comment by wriedmann** [comment] 2021-04-23 13:01
Unfortunatly Github strips out the XML tags in the code
[TestMod.zip](https://github.com/X-Sharp/XSharpPublic/files/6365454/TestMod.zip)

**Comment by RobertvanderHulst** [comment] 2021-06-23 15:28
I cannot reproduce this with the current build...

**Comment by cpyrgas** [comment] 2021-06-23 15:50
Same here. When compiling in code, an error is reported about assigning the char value, but the correct error line is reported.

**Comment by RobertvanderHulst** [comment] 2021-09-06 11:24
I am closing this (for now) because the issue is not reproducible over here

**Closed by RobertvanderHulst** 2021-09-06 11:24 UTC
Labels: bug, Compiler

**Comment by cpyrgas** [comment] 2021-09-06 15:35
Same here.
