### ISSUE TITLE
Error XS9002 Parser: mismatched input '+' expecting EOS

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#171] opened 2019-09-09 08:59 UTC
In a project with FoxPro dialect, I am getting this error:
 **Error XS9002 Parser: mismatched input '+' expecting EOS**

For this line of code:

`	? lcFirstName + " " + lcLastName`

**Comment by RobertvanderHulst** [comment] 2019-09-09 09:05
Matt,
Is this the only source in the file ?

**Comment by mattslay** [comment] 2019-09-09 09:20
Here's the entire code:


Using System
Using System.Collections.Generic
Using System.ComponentModel
Using System.Data
Using System.Drawing
Using System.Text
Using System.Windows.Forms



Begin Namespace MyApp.vfp_classlib_sample_2.vcx
	
	Public Partial Class fieldcontainer ;
			 Inherit _vxBaseClasses._vxContainerBase
		
		// This is a sample custom integer property added to this class.
		Public Property nCustomerProperty1 As Int Auto
		// XML Metadata for customizable properties
		Public Property _memberdata As Usual Auto
		// This is a sample custom String property added to this class.
		Public Property cCustomStringProperty1 As String Auto
		// This is another sample custom String property added to this class.
		Public Property cCustomStringProperty2 As String Auto
		// This is a Hidden Property.
		Hidden Property HiddenProperty As Int Auto
		// This is a Protected Property.
		Protected Property ProtectedProperty As Int Auto
		
		Public Constructor() Strict 
			InitializeComponent()
			Return
			
Method CustomerWorkerMethod()
Local lcFirstName, lcLastName, lcMessage As String
Local lnX
Local MyArray[1]
Dimension myArray[3,2]
myArray[1,1] := "Matt"
myArray[1,2] := "Slay"
myArray[2,1] := "Jimm"
myArray[2,2] := "Smith"
myArray[3,1] := "Nancy"
myArray[3,2] := "Adams"
For lnX := 1 To Alen(myArray, 1)
	lcFirstName := myArray[lnX, 1] 
	lcLastName := myArray[lnX, 2]
	? lcFirstName + " " + lcLastName
Next
		
lcMessage := "Hello from custom method."
MessageBox(lcMessage)
 
Return .T.

Method HiddenMethod()
Local lcMessage
lcMessage := "This is a HIDDEN method on a Class."
MessageBox(lcMessage)
Return .T.

Method ProtectedMethod()
Local lcMessage
lcMessage := "This is a PROTECTED method on a Class."
MessageBox(lcMessage)
Return .T.


			




	End Class

End Namespace

**Comment by JohanNel** [comment] 2019-09-09 10:03
Hi Matt,

There is a fundamental difference between how Fox and VO/X# handles Usual Arrays,  In X# arrays are not fixed dimensions, they are ragged, similar to .NET STRING[][].

For the above to work ALen(myArray) will return 3.
Alen(myArray[nX]) will return the length of the subarray which will be 2 in your example.

Hope this explains the difference.

Johan

**Comment by mattslay** [comment] 2019-09-09 11:52
Johan - thanks, and I do understand what you have shown me. However, the result imported was from me trying to run existing VFP. 

I hope they can handle this code as-is, so that people don’t get compiler errors when they open their PRGs in X# and choose the FoxPro dialect. 

If they have to do a lot of editing on their code, their could be hundreds of this code type in a FoxPro project, and no one wants to touch that mush of their code for fear of making a mistake, or the shear burden of the task.

**Comment by RobertvanderHulst** [comment] 2019-09-09 12:24
Matt, Johan,

It is our intention to make X# so compatible that existing code like this runs without changes.
So we will add a runtime function ALen() with 2 parameters just like in FoxPro.
Unfortunately we're not there yet.

At this moment we're in the middle of getting the VFP class syntax to work.
Then we'll need to look at some other issues like supporting the Dimension statement in the compiler that you have used in your code.
And we'll have to write the UDCs to map the various commands to existing runtime functions
After that we'll look into the missing runtime functions or runtime functions with a different behavior.

Robert

PS I am not sure what you are trying to achieve with

```
Local MyArray[1]
Dimension myArray[3,2]

```
Why declare an array with 1 element if you are changing it in the next line to 3 by 2 ?

**Comment by mattslay** [comment] 2019-09-09 14:37
```
Local MyArray[1]
Dimension myArray[3,2]
```

Robert - Indeed, this may look like an odd thing to do, but it is also valid code, and I'd say not all that uncommon to see in VFP code...  One declares an array with `Local aBlah[1]` at top of code, then later in code re-dimensions the array as needed based on who-knows-what kind of requirements.


Example:

```
Local MyArray[1]
Dimension myArray[3,2]

myArray[1,1] = "Test1"
myArray[3,2] = "Test2"

?myArray[1] && Prints "Test1"
?myArray[1,1] && Prints "Test1"

?myArray[3,2]&& Prints "Test2"

```

**Comment by JohanNel** [comment] 2019-09-10 02:53
Hi Robert,

Just maybe if you have not seen it before.  Through reading some VFP documentation regarding arrays, it seems that VFP is always storing internally multi-dimensional arrays in a flat single dimensional array.  Hence why myArray[1] gives "Test1" and not '{"Test1", NIL}'.  Similarly myArray[6] gives "Test2", while VO/Vulcan/X# will produce out of bounds error.

Johan

**Comment by RobertvanderHulst** [comment] 2019-09-10 04:45
Johan,
It will be difficult to implement this without breaking other code that depends on the fact that myArray[1] returns an array.
I'll see what I can do, but this is most likely going to be impossible.
The only solution that I can think of is to map `Dimension myArray[3,2]` to `Dimension myArray[3*2]`
and always allocate a single dimensional array in the FoxPro dialect.

**Comment by JohanNel** [comment] 2019-09-10 04:54
Hi Robert,
> and always allocate a single dimensional array in the FoxPro dialect.
I was also thinking that VFP dialect might have to have separate implementation of ARRAY, I am just not sure if anybody in the VFP community actually use the "flat" approach to access elements.  I will ask this in the VFP forums and monitor responses...
Johan

**Comment by RobertvanderHulst** [comment] 2019-09-10 08:09
Johan,
I think we can solve this in the runtime. The runtime "knows" the current dialect, and I can  probably detect that the running app is FoxPro and in stead of creating a real 2 dimensional array I can create a single dimensional array and remember the row and column count. When accessing the array with a single index I can simply return that row and when accessing the array with a double index then I can return the element calculated from the row and column position and use the defined rowcount to calculate the right position.
So an array declared as [3,2] will have 3 rows and 2 columns. This will then be allocated as a single dimensional 6 element array. When retrieving element [3,1] I will calculare (3 -1 * colCount) + 1 = element 5 (1 based).
We should probably create a special setting for this (SetFoxArrays()) which will be enabled in the startup code in the VFP Runtime DLL.

**Comment by JohanNel** [comment] 2019-09-10 08:25
Hi Robert,
Yes that should not be too difficult, but I would love to hear from VFP guys if they would not like to have nested/multi-dimensional arrays.  I see there is also a AELEMENT() function to return the single dimensional array position, etc.  Same goes for "RowCount" and "ColumnCount" retrieval.  My personal feel would be that maybe a bit of changes to VFP code can open up a lot more to the VFP community using VO/X# arrays.  Not sure if one can have both options available in the VFP syntax..?

**Comment by mattslay** [comment] 2019-09-10 10:00
> When accessing the array with a single index I can simply return that row and when accessing the array with a double index then I can return the element calculated from the row and column position and use the defined rowcount to calculate the right position.

**Robert**  I don't thinks this part is correct...

> When accessing the array with a single index I can simply return that row...


FoxPro never returns an entire row, it just returns a single element from the array, even when working with a 2-
![2019-09-10 04_53_48-](https://user-images.githubusercontent.com/309016/64604527-f2427c80-d387-11e9-94fd-0cd4b18478b0.png)
dimensional array.

See example code:

```
Clear

*  Array example
Local MyArray[1]
Dimension myArray[3,2]

myArray[1,1] = "One"
myArray[1,2] = "Two"

myArray[2,1] = "Three"
myArray[2,2] = "Four"

myArray[3,1] = "Five"
myArray[3,2] = "Six"

?myArray[1,1] && Prints "One"
?myArray[2,1] && Prints "Three"
?myArray[3,1] && Prints "Five"
?myArray[3,2] && Prints "Six"

? ""

?myArray[1] && Prints "One"
?myArray[2] && Prints "Two"
?myArray[3] && Prints "Three"
?myArray[4] && Prints "Four"
?myArray[5] && Prints "Five"
?myArray[6] && Prints "Six"
```

**Comment by RobertvanderHulst** [comment] 2019-09-10 10:13
Matt, this is exactly what I meant. I used the word 'row' where I should have used 'cell' or 'element'
XBase++ and VO return the row.
I personally think the FoxPro behavior is crazy, but I will implement it anyway.

**Comment by RobertvanderHulst** [comment] 2019-10-21 09:51
I am closing this issue, since the error is no longer reproducible. ALen() will be adjusted for VFP and a MessageBox() function will also be added

**Closed by RobertvanderHulst** 2019-10-21 09:51 UTC
Labels: FoxPro
