### ISSUE TITLE
Visibility of undeclared Private memvars

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#231] opened 2019-10-18 05:43 UTC
when you run the code unchanged, you should notice that the memvar "nVar" - undeclared created in the Test() - is visible in the Start(). When you declare the "nVar" the results are as expected.

```
// 1. <Foxpro> dialect
//
// 2. used compiler switches: 
//    -memvar+  -undeclared+  -VO8+
// 

#define __DECLARE_PRIVATE__ 0   // 1
	
FUNCTION Start() AS VOID 

    ? "Privatescount()" , MEMVAR.Privatescount()  //  0 , ok
    
 	x = Test() 
 	
    ? "Privatescount()" , MEMVAR.Privatescount()  // must always show 1 instead of 2
    
    ? 
    ? "x" , x  // true , ok

    // must always throw an "undeclared variable" error at runtime    
    ? "nVar" , nVar     
 	 
	RETURN	


FUNCTION test()
	 
#ifdef __DECLARE_PRIVATE__ 

 PRIVATE nVar = 12.45
 
#else	

 nVar = 12.45
 
#endif  
	
	RETURN .t.

```

**Comment by RobertvanderHulst** [comment] 2019-10-18 11:59
Confirmed, but a bit more difficult to implement without sacrificing performance. 
At this moment when the compiler detects a MEMVAR or PRIVATE statement in a method/function/procedure it marks that entity and when generating the Roslyn parse tree for that method we generate special entry and exit code to keep track of the privates created at that level.
when __DECLARE_PRIVATE_ is enabled the C# equivalent of the code inside test() looks like this:

```
        int nLevel = XSharp.RT.Functions.__MemVarInit();
	try
	{
		XSharp.RT.Functions.__MemVarDecl("nVar", _priv: true);
		XSharp.RT.Functions.__MemVarPut("nVar", 12.45);
		return true;
	}
	finally
	{
		XSharp.RT.Functions.__MemVarRelease(nLevel);
	}
```

Because we know that nVar is a memvar we will generate __MemVarPut() code.

Without the private keyword this is not done and then the compiler detects later (in the binder phase) that the identifier (nVar) cannot be found (so it is not a instance variable, global or something like that) and then when /undeclared is enabled we translate the assigment of nVar to 
```
    XSharp.RT.Functions.__VarPut("nVar", 12.45);
```
We don't know this yet at parse time, so the function test() is not marked as 'adds privates' and no special entry and exit code is generated.

I see 2 solutions:
- Every method / function / procedure will get __MemVarInit() and __MemVarRelease() calls when compiling with /undeclared (this should be relatively easy to implement, but will slow down the runtime speed)
- After the binding phase, the compiler goes through a 'Local rewriter phase'. We could mark the method in the binding phase with 'contains assignments to undeclared variables' and then later change the body of the method to add calls to __MemVarInit and __MemVarRelease(). This would of course still be useless code if the nVar existed as DBF field, in which case the assignment would update the DBF.
That is more difficult to implement, but has less runtime overhead. It would only be done for code that actually updates undeclared variables. And we could use the same mechanism for declared variables and would not have to generate the entry and exit code in the parser.

Robert

**Closed** 2019-11-05 16:45 UTC
Labels: Compiler, FoxPro, enhancement
