### ISSUE TITLE
Too many parser errors

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#164] opened 2019-09-04 01:03 UTC
In a lot of cases, one syntax error desyncs the parser causing to report way too many parser errors, making it very difficult to track the one which is important. In the following sample, 18 errors are reported due to one problem in the code. In long prg files, the amount  of such parser errors easily gets to thousands...This needs to be improved.

FUNCTION Start() AS VOID
	IF TRUE
		SOME PREPROCESSOR COMMAND	
	ENDIF
	? 
	? DbCloseArea()
	? DbCloseArea()
	? DbCloseArea()
	n := test() + test()
	n :=  DbCloseArea()
	? DbCloseArea()
	? DbCloseArea()
	? DbCloseArea()
	? DbCloseArea()
	? DbCloseArea()
	? DbCloseArea()
	? DbCloseArea()
	? DbCloseArea()
RETURN

xRntime.prg(3,8): error XS9002: Parser: unexpected input 'SOME PREPROCESSOR'
xRntime.prg(4,2): error XS9002: Parser: unexpected input 'ENDIF'
xRntime.prg(5,2): error XS9002: Parser: unexpected input '?'
xRntime.prg(6,2): error XS9002: Parser: unexpected input '?'
xRntime.prg(7,2): error XS9002: Parser: unexpected input '?'
xRntime.prg(8,2): error XS9002: Parser: unexpected input '?'
xRntime.prg(9,2): error XS9002: Parser: unexpected input 'n'
xRntime.prg(10,2): error XS9002: Parser: unexpected input 'n'
xRntime.prg(11,2): error XS9002: Parser: unexpected input '?'
xRntime.prg(12,2): error XS9002: Parser: unexpected input '?'
xRntime.prg(13,2): error XS9002: Parser: unexpected input '?'
xRntime.prg(14,2): error XS9002: Parser: unexpected input '?'
xRntime.prg(15,2): error XS9002: Parser: unexpected input '?'
xRntime.prg(16,2): error XS9002: Parser: unexpected input '?'
xRntime.prg(17,2): error XS9002: Parser: unexpected input '?'
xRntime.prg(18,2): error XS9002: Parser: unexpected input '?'
xRntime.prg(19,1): error XS9002: Parser: unexpected input 'RETURN'
xRntime.prg(2,9): error XS1003: Syntax error, 'END[IF]' expected

**Comment by nvkokkalis** [comment] 2019-09-25 07:56
I have tried a solution based on customizing the error strategy with success, but it's not generic. I will use this if I fail to find a more elegant one.

To explain the solution, in this particular case, the error occurs within the statementBlock rule. Knowing this, when an error occurs in that rule, we can skip all tokens until a token that is known to terminate the statementBlock is found (like the ENDIF), whereupon the parser is allowed to continue.

The default antlr4 error recovery fails to do this. I suppose this happens because our grammar is very complicated for the parser to track (e.g. depending on the rule, the statementBlock may terminate with different tokens, and it may need to backtrack the rule hierarchy to find them).

Any ideas on this?

**Comment by RobertvanderHulst** [comment] 2019-09-25 08:43
Nikos,
The first 2 error in the list are Ok, I think. 
Why do the other errors appear. Did Antlr abort the outer statement block as well and therefore the QoutStmt is no longer valid ? Does the error in line 4 at this moment abort the outer block ?
Can't you tell Antlr to just abort the innerblock (line 3) and accept that line 4 is unexpected input and then continue the outer block. 
If that is the case then we should at least detect the closing tokens and silently consume them so we can continue the outer block. I think the list of these end tokens is not too long:
END, ENDDO, ENDCASE, CASE, ELSEIF, ELSE, ENDIF, NEXT, RECOVER, FINALLY, CATCH, UNTIL

Of course we also have the entities themselves, that have a statement block and do not have a proper END marker (I have added these, but they are optional).
To include these would indeed be too much work, because then you would have a list that includes LBRKT(attributes), all modifiers, all entity keywords etc,

**Comment by nvkokkalis** [comment] 2019-09-25 09:56
Only the first error is valid, imo. The other errors appear because antlr aborts the IF/ENDIF block at the "SOME" token, then aborts the FUNCTION block at the 'ENDIF' token (because the IF block was already aborted), and then expects an entity and instead finds '?'.

To work correctly, it needs to consume all tokens until ENDIF at the first error. Then, the IF/ENDIF block will close correctly and the rest of the code will not produce errors.

**Comment by nvkokkalis** [comment] 2019-10-02 07:12
The main problem here is that the error happens at the `statementBlock` rule instead of the `statement` rule. This happens because the `statement` is optional (the `statementBlock` can consist of 0 or more statements). So, no more statements can be added to the block if a parser error occurs because the `(Stmts+=statement)*` clause is aborted at the first error.

Even worse, the antlr4 error strategry mechanism does not allow elegant handling of this case. It offers a `sync()` function, but it is called before the prediction that aborts the `statementBlock` rule, so the only way to handle the error early would be to invoke the prediction twice (which would be costly).

I will experiment with slightly altered rules to see if I can allow the error handling to work correctly.

**Comment by RobertvanderHulst** [comment] 2019-10-02 08:57
Nikos,
What happens if we change the statementBlock rule to match 1 or more statements and make the StmtBlock optional on the places where it is used ?

**Comment by nvkokkalis** [comment] 2019-10-03 06:21
The most elegant solution would be to provide the `statementBlock` with a fixture, e.g. remove `eos` as part of the statement and rewrite it as:

`statementBlock      : (Stmts+=statement (eos Stmts+=statement)*)?;`

This would allow `sync()` to look for either `eos` or the limited number of `entity` tokens as block terminators, which would make early error detection possible. However, this would be a major rewrite of the grammar, because it would mean handling `eos` outside the block rule (the missing `eos` at the end of the rule is not an oversight).

As it is, perhaps the dirty solution is preferrable, i.e. to add an `errorStmt` subrule to the statement to parse out anything that cannot come after a block and throw an error on it after the parsing is finished.

**Comment by RobertvanderHulst** [comment] 2019-10-03 07:16
I assume that would mean that a rule such as BEGIN SCOPE would then have to include an eos after the statementblock:
```
BEGIN Key=SCOPE end=eos
                      StmtBlk=statementBlock eos
(e=END SCOPE ? eos)?	
```
I see no problem with that, especially when it helps to improve error detection.
 
At this moment I have made most (all?) of the END markers for blocks optional. I did that because I was using the parser to also parse source in the source code editor. We are not using the parser for that anymore.
Would it help if we make the END clauses, such as the END SCOPE above mandatory again. Would that make error reporting better ? 

Btw I have changed eos to EOS for several (all ?) entity rules and added eos to the entity rules. 
This made it easier to link source code comments to the entities that they belong to. With an eos rule at the end of an entity the comments would logically belong to the previous entity.
Does this make the parsing more complicated ?

**Comment by nvkokkalis** [comment] 2019-10-03 17:19
Such a modification would not be sufficient alone, but would allow the sync() method of the error strategy to handle the error. However, I think it's too intrusive so I opted for another solution (not as clean, but simpler). In fact, I tried it over v2040 tag and it worked so I pushed it, but I see it's broken now. Will check again.

**Comment by nvkokkalis** [comment] 2019-10-03 19:34
The fix works on v2060 but not on v2070. It no longer works because the error is now thrown at the `entity` rules instead of the `statementBlock`, likely due to recent changes to the parser. The antlr4 predictor plays it smart and never enters the `funcproc` rule because of the error, believing it might find an alternative - which it doesn't. Unfortunately, we cannot do any meaningful error handling if the right entity rule is never chosen. It seems that the grammar is becoming increasingly ambiguous...

**Comment by RobertvanderHulst** [comment] 2019-10-03 19:42
I merged the function and procedure rules because there was a lot of common functionality in them and I thought it would make sense to do so (to reduce duplicate code).
If this makes the parser too complex I can split the rules again.
I also changed the method rule, so it now also allows the FUNCTION and PROCEDURE keywords, since inside VFP classes methods are called FUNCTION or PROCEDURE.

In my latest code I have also removed most of the predicates in the parser (in the hope that would bring back some speed) and much of the error handling out of the Transform classes , and moved the detection of 'unacceptable' code to the ParserErrorAnalysis Listener. That way we can focus on tree building inside the Transform classes.

Anyway, as you see in this problem, I can really use your help in the compiler....

**Comment by nvkokkalis** [comment] 2019-10-03 19:54
I'm not sure it's the merging of the rules that caused this behavior. I'll try to work it out, but the ambiguity of the grammar is not making it easy. I'm more concerned that there may be some other case where the `statementBlock` rule behaves differently...

**Comment by RobertvanderHulst** [comment] 2019-10-03 20:03
If you have suggestion how things can be done better, I'd really like to hear them.
What do you think of removing the predicates, and moving error checking to the separate ParserErrorAnalysis listener? 

And I have also simplified the parser by preprocessing out 'garbage' (such as NEXT i) in the preprocessor. That should make the parser simpler.  Do you think it would make sense to make the END IF, NEXT, ENDCASE etc tokens mandatory again, now that I am no longer using the parser inside the editor ?

**Comment by nvkokkalis** [comment] 2019-10-03 20:48
In this case the ambiguity was caused because `FUNCTION` and `PROCEDURE` were added to the `methodtype` rule. This made the predictor unable to determine which rule to visit early on, so the error was thrown at the parent `entity` rule. Predicating it with `IsFox?` does not help either, as the prediction phase ignores prediactes.

We either need a different approach to the grammar to minimize ambiguity as much as possible, or we must live with such errors,..

**Comment by RobertvanderHulst** [comment] 2019-10-04 05:12
Ok, I see what the problem is is. We probably need several method rules to help the parser. One for methods outside a class (lets call this vomethod), one for our current class members and one for foxpro class members. vomethods  can only start (after attributes and modifiers) with METHOD/ACCESS/ASSIGN. That way at the entity level there is no confusion. 
We can probably reduce some duplicate code by defining a rule that holds common info, lets call this **header** for now. This always holds the name (Id) and optionally holds the other info such as parameters type parameters etc.
```
header : Id=identifier                             
          TypeParameters=typeparameters?                            
          (ParamList=parameterList)?                                
          (AS Type=datatype)?                                       
          (ConstraintsClauses+=typeparameterconstraintsclause)*     
          (CallingConvention=callingconvention)?  
          ;
```
This would change the other rules to:

**funcproc** then becomes 
```
(Attributes=attributes)? (Modifiers=funcprocModifiers)?   
T=(FUNCTION|PROCEDURE) hdr=header
InitExit=(INIT1|INIT2|INIT3|EXIT)?                        
(EXPORT LOCAL)?                    
(DLLEXPORT STRING_CONST)? 
end=eos  
StmtBlk=statementBlock
(END T2=(FUNCTION|PROCEDURE)   EOS )?

```

**vomethod** then becomes
```
(Attributes=attributes)? (Modifiers=funcprocModifiers)?   
T=vomethodtype ExplicitIface=nameDot)? hdr=header
CLASS (Namespace=nameDot)? ClassId=identifier // note the Class clause is mandatory here !
(EXPORT LOCAL)?  
(DLLEXPORT STRING_CONST)?
end=eos
StmtBlk=statementBlock
(END T2=vomethodtype EOS)?

vomethodtype          : Token=(METHOD | ACCESS | ASSIGN )
                    ;


```

**method** (used inside classmembers) :
```
(Attributes=attributes)? (Modifiers=memberModifiers)?   
T=vomethodtype  ExplicitIface=nameDot)? hdr=header
(CLASS (Namespace=nameDot)? ClassId=identifier)?
(EXPORT LOCAL)?  
(DLLEXPORT STRING_CONST)?
end=eos
StmtBlk=statementBlock
(END T2=vomethodtype EOS)?
```

and **foxmethod** (used in foxclassmembers)

```
(Attributes=attributes)? (Modifiers=memberModifiers)?   
T=foxmethodtype  hdr=header
HelpString=HELPSTRING HelpText=expression)?          
(ThisAccess=THISACCESS LPAREN MemberId=identifier RPAREN)?    
end=eos
StmtBlk=statementBlock
(END T2=foxmethodtype  EOS)?

foxmethodtype          : Token=(FUNCTION| PROCEDURE  )
                    ;

```
We can probably also simplify things by combining (EXPORT LOCAL)?  and (DLLEXPORT STRING_CONST)? in one rule. Or we should simply remove these tokens, since we are not generating code for this anyway. Chris should be able to strip this out in his Xporter.

If we do something like this then we will have to change some code in the transform classes but I think it will make the parser less ambiguous.

**Comment by nvkokkalis** [comment] 2019-10-04 06:39
Yes, that would work. Alternatively, we could have only one super-rule for methods/functions and do some extra error checking in the tree transform phase (e.g. throw error for methods outside a class):

`(Attributes=attributes)? (Modifiers=funcprocModifiers)?   
T=(FUNCTION|PROCEDURE|METHOD|ACCESS|ASSIGN) hdr=header
InitExit=(INIT1|INIT2|INIT3|EXIT)?                        
(EXPORT LOCAL)? (DLLEXPORT STRING_CONST)? end=eos  
StmtBlk=statementBlock
(END T2=(FUNCTION|PROCEDURE|METHOD|ACCESS|ASSIGN) EOS)?`

Or we could have one rule for functions (outside a class) and one for methods (within a class, but common for core/vo/foxpro). Whatever you prefer.

Note that the optional `END` keywords also increase the ambiguity because the parser can abort the `statementBlock` rule on an error (since the closing kw is optional) and throw the error at the parent rule.

**Comment by RobertvanderHulst** [comment] 2019-10-04 06:59
Yes, that super rule would work too. Except that there are different modifiers now (funcprocmodifiers and memberModifiers) and the modifier STATIC for a function/procedure has a different meaning (visibility) than static for a METHOD. 
And I understand that the END keywords add to the ambiguity. For Foxpro they are needed (Foxpro has ENDPROC and ENDFUNC, but I am preprocessing these into END PROCEDURE and END FUNCTION). My idea was (for consistency) to add these to all classmembers.
Ok, one of us needs to do this. 
I suggest that I do this and you have a look at # 51

**Comment by RobertvanderHulst** [comment] 2019-10-04 18:01
I have rearrange the parser according to your advise. I named the new rule "signature" because that is what it is, a name, parameters, return type, generic parameters and constraints.
The erroneous line is now wrapped in a NopStmt(). If I insert lines before and after the erroneous line then these will be combined into one statementblock. This is s great improvement.

**Comment by nvkokkalis** [comment] 2019-10-07 06:21
That's great. Please inform me of any other cases that weird parser errors appear. Perhaps we need improvements in other rules as well.

**Closed** 2019-10-13 10:47 UTC
Labels: Compiler, enhancement
