### ISSUE TITLE
xBase++ preprocessor doesn't recognize parentheses in #xtranslate

### ISSUE THREAD

**Issue by kpa174** [X-Sharp/XSharpPublic#963] opened 2022-02-16 09:44 UTC
**Describe the bug**
#xtranslate expression with regular match marker and parentheses is not recognized by the preprocessor (xBase++ dialect).

**To Reproduce**
```
#xtranslate new <Exp>([<args,...>]) => <Exp>():new([<args>])
class Example
endclass
procedure main()
    local o := new Example(2)
return

```
**Expected behavior (xBase ppo)**
```
class Example
endclass
procedure main()
    local o := Example():new( 2)
return

```
**Actual behavior (x# ppo)**
```
class Example
endclass
procedure main()
    local o := new Example(2)
return
```

**Error message**
_error XS9002: Parser: unexpected input 'Example'_

**Additional context**
X# Compiler version 2.10.0.3 (public)

**Comment by RobertvanderHulst** [comment] 2022-02-16 19:57
The problem in this case is not the <Exp> Match marker but the fact that the open and close parentheses are not recognized as 'token'. If you change the udc to

`#xtranslate new <Exp> XX[<args,...>]YY => <Exp>():new([<args>])
`
and the test code to 

`local o := new Example XX 2 YY`

then it works.

**Comment by kpa174** [comment] 2022-02-17 06:07
Yes. Standart xBase UDCs also don't work:
```
#translate ISARRAY(<v>)      =>  ( VALTYPE(<v>)=="A" )
#translate ISBLOCK(<v>)      =>  ( VALTYPE(<v>)=="B" )
#translate ISCHARACTER(<v>)  =>  ( VALTYPE(<v>)=="C" )
#translate ISDATE(<v>)       =>  ( VALTYPE(<v>)=="D" )
#translate ISLOGICAL(<v>)    =>  ( VALTYPE(<v>)=="L" )
#translate ISNIL(<v>)        =>  ( (<v>)==NIL )
#translate ISNUMBER(<v>)     =>  ( VALTYPE(<v>)=="N" )
#translate ISMEMO(<v>)       =>  ( VALTYPE(<v>)=="M" )
#translate ISOBJECT(<v>)     =>  ( VALTYPE(<v>)=="O" )

```

**Comment by kpa174** [comment] 2022-02-17 08:40
> The problem in this case is not the Match marker but the fact that the open and close parentheses are not recognized as 'token'.

Thank you, Robert. Could you check if the next problem is the same?

**To Reproduce**
```
#xtranslate \{<b>..<e>\} => Range(<b>, <e>)
local o := {1..5}
```
**Expected behavior (xBase ppo)**
```
local o := Range(1, 5)
```
**Actual behavior (x# ppo)**
```
local o := {1..5}
```
**Error message**
_error XS9002: Parser: unexpected input '.5'_

**Comment by RobertvanderHulst** [comment] 2022-02-17 09:58
I suspect this is the same problem. The preprocessor does not recognize the dots (as well as the parentheses from the other example) correctly as "token".

**Comment by kpa174** [comment] 2022-02-18 05:47
Another one example:
```
#translate (<n1>.EQ.<n2>) =>    (IsZero((<n1>)-(<n2>)))
if (a.eq.b-c)
```
Expected behavior (xBase ppo)
```
if (IsZero((a)-(b-c)))
```

Actual behavior (x# ppo)
```
if (a.eq.b-c)
```

**Comment by RobertvanderHulst** [comment] 2022-02-18 09:03
Petr,
These are all examples of the same thing: that the regular match marker needs to exit matching input text when a certain "stop token" is found. In most of your examples the stop token is a `(` or a `.`.
Btw I am not sure why you would want to use a UDC `#translate (<n1>.EQ.<n2>) =>    (IsZero((<n1>)-(<n2>)))`.
This kind of code makes your source unnecessarily complex imho.

**Comment by kpa174** [comment] 2022-02-18 09:53
> Btw I am not sure why you would want to use a UDC `#translate (<n1>.EQ.<n2>) => (IsZero((<n1>)-(<n2>)))`.
> This kind of code makes your source unnecessarily complex imho.

We use them to compare floating point numbers. Usually money.
```
#define EPSILON 0.005
function isZero(n)
return (n <= EPSILON .and. n >= -EPSILON)
```

**Comment by kpa174** [comment] 2022-02-18 11:33
Robert, there's another problem. xBase++ doesn't have date literals. Therefore, we use this UDC:
```
#translate $<d>/<m>/<y> => ntod((<y>)*10000+(<m>)*100+(<d>))
local d := $18/02/2022
```
Expected behavior (xBase ppo)
```
local d := ntod((2022)*10000+(02)*100+(18))
```
Actual behavior (x# ppo)
```
local d := $18/02/2022
```

**Comment by RobertvanderHulst** [comment] 2022-02-18 14:34
I have changed the preprocessor to handle parentheses and other characters as stop tokens after a regular match marker.
However that are some problems that I cannot solve without major changes (that I do not want to do at this moment):

```
#xtranslate \{<b>..<e>\} => Range(<b>, <e>)
local o := {1..5}
```
Will be difficult to support unchanged because our lexer translates this into (whitespace removed)
```
LOCAL = KEYWORD
o  identifier
:= Assignment operator
{  LCurly
1 Integer constant
.  Dot
.5 Fractional constant
} RCurly
EOS = End Of Statement
```

If you put a space between second dot and the 5 then it works (at least with the changed preprocessor that I have here)
`local o := {1 .. 5}`

This should also work in Xbase++ with the extra space(s)

```
#translate $<d>/<m>/<y> => ntod((<y>)*10000+(<m>)*100+(<d>))
local d := $18/02/2022
```

For this rule there is another problem: the `$18` is matched with the FoxPro Currency literal and is therefore a single token and not 2 separate tokens so the code divides $18 by 2 and then by 2022.
Again : a whitespace character after the $ character will solve this.

`local d := $ 18/02/2022`
This should also work in Xbase++

The other rules should now work with the new compiler.

**Comment by kpa174** [comment] 2022-02-21 04:28
Robert, thanks for the detailed answer.
As for the Range example, the xBase preprocessor is smarter. If you write an expression:
`local o := {1...5}`
The xBase preprocessor will output:
`local o := Range(1, .5)`
Whereas the X# would say:
`error XS9002: Parser: unexpected input '.5'`

**Comment by kpa174** [comment] 2022-02-21 05:05
> For this rule there is another problem: the $18 is matched with the FoxPro Currency literal
We don't have such literals. Is it possible for a xBase dialect to de-recognize them?

**Comment by RobertvanderHulst** [comment] 2022-02-21 07:30
Petr,
I know of a XBase++ customer that really values the addition of the Currency type. He would be very displeased if I removed the currency support from X# for the Xbase++ dialect because some other user uses the `$` character in a UDC.
Since you can fairly easy change the use of the UDC with search/replace with a regular expression search I would advise you to add a space behind the $ in your custom date literals. 
W.r.t. Range command: it should also not be too difficult to change your code to add a space before and after the `..` characters.

**Comment by cpyrgas** [comment] 2022-02-21 09:52
Confirmed fixed, with the noted necessary adjustments.
Closing this in the sense that the issue has been taken care of, but of course discussion can continue!

**Closed by cpyrgas** 2022-02-21 09:52 UTC
Labels: bug, Compiler
