### ISSUE TITLE
Error 5041:  The requested object was not found.  Key not found.

### ISSUE THREAD

**Issue by christianschmid200272** [X-Sharp/XSharpPublic#1444] opened 2024-03-19 10:36 UTC
An exception is thrown if a new data record is added to a DBServer, a refresh is executed on the DBServer but the newly created data record is filtered out by the current filter of the DBServer.
If you remove the filter, there are no exceptions.

**XSharp: 2.19.0.2**
Subsystem: AXDBFCDX
Fehler-Subcode: 5041 (Error 5041:  The requested object was not found.  Key not found.)
Funktion: ORDERKEYNO

 Stacktrace: 
 ADSINDEX:_CHECKERROR (Line: 0)
 ADSINDEX:ORDERINFO (Line: 0)
 WORKAREA:ORDERINFO (Line: 0)
 COREDB:<>C__DISPLAYCLASS71_0:<ORDERINFO>B__0 (Line: 0)
 COREDB:DO (Line: 0)
 COREDB:ORDERINFO (Line: 0)
 VODB:ORDERINFO (Line: 0)
 DBSERVER:ORDERKEYNO (Line: 0)
 BDBSERVER:ORDERKEYNO (Line: 0)
 RUNTIMEMETHODHANDLE:INVOKEMETHOD (Line: 0)
 RUNTIMEMETHODINFO:UNSAFEINVOKEINTERNAL (Line: 0)
 RUNTIMEMETHODINFO:INVOKE (Line: 0)
 OOPHELPERS:SENDHELPER (Line: 0)
 OOPHELPERS:SENDHELPER (Line: 0)
 OOPHELPERS:DOSEND (Line: 0)
 __INTERNALSEND (Line: 0)
 BBROWSER:GETROWNO (Line: 0)
 BBROWSER:SELECTIONCHANGE (Line: 0)
 BBROWSER:REFRESH (Line: 0)
 BBROWSER:NOTIFY (Line: 0)
 RUNTIMEMETHODHANDLE:INVOKEMETHOD (Line: 0)
 RUNTIMEMETHODINFO:UNSAFEINVOKEINTERNAL (Line: 0)
 RUNTIMEMETHODINFO:INVOKE (Line: 0)
 OOPHELPERS:SENDHELPER (Line: 0)
 OOPHELPERS:SENDHELPER (Line: 0)
 OOPHELPERS:DOSEND (Line: 0)
 SEND (Line: 0)
 DBSERVER:NOTIFY (Line: 0)
 BDBSERVER:NOTIFY (Line: 0)
 DBSERVER:REFRESH (Line: 0)
 BDBSERVER:REFRESH (Line: 0)
 DTAQMVERWALTUNG:QMDOKUMENTPOSITIONEN (Line: 1907) //Call the refresh

**Comment by christianschmid200272** [comment] 2024-03-20 09:21
It seems to be a problem of the bServer/bBrowser , I close the issue.

**Comment by cpyrgas** [comment] 2024-03-20 09:57
Christian, can you reproduce the problem with a bServer alone (without GUI/bBrowser)? If yes, please send a repro sample, could very well be an rdd problem.

**Comment by christianschmid200272** [comment] 2024-03-21 06:26
Chris, after a longer debugging session from bbrower, bserver and x# RT I can  reproduce the problem in a small consol app.

#########################
USING System.IO
USING System.Collections.Generic
USING VO
USING System.Timers
USING System.Diagnostics
USING XSharp.RDD
USING VOSystemClasses


FUNCTION Start() AS VOID STRICT
   ? "Hello Error 5041 Demo! Today is ",Today()
   LOCAL oFSDemo     AS FileSpec
   LOCAL odbDemo		AS DbServer
   //you can use any table
   oFSDemo := FileSpec{"\\myserver\data\waehrung.DBF"}
   odbDemo :=  DbServer{oFSDemo, DBSHARED, DBREADWRITE, "AXDBFCDX"}
   //without this codeline an there is no exception
   odbDemo:SetFilter(,"KENNZ = ""I""")
   //appent row to the filtered server
   odbDemo:Append(FALSE)
   VAR nRecNo := odbDemo:RecNo
   //this line of code thrown the exception
   VAR nOrderKeyNo := odbDemo:OrderKeyNo()

   ?nRecNo
   ?nOrderKeyNo

   odbDemo:Close()
   wait
   RETURN

**Comment by cpyrgas** [comment] 2024-03-21 09:47
Christian thanks, but can you also provide the dbf so we can reproduce the problem here?

**Comment by christianschmid200272** [comment] 2024-03-21 10:07
Chris, her are the dbf file. [Daten.zip](https://github.com/X-Sharp/XSharpPublic/files/14693380/Daten.zip)

**Comment by RobertvanderHulst** [comment] 2024-03-22 09:43
The error only occurs when the setting Ax_SetExactKeyPos() is TRUE. This happens because the current record does not match the filter criterium.
If you issue Ax_SetExactKeyPos(FALSE) before calling DbOrderInfo( DBOI_POSITION )  then there is no error.
I can change the RDD code to do this automatically (silently) when the function AdsGetKeyNum() returns the error code 5041. Is that a good idea?
The ADS RDD for Vulcan generates the same error.

**Comment by christianschmid200272** [comment] 2024-03-22 11:46
Robert, it is probably better to switch silently than to trigger an error because VO does not trigger an error at this point and probably some programs rely on the fact that there is no error.

**Comment by cpyrgas** [comment] 2024-03-23 08:14
Christian, what value does VO return in this case?

**Comment by christianschmid200272** [comment] 2024-03-24 14:20
Chris, unfortunately I can't answer your question because in our application the error only occurs indirectly through the bBrowser when it executes a refresh and OrderKeyNo() is called in the course of this. Unfortunately, I can't debug this enough in VO to be able to say exactly what happens there.

**Comment by cpyrgas** [comment] 2024-03-26 09:46
Christian, can you please try with your small test sample? (in VO I mean) Just to make sure we are 100% compatible now.

**Comment by christianschmid200272** [comment] 2024-03-31 11:39
Hi Chris, with filter DbOrderInfo returns NIL.

VO example:
FUNCTION Start(p)
	LOCAL oCon as Console 
	local r as usual
	LOCAL cDbf as STRING
	
	cDbf := "\\server\data\ordkeyno"
	oCon := Console{}
	
	RddSetDefault ("AXDBFCDX")
	AdsSetServerType(1)
	
	FErase(cDbf + ".cdx")
	DBCREATE(cDbf, {{"KENNZ","C",3,0}})
	DBUSEAREA(,,cDbf)
	
	DBAPPEND()
	FIELDPUT(1,"1")
	DBAPPEND()
	FIELDPUT(1,"2")
	DBAPPEND()
	FIELDPUT(1,"3")
	DBAPPEND()
	FIELDPUT(1,"4")
	DBAPPEND()
	FIELDPUT(1,"5")	
	DBAPPEND()
	FIELDPUT(1,"6")	
	
	DBCREATEINDEX(cDbf, "KENNZ")
	DBCLOSEAREA()
	
	
	DBUSEAREA(true,,cDbf)
	DbSetFilter(,"KENNZ = '1'")
	DbGotop()
	DBAPPEND()
	FIELDPUT(1,"777")
	
	//with filter DbOrderInfo returns NIL, without filter DbOrderInfo returns 7
	r:= DbOrderInfo( DBOI_POSITION )
	
	DBCLOSEAREA()
	                    
	                    
  RETURN nil

**Comment by cpyrgas** [comment] 2024-04-01 09:34
Thanks Christian, now with Robert's fix, with either the filter set or not, order info in X# returns always 7. Not sure if this should be consisdered a problem (VO incompatibility) or not, considering that VO returns NIL with the filter.

**Comment by christianschmid200272** [comment] 2024-04-01 13:14
Chris, the 7 would be the right value in any case, yes the new behavior can lead to compatibility problems, if you have a fix for me I could test that at least for our context.

**Comment by cpyrgas** [comment] 2024-04-02 09:01
Christian, please try this new dll, you need to put it in the GAC at C:\Windows\Microsoft.NET\assembly\GAC_MSIL\XSharp.Rdd\v4.0_2.6.0.0__ed555a0467764586. I think there are no dependencies on any other changes we made since the last X# release, but in case something doesn't work ok, I will send you a complete new set of runtime dlls.

[XSharp.Rdd.zip](https://github.com/X-Sharp/XSharpPublic/files/14834152/XSharp.Rdd.zip)

**Comment by christianschmid200272** [comment] 2024-04-03 05:44
Chris, unfortunately it behaves differently to the old Vo application, could you create an XSharp.Rdd.dll for me that returns NIL like VO and not the actual correct value. I would also like to run a test with it.

**Comment by cpyrgas** [comment] 2024-04-03 07:06
Christian, are you sure the problem comes from this return value, does your code indeed depends on the return value of NIL, or could it be some other issue?
Will need to wait a little for Robert (who is offline this week) to adjust the RDD to return NIL in such cases, as I am not familiar with that code.

**Comment by christianschmid200272** [comment] 2024-04-04 05:05
Chris, I'm not sure because we are using the bBrowser and bServer here and the exception is passed through from there, a DLL with the return NIL would be the easiest way for me to test this.

**Comment by cpyrgas** [comment] 2024-04-05 09:19
Christian, OK, please give Robert a few days to look into this

**Comment by RobertvanderHulst** [comment] 2024-04-08 10:12
I have committed a change for this. Chris can you build the DLL and send it to Christian?

**Comment by cpyrgas** [comment] 2024-04-08 10:46
Yes of course, Christian please try again with this one:

[XSharp.Rdd.zip](https://github.com/X-Sharp/XSharpPublic/files/14904452/XSharp.Rdd.zip)

**Comment by christianschmid200272** [comment] 2024-04-09 11:43
Chris, the new version of the DLL behaves like the version that returns the correct value. I would prefer the correct value to the NIL returned for compatibility reasons.

**Comment by RobertvanderHulst** [comment] 2024-04-09 13:02
Christian,
To be compatible with VO we should return NIL. I am not sure why you say:
> I would prefer the correct value to the NIL returned for compatibility reasons.

**Comment by christianschmid200272** [comment] 2024-04-09 13:24
Robert, 
I just wanted to say that our application behaves the same with both variants, which is why NIL is absolutely ok as a return value.
Compatibility is of course very important and the decision is up to you, my experience with VO and X# is certainly not sufficient here.

**Comment by cpyrgas** [comment] 2024-04-10 08:28
Robert, my mistake, I uploaded the new dll without testing it first, but now that I did, I see that the return value is 0, not NIL, maybe this is why it hasn't fixed the root problem (I understood that right Christian, is that correct?)

**Comment by RobertvanderHulst** [comment] 2024-04-11 10:52
We are calling this inside the RDD

`ACE.AdsGetKeyNum(hIndex, ACE.ADS_RESPECTFILTERS, OUT dwKeyNo)`

And, this call returns 0 in dwKeyNo when the RDD is at EOF

The same code in VO also returns 0 when at EOF

**Comment by christianschmid200272** [comment] 2024-04-11 11:46
Sorry guys, but I have a lot on my plate at the moment and can't get around to reading my emails :-(
Robert, thanks for answering Chris' question.
Chris, no more exceptions will be triggered, we can work with the solution from the last fix.

**Comment by cpyrgas** [comment] 2024-04-12 06:38
OK, that's great, problem is confirmed fixed then!

**Closed by cpyrgas** 2024-04-12 06:38 UTC
Labels: bug, RDD
