### ISSUE TITLE
Some problems with the VS option "Show completion list after a character is typed"

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#285] opened 2019-12-15 15:58 UTC
Enable this option in VS settings, seems it is still quite clumsy.

Type the following for example:

CLASS TestClass
METHOD TestMethod() AS VOID
IF TRU

when you type "TRU", "TRUE" is offered as an autotype option, select it with <enter>. It does type it, but also types an extra space at the end. Some happens with most (but not all) other keywords, there's an extra space

Hit <enter> to go to a new line, now try to type "ENDIF". When you type the 3 first characters, the list pops up, but shows a list with all available identifiers, namespaces etc, not only those starting with "END". Now also type "i", so you end up with "ENDI", now the list shows everything that starts with an "I"

**Comment by RobertvanderHulst** [comment] 2020-05-02 14:54
Duplicate of #43

**Closed** 2020-06-09 18:13 UTC
Labels: bug, vs editor
