### ISSUE TITLE
Incorrect display of CheckBox font in VOWED

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#796] opened 2021-10-01 09:33 UTC
When choosing a font other than the default in VOWED for a CheckBox control, two problems arise (also possible with other controls):
1. Incorrect display of the selected font on the editor form.
2. When you select the font size, for example 11, instead of the selected integer value, a fractional value is stored, for example 11.25.

Here's an illustrative screenshot:
![screenshot](https://user-images.githubusercontent.com/64518775/135598298-879aafb8-7330-47b9-b5cf-d25f15c8e3b1.png)

**Comment by cpyrgas** [comment] 2021-10-01 17:06
Leonid, this (fractional) size is the actual size return by the system code for the selected font. Try this:

VAR d := System.Windows.Forms.FontDialog{}
d:ShowDialog()
? d:Font:Size

and select a font with size 11, you will see that the actual size returned is 11.25. I had thought about truncating the value when displaying it, but at the end thought that since this is the actual size, then better display it as is.

I guess this is just a cosmetic issue fro you in design mode only, right? Or is this causing some other problem?

**Comment by leon-ts** [comment] 2021-10-04 06:40
Chris,

I noticed this behavior when I saw that the text in the CheckBox is displayed incorrectly. So I thought it was because of the fractional font size. Whether this will cause any other problems, I do not know yet. I ported the app from VO to X# and the Calibri 11 font is preserved correctly. And the other day for the first time I had to edit the window already in X# and I saw the result described above.

I did a little research on this question, why this is happening. This is due to the ratio of dots per inch to the logical resolution of the screen. Actual calculations give fractional values ​​for some font sizes. But as practice shows, their equivalents rounded to the nearest integer still give the correct result in the end. At least in VO. As for Word and others, it is possible that inside they store a real (fractional) value, and display an integer value to the user. I don’t know. But the fact is that what (integer) value the user chooses, it remains so.

**Comment by cpyrgas** [comment] 2021-10-04 07:17
Leonid, so you are saying the text is displayed incorrectly? Can you please elaborate, what is wrong with it? Maybe show a screenshot between the same thing in VO and X#, so I can see what you mean? Also is the problem happening only in design mode, or also at runtime?

**Comment by leon-ts** [comment] 2021-10-04 07:39
Chris,
In this ticket I have attached a screenshot (see above). For example, I added a FixedText control to the form, in which the Calibri 11 font is displayed correctly (in VO, the same). To the right of it, I put a green checkmark. Under this control, I added a CheckBox control where the Calibri 11 font is displayed incorrectly. Thus, in this screenshot you can see two displays of the Calibri 11 font - the correct one (FixedText) and the incorrect one (CheckBox) below. That is, the problem is visible on the CheckBox (and maybe on some other controls, but I haven't looked at all). This issue only occurs in the form editor. At runtime, the font is displayed correctly.

**Comment by leon-ts** [comment] 2021-10-04 07:43
> (in VO, the same)

I mean, in all editors (this is the actual correct style of the given font in the given size), including VO.

**Comment by cpyrgas** [comment] 2021-10-04 08:16
Leonid, do you mean the problem is the checkbox only then? And it always exists? Maybe you are referring to the same problems as in https://github.com/X-Sharp/XSharpPublic/issues/741 and https://github.com/X-Sharp/XSharpPublic/issues/573 which are now fixed?

If yes, please check again with the new build as soon as it is released, and if you are still seeing problems, please post a sample .aef with a window demonstrating the difference of the controls shown in VO and X#.

**Comment by leon-ts** [comment] 2021-10-04 09:19
Chris,
Yes, I have described a problem that only occurs for CheckBox. The tickets you mentioned describe other problems. But it is possible that when you fixed them, it also affected the font issue.
Do you see the screenshot that I attached to this ticket under the text "_Here's an illustrative screenshot:_"? There you can clearly see how this problem manifests itself. The screenshot shows that the Calibri font is rendered differently for different controls inside X# (display in VO in this case does not matter). For FixedText, it renders correctly. But for CheckBox, no. If the screenshot I mentioned for some reason does not appear on your ticket, I will attach an archive with a PNG file: 
[screenshot.zip](https://github.com/X-Sharp/XSharpPublic/files/7276930/screenshot.zip)

**Comment by cpyrgas** [comment] 2021-10-04 13:19
Leonid, I can see the screenshot, I just wasn't sure what the problem was. I think you mean that the two texts appear a bit differently, but they are both using the same font, styles etc, right? I tried doing the same in a window now and they seem to be (almost) identical, so please try again with the new build. If you still see problems, please post a sample, so I cat test with the exact same settings etc.

**Comment by leon-ts** [comment] 2021-10-04 14:17
Chris,
Yes, two different controls have the same font and size, but they look different. The problem is specifically with the CheckBox. All other controls are displayed correctly in all sizes. I noticed that this appears only for certain sizes. For example, 8 and 16 are displayed correctly, but 9, 10, 11, 12, 14 are not.

Ok, I'll see it in version 2.9.
I really hope that your team will release it this week. We are really looking forward to it from August.

**Comment by cpyrgas** [comment] 2021-10-04 17:46
We're still looking into some issues that we found through testing. I think it will be difficult to release it this week, but we'll try.

**Comment by leon-ts** [comment] 2022-04-13 08:46
Hi Chris,
In version 2.9 this problem still exists. Our software products are already in production on this version, so we are not updating it yet. This is not a critical issue.

**Comment by cpyrgas** [comment] 2022-04-13 08:54
Hi Leonid,
Ah OK! When you do move to a later X# version, please let me know if you still see this.

**Comment by cpyrgas** [comment] 2023-03-27 08:11
Actually I can reproduce the problem still in 2.15, text between a checkbox and a fixedtext appear differently, as demonstrated in the report.

**Comment by cpyrgas** [comment] 2023-09-09 07:21
Difference between the FixedText and the CheckBox is that while text in FixedText controls is drawn by the system normally, in the CheckBox it is drawn manually using Graphics:DrawString(), in order to make it compatible to VO regarding clipping, alignment etc (the default behavior of WinForms is different to that of Win32). 

Apparently in some cases the manual drawing gives different results regarding how the text itself appears for some fonts, trying to find a setting in the Graphics class that makes it more Win32 compatible.

**Comment by cpyrgas** [comment] 2023-09-18 07:42
Found this:

Graphics:TextRenderingHint := System.Drawing.Text.TextRenderingHint.AntiAliasGridFit

which makes the text look very close to the Win32 version for this particular font setting, but unfortunately doesn't look as good with the default font... 

Apparently the only possible way to have the same result, is to use Win32 drawing of text, with the DrawText() or DrawTextEx() API function. First results are promising regarding how the text looks like, but need to make it also respect the various alignment settings of the designed control

**Comment by cpyrgas** [comment] 2023-09-19 16:29
Fixed. Now the caption of CheckBox (and also RadioButton which had the same problem) controls are drawn with Win32 API function DrawText() which should always give the same look as when running the app

**Closed** 2023-09-20 11:01 UTC
Labels: bug, VS VO binary editor
