### ISSUE TITLE
Project Properties: Not able to save "Allow Old Style assignments"

### ISSUE THREAD

**Issue by MarioV-GH** [X-Sharp/XSharpPublic#1582] opened 2024-10-02 12:33 UTC
**Describe the bug**
After setting the checkbox "Allow Old Style assignments" to true and restart of Visual Studio, the setting was reset to "not checked".

**To Reproduce**
1. Set checkbox "Allow Old Style assignments" in the project settings / Language
2. Save
3. Close and start Visual Studio
4. Check the checkbox "Allow Old Style assignments"

**Expected behavior**
The setting for this checkbox should remain saved.

![Screenshot 2024-10-02 143245](https://github.com/user-attachments/assets/23aa184e-cd92-494f-888d-b18fd94a1ff0)

**Comment by RobertvanderHulst** [comment] 2024-10-02 12:59
This is a duplicate of #1495 and will be fixed in 2.21.

**Closed** 2024-10-02 13:03 UTC
Labels: duplicate, vs projectsystem

**Comment by cpyrgas** [comment] 2024-10-03 23:37
Confirmed fixed. @MarioV-GH , don't worry about that!
