### ISSUE TITLE
Filling the structure clears up local variables

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#735] opened 2021-07-19 08:55 UTC
When the following code is executed, the **oObj** variable becomes null after the MemClear function is executed:
```
FUNCTION Start() AS VOID STRICT

	LOCAL oObj AS OBJECT
	LOCAL st IS MYSTRUCT

	oObj := OBJECT{}
	MemClear(@st, _SIZEOF(MYSTRUCT))

	RETURN

INTERNAL VOSTRUCT MYSTRUCT
	MEMBER dwVal1 AS DWORD
	MEMBER dwVal2 AS DWORD
	MEMBER DIM bArray1[17] AS BYTE
	MEMBER dDate AS DATE
	MEMBER DIM bArray2[221] AS BYTE
	MEMBER dwVal4 AS DWORD
```

The sample code is taken from a real application, where only the names of fields and variables have been changed.

The size of the MYSTRUCT structure was incorrectly calculated (larger than it should), as a result of which the value of the **oObj** variable was overwritten on the stack. _SIZEOF(MYSTRUCT) returns the value 260, although the actual size of the structure is 254. As a result, the MemClear function wipes the extra 6 bytes in the stack, 4 bytes of which belong to the **oObj** variable.

Also I think this problem is related to the problem already described in this ticket: [734](https://github.com/X-Sharp/XSharpPublic/issues/734)
The problem is very serious.

**Comment by RobertvanderHulst** [comment] 2021-07-19 17:23
Leonid,
The problem with this code seems to be the use of the MEMBER dDate AS DATE
In earlier builds we translated _sizeof() to System.Runtime.InteropServices.Marshal.Sizeof() and we did not allow DATE and SYMBOL inside structires.
That caused problems when people used _sizeof() inside DEFINES and because people were using SYMBOL and DATE inside structures in VO. So now we are calculating the size at compile time and we allow these types.
This apparently is done incorrectly or Marshal.SizeOf() does not understand the size of the DATE in the structure.
When I run this code: 
```
	? _SIZEOF(MYSTRUCT)
	? System.Runtime.InteropServices.Marshal.Sizeof(typeof(MYSTRUCT))
```

Then the first line outputs 260 and the second line 256.
If you change dDate AS DATE to dDate as DWORD then both sizes are 260.

If you look at the generated EXE with ILSpy then you will see that the MYSTRUCT structure has been marked with a [VOstruct] attribute with the size of 260. This is the size that is used for _SIZEOF() too. But the structure on the stack is calculated by the .Net runtime and has the size 256...
If you compile this with Vulcan (you will have to change the DATE to a DWORD because Vulcan does not allow DATE variables in structures) then the size is also 260. 
And in VO the structure is also 260 bytes (with DATE and DWORD).
I did some more analysis and added this code
```
LOCAL pStart AS DWORD
 pStart := DWORD(_CAST,@st)
? DWORD(_CAST,@st.dwVal1) - pStart // 0
? DWORD(_CAST,@st.dwVal2) - pStart // 4
? DWORD(_CAST,@st.bArray1) - pStart // 8
? DWORD(_CAST,@st.dDate) - pStart  // 25 = incorrect, should be aligned to DWORD = 28
? DWORD(_CAST,@st.bArray2) - pStart
? DWORD(_CAST,@st.dwVal4) - pStart
```
If you compare the results in VO with the results in X# with the DATE type then you will see that the .Net runtime puts the dDate on memory location 25 but it should have been 28.
The problem is most likely caused by the attribute on the __Date type:
`[StructLayout(LayoutKind.Explicit, Pack = 1)]`
I'll investigate this further and will fix it.

**Comment by cpyrgas** [comment] 2021-07-30 16:50
Guys, when I use _SIZEOF(MYSTRUCT) in VO, I do get 260 as a result, not 254! Am I missing something?

**Comment by leon-ts** [comment] 2021-07-30 17:19
Chris,
It should be so. The problem lies in the different result when calculating the size of the structure for the stack and the value returned from _SIZEOF. As a result, less memory is allocated on the stack than needed. Robert wrote about this:
> But the structure on the stack is calculated by the .Net runtime and has the size 256...

**Comment by leon-ts** [comment] 2021-07-30 17:22
When I wrote about the value 254, I meant that apparently such a volume was allocated on the stack. I did not write anything about VO on this ticket.

**Comment by leon-ts** [comment] 2021-07-30 17:34
To be honest, I do not know how to fully check if the correct amount is allocated on the stack. Robert applied еру test that works if the size of the structure on the stack is less than _SIZEOF returns. But if _SIZEOF returns a value less than the value allocated on the stack, then the problem will not be reproduced, but the MemClear or MemSet functions will not process all the memory of the structure, which will lead to the program malfunctioning.

**Comment by cpyrgas** [comment] 2021-07-30 23:15
Leonid, ah sorry, I misunderstood, when you said that the code is taken from a real application, I had assumed this was a VO application ported to X#.

**Comment by leon-ts** [comment] 2021-07-31 05:18
Chris,
You got it right. This is truly a VO application ported to X#. When I said that I did not mention VO, I meant that this ticket does not describe the difference in the operation of the _SIZEOF operator in VO and X#. This ticket describes the difference in sizing for a specific structure within X# - the compiler allocates one volume for the stack, and the _SIZEOF operator returns a different value for the volume. This difference raises a serious problem in the application.

But there is also a difference in how the _SIZEOF operator works in VO and X#. And this other problem with an example, when it occurs, I described in another ticket with the number 734.

**Comment by RobertvanderHulst** [comment] 2021-07-31 06:38
Guys,
The easiest solution for us would be to translate all _sizeof() code to Marshal.SizeOf() and calculate the sizes at runtime.
However that does not work if people use _sizeof() in a DEFINE and then use that define to declare a structure. This was what happened in the ticket that triggered me to make the change.
Anyway the sizes calculated in X# are correct in the current build.

**Comment by cpyrgas** [comment] 2021-07-31 08:53
Thanks for persisting guys, I finally got this :)

But I think there's still a problem in the newer compiler, the test app (and test case R796) exits abruptly, so this tells me that the MemClear(@st, _SIZEOF(MYSTRUCT)) call still wipes out memory outside of the structure memory location. I noticed that _SIZEOF(MYSTRUCT) still returns 260, so when I changed the call to MemClear(@st, 256), now the code works correctly.

There's also a problem with test R756 now, the size returned by _SIZEOF(_test) now for the structure

VOSTRUCT _test 
    MEMBER a AS LONG
    MEMBER b AS DWORD
    MEMBER c AS WORD
    MEMBER d AS SHORT

is now 16m while it used to be 12 and VO also returns 12.

Since this is causing so much trouble, I think it's OK to simply disallow using _SizeOf() in a DEFINE and mark this as a VO compatibility difference. The workaround will be relatively easy, the developer will need to supply the actual literal value instead, which is easy enough to obtain. Not ideal, but better than having possible timebombs in the code.

**Comment by cpyrgas** [comment] 2021-07-31 11:45
Also apparently the way to check if the code works correctly at runtime with the addresses of two OBJECTs is not reliable, because if you type:

? INT(@oObj) - INT(@oObj2) // 4
? INT(@st) - INT(@oObj2)   // 8

you get 4,8, which means that the CLR has actually put variables in the memory in this order: oObj2, oObj, st. So overflowing the memory occupied by st will not affect the contents of oObj or oObj, but will instead corrupt memory after that memory. And this is what is actually happening at runtime.

**Comment by cpyrgas** [comment] 2021-07-31 11:55
I have adjusted https://github.com/X-Sharp/XSharpDev/commit/674e1c12ad8ad01f027f87d3a3158576ea4a4e36 to cover the above. The test now does fail at runtime.

**Comment by leon-ts** [comment] 2021-07-31 13:38
Robert,
> The easiest solution for us would be to translate all _sizeof() code to Marshal.SizeOf() and calculate the sizes at runtime.

Marshal.SizeOf(MYSTRUCT) returns 256. And _SIZEOF(MYSTRUCT) in VO returns 260. It turns out that this approach does not solve the size compatibility issue of structures in X# and VO. That is, binaries created in VO based on structures may not read correctly in X#.

Chris,
> Since this is causing so much trouble, I think it's OK to simply disallow using _SizeOf() in a DEFINE and mark this as a VO compatibility difference.

Removing support for the _SIZEOF operator in DEFINE will not play a special role here, since Marshal.SizeOf () for certain structures differs from _SIZEOF in VO (see above). And this is the problem described in ticket 734. In an amicable way, probably these problems should have been combined into one ticket. Otherwise, misunderstandings may arise.

**Comment by leon-ts** [comment] 2021-07-31 14:06
Guys,
I looked through ILSpy that if the _SIZEOF operator is used in DEFINE, then the IL code looks like this (version 2.8c):
`public unsafe static initonly MYSTRUCTSIZE := (DWord)sizeof(MYSTRUCT) as DWord`
But in this line, you can easily use the Marshal.SizeOf () method or, in general, a custom method that calculates the correct size of the structure:
`public static initonly MYSTRUCTSIZE := (DWord)Marshal.SizeOf(typeof(MYSTRUCT)) as DWord`

Therefore, I do not understand the problem with the support for _SIZEOF in DEFINE. But I do not exclude that I do not understand something.

**Comment by leon-ts** [comment] 2021-07-31 15:31
Robert,
I've experimented more with the VO-SIZEOF and Marshal.SizeOf operators and they actually return the same result. The problem really arises, as you found out earlier, only if the DATE type is present in the structure. If in the MYSTRUCT structure change the dDate field from DATE type to DWORD type, then the problem disappears and VO-SIZEOF and Marshal.SizeOf return the same result (260 bytes).

Maybe for use in structures at compile time, consider the DATE type as a DWORD and automatically do type conversions? Or create some kind of special _VoDate class for vostruct which will replace the DATE type in vostruct during compilation?

```
STRUCTURE _VoDate
	HIDDEN dwValue AS DWORD
	// Methods for overloading type conversion operations (in particular _VoDate to DATE and vice versa) 
```

**Comment by RobertvanderHulst** [comment] 2021-07-31 15:38
Leonid,
I think the MarshalOf code gets confused by the explicit layout of the __Date structure. I noticed that the StructLayout attribute also has a field called Size. I'll first try to set this field with the right value (4). Most likely that will solve it.
When this does not work then we can indeed consider to embed the __Date in a special structure.

The problem we had with using sizeof() in a define is when the define was later used inside another structure

```
DEFINE MYSIZE := _sizeof(SomeStruct)
VOSTRUCT AnotherStruct
MEMBER DIM bArray[MYSIZE] as Byte
```
To make this work we must know the size at compile time.

**Comment by RobertvanderHulst** [comment] 2021-07-31 15:49
Ok, found it:
when I change the layout attribute on the __Date type to:
`	[StructLayout(LayoutKind.Explicit, Size := 4)];
`
so 
- remove the pack
- add the size
Then it works as expected.

**Comment by leon-ts** [comment] 2021-07-31 15:54
Robert,
> The problem we had with using sizeof() in a define is when the define was later used inside another structure

Now I understand. I thought the problem was only with the DEFINE declaration. Thanks a lot for the clarification.

**Comment by cpyrgas** [comment] 2021-08-01 11:49
Problem is completely fixed now!

**Closed by cpyrgas** 2021-08-01 11:49 UTC
Labels: Compiler, bug

**Comment by leon-ts** [comment] 2021-08-02 05:19
I think it will be enough to mention in the documentation that if data is exchanged between VO and X#, for example, through a structured binary file in which there are fields of type DATE, then in X # this field must be declared in the structure as DWORD.

**Comment by leon-ts** [comment] 2021-08-02 05:24
A radical option would be to change the DATE type itself in X#. For example, if the **_ymd** field stores the number of days, as in VO, and the **_year**, **_month**, and **_day** fields are transferred from fields to properties that calculate their values from **_ymd**, then the DATE type in X# will be structurally compatible with VO.

**Comment by cpyrgas** [comment] 2021-08-02 08:42
Leonid, the main reason for choosing this structure of the date class I think is efficiency/performance and ease of use. A lot of the types in X#/.Net are structurally inevitably different than in VO, strings, symbols etc are different, so I'm not sure it's worth losing that for making DATE structurally identical to VO's implementation.

**Comment by leon-ts** [comment] 2021-08-02 09:07
Chris, I totally agree with you.
That's why I wrote that this is a radical option at your discretion. But what, in my opinion, must be done without changing anything in X#, is to mention this difference in storing the DATE type in VO and X# in the documentation. This reference became important after a recent version of X # added support for the DATE type to VOSTRUCT.

**Comment by RobertvanderHulst** [comment] 2021-08-02 10:14
Leonid

I will create a _windate structure that persists the date in a vo compatible binary format.

**Comment by leon-ts** [comment] 2021-09-06 07:49
Guys,
Is it realistic to patch this fix for version 2.8c? This refers to those problems in the code that are very difficult to overcome (in a large application). I'm also interested in fixing M->: https://github.com/X-Sharp/XSharpPublic/issues/738

**Comment by RobertvanderHulst** [comment] 2021-09-06 07:57
Leonid,
I just added ticket 773 to create the _WinDate structure that we discussed.
The compiler will also have to be told to use this structure instead of the Date (just like it does for _WinBool instead of logic).

**Comment by RobertvanderHulst** [comment] 2021-09-06 07:59
I will see if I can do this later this week and if I can then send you a "patch version"

**Comment by leon-ts** [comment] 2021-09-06 08:00
Robert,
I meant the problem in general with _SIZEOF, that it incorrectly calculated the size of the structure in memory.

**Comment by leon-ts** [comment] 2021-09-06 08:14
Robert,
Just to clarify: I can still get around the problem with _WinDate by using DWORD in the structure instead of DATE. That is, this problem is not yet critical. Now I am interested in specifically the problems you have already fixed (tickets are marked as Done), in particular, with the incorrect calculation of the structure size, which leads to overwriting the stack.

**Comment by RobertvanderHulst** [comment] 2021-09-06 08:33
Leon, I did understand that. However I also want to add the proper support for DATE values inside structures. It is really not very difficult.

**Comment by leon-ts** [comment] 2021-09-06 08:36
Robert,
Thanks!
