### ISSUE TITLE
Go to definition not working with super and partial classes

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1141] opened 2022-09-22 06:32 UTC
If you try to call "Go to definition" on "return super:GetVal()" than the cursor goes allways to the start of "class Test..." instead of BaseTest:GetVal.
It seems to be only if the class is a partial class
```
partial class BaseTest
	public virtual method GetVal2() as int
		return 2
end class

partial class BaseTest
	public virtual method GetVal() as int
		return 3
end class

class Test inherit BaseTest	
	public override method GetVal() as int
		return super:GetVal()
end class
```

**Comment by RobertvanderHulst** [comment] 2023-01-30 15:16
The problem in the above example was caused by the fact that 2 partial classes with the same name existed in the same source file. We had not taken that into account, and the methods for the 2nd instance of the class were not written to the codemodel database.

**Comment by cpyrgas** [comment] 2023-02-01 09:51
When copy/pasting the code in a prg, then the problem still happens, cursor incorrectly goes to the child class. It gets fixed only after you close and reopen the solution, now indeed goes to the parent method.

Now select "Rebuild intellisense database", VS closes and reopens, and the problem returns back again. Close and reopen the solution, it's now working again as expected. Etc.

Maybe this is a more general problem with how the database is created/stored?

**Comment by cpyrgas** [comment] 2023-02-01 09:59
Hmmm, this looks like a general problem with intellisense in the new build actually..

**Closed** 2023-02-01 10:12 UTC
Labels: bug, enhancement, vs editor
