### ISSUE TITLE
Dialect XBase++: implicit access to static class members

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1215] opened 2023-02-28 09:20 UTC
**Describe the bug**
X# compiler doesn't recognize implicit access to static class members

**To Reproduce**
```
procedure main()
    local o

    ? Example():a
    ? Example():ClassFormula()
    
    o := Example():new(5)
    ? o:b
    ? o:Formula()
return


class Example
exported:
    inline class method InitClass()
        ::a := 3
    return

    inline class method ClassFormula()
    return ::a + 1

    inline method Init(b)
        ::b := b
    return self

    inline method Formula()
    return ::a + ::b

    class var a
    var b
endclass
```

**Expected behavior (xBase++ exe)**
Output
```
3
4
5
8
```

**Actual behavior (X# compiler)**
```
xsharp2.prg(16,9): error XS0026: Keyword 'SELF' is not valid in a static property, static method, or static field initializer
xsharp2.prg(16,9): error XS0176: Member 'Example.a' cannot be accessed with an instance reference; qualify it with a type name instead
xsharp2.prg(20,5): error XS0026: Keyword 'SELF' is not valid in a static property, static method, or static field initializer
xsharp2.prg(20,5): error XS0176: Member 'Example.a' cannot be accessed with an instance reference; qualify it with a type name instead
xsharp2.prg(27,5): error XS0176: Member 'Example.a' cannot be accessed with an instance reference; qualify it with a type name instead
xsharp2.prg(4,5): error XS1955: Non-invocable member 'Example' cannot be used like a method.
xsharp2.prg(5,5): error XS1955: Non-invocable member 'Example' cannot be used like a method.
```

**Additional context**
X# Compiler version 2.14.0.4 (release)
-dialect:xBase++ -lb -memvar -vo1 -vo5 -vo15 -vo16

Also, the built-in methods don't work:
:ClassName()
:ClassObject()
:isDerivedFrom()

**Comment by RobertvanderHulst** [comment] 2023-02-28 11:04
It was our understanding that `::` was a synonym for `SELF:`.
That is what the compiler translates it to at this moment.
Apparently we were wrong and it can also reference class variables.
Probably the easiest solution would be to translate it therefore to `nothing`, and let the compiler resolve it to a static or instance class variable.
The only possible problem with translating it to `nothing` is when there is also a local variable with the same name as the static or instance variable. Without prefix the compiler will resolve the name then to the local variable.
This needs some research.

The methods ClassName(), ClassObject() and IsDerivedFrom are implemented in the Abstract class in the XSharp.XPP namespace. To automatically have these in your code you need to enable the /xpp1 compiler option (Called 'Inherit from Abstract class') on the dialect page in VS:
https://www.xsharp.eu/help/proppage-dialect.html
The abstract class is documented here:
https://www.xsharp.eu/runtimehelp/html/T_XSharp_XPP_Abstract.htm
You can view the source code for this class by clicking on the [View Source] button in the documentation.

In theory, we could also implement these as extension methods on the System.Object class, but we have chosen to do this in a separate base class that also has some other support methods.

**Comment by DenGhostYY** [comment] 2023-03-01 04:04
This code is working.
```
procedure main()
    local o

    ? Example:a
    ? Example:ClassFormula()
    
    o := Example():new(5)
    ? o:b
    ? o:Formula()
    wait
return


class Example
exported:
    inline class method InitClass()
        Example:a := 3
    return

    inline class method ClassFormula()
    return Example:a + 1

    inline method Init(b)
        ::b := b
    return self

    inline method Formula()
    return Example:a + ::b

    class var a
    var b
endclass
```
Imho, `::` for static members is better translated into `<current_classname>:<static_name>`.
Besides, do not forget about explicit calls by class name (in X# isn't working):
```
class Example2 from Example
exported:
    inline method Init(b)
    return ::Example:Init(b)

    inline method Formula()
    return super:Formula() + 1
endclass
```
In X# next variant is working:
```
class Example2 from Example
exported:
    inline method Init(b)
        super:Init(b)
    return self

    inline method Formula()
    return super:Formula() + 1
endclass
```

**Comment by DenGhostYY** [comment] 2023-03-01 04:10
I tried to add parameter `-xpp1`, but I am facing the same error.
```
XSharp.Error: No exported method
   в XSharp.RT.OOPHelpers.DoSend(Object oObject, String cMethod, __Usual[] args, String cCaller)
   в XSharp.RT.Functions.__InternalSend(__Usual oObject, String cMethod, __Usual[] args)
   в xsharp3.Exe.Functions.main(__Usual[] Xs$Args)
   в xsharp3.Exe.Functions.Start(String[] Xs$Args)
```
Please, tell me, why is this happening?

**Comment by RobertvanderHulst** [comment] 2023-03-01 07:19
> I tried to add parameter `-xpp1`, but I am facing the same error.
> 
> ```
> XSharp.Error: No exported method
>    в XSharp.RT.OOPHelpers.DoSend(Object oObject, String cMethod, __Usual[] args, String cCaller)
>    в XSharp.RT.Functions.__InternalSend(__Usual oObject, String cMethod, __Usual[] args)
>    в xsharp3.Exe.Functions.main(__Usual[] Xs$Args)
>    в xsharp3.Exe.Functions.Start(String[] Xs$Args)
> ```
> 
> Please, tell me, why is this happening?

Can you attach a sample project showing the error?

**Comment by RobertvanderHulst** [comment] 2023-03-01 07:25
W.r.t. translating `::` into something:
- at this moment, the parser translates `::` into `SELF:`. At that stage in the compiler we do not "know" if the variable/method/property is implemented at the class level or at the instance level
- the syntax `::Example:Init(..)` has the same problem. The parser does not "know" if `::Example` means `SELF:Example` or the typename `Example`. In X# you can write `Example.Init()` for calls to static method btw.

So most likely we will have to move the resolution of `::` from the parser to the binder.

**Comment by DenGhostYY** [comment] 2023-03-01 08:51
[XSharpConsole.zip](https://github.com/X-Sharp/XSharpPublic/files/10858908/XSharpConsole.zip)

**Comment by RobertvanderHulst** [comment] 2023-03-08 14:08
I have changed the parser to translate `::` to `ClassName.` inside static (class) members of a class .
Inside Instance members, we do not know at parsing time if `::a` is a static (class) field or an instance field.
This gets therefore translated into `self:`.
Later in the binder, when we detect that `self:` was not correct, then the compiler allows `::` as alternative for `ClassName.` 

Translating `Example().a` to `Example.a` is a bit more complex. For now, I have changed the compiler to allow `Example:a` as alias for `Example.a` so that code compiles both in Xbase++ and X#.

The example program shows indeed that the /xpp1 compiler option in the current build does not automatically make the classes inherit from XSharp.XPP.Abstract. I have fixed that too.

**Comment by DenGhostYY** [comment] 2023-03-13 06:05
> Translating Example().a to Example.a is a bit more complex. For now, I have changed the compiler to allow Example:a as alias for Example.a so that code compiles both in Xbase++ and X#.

Did I understand correctly, that the construction `Example():a` will mean `Example.a` for X#? The syntax analyzer of Xbase++ displays a warning "Ambiguous variable reference Example" on the `Example:a`

**Comment by RobertvanderHulst** [comment] 2023-03-13 08:34
You are right that accessing class variables, such as in `Example():a` natively should be done with `Example.a`.
It will be very difficult to emulate that at compile time with the "function style" syntax,

We have considered generating special "class functions" next to the class itself when compiling in the XBase++ dialect.
So the compiler would then generate both type `Example` type and the `Example()` function.

This class function could return a helper object with a New() method (to support Example():New(...) ) and with methods that would be used to resolve `Example():A` 

Inside this helper object, we could then retrieve the meta data for the Example() class and figure out if "A" was the valid name of a class variable of type `Example`. It could then also translate `Example():ClassFormula()` into a call to the `ClassFormula` method, if that method exists,

However, that would mean that all of this is done at runtime and not at compile time. 
Typos in field names or method names would not be shown at compile time and everything would be weakly typed, so the code would be slower at runtime.

If this is really something that you want, then we can probably implement that. But it will have the disadvantages that I mentioned.

**Comment by DenGhostYY** [comment] 2023-03-14 03:26
Xbase++ syntax compatibility and identical execution are our highest priority. Runtime and weak typing are of lower priority for us. If the X# program really runs much slower than the XBase++, then we will think about what to do.

**Comment by RobertvanderHulst** [comment] 2023-04-03 14:37
See #1235

**Comment by cpyrgas** [comment] 2023-04-20 07:07
Looks good, except there is a bogus warning when accessing the static members via "normal" .Net syntax:

```
warning XS9073: Variable 'Example' has not been declared. Assuming this is a FIELD or a MEMVAR. (3 times)

PROCEDURE main()
	Example.staticVar := 123
	? Example.staticVar
	
	? Example.staticMethod()
RETURN

CLASS Example
EXPORTED:
    CLASS VAR staticVar
    INLINE CLASS METHOD staticMethod()
    RETURN 456
ENDCLASS
```

Also not sure if in the XPP dialect, it should be allowed to use also the colon operator in the above sample to access the static members. (I will run fast now :))

**Comment by DenGhostYY** [comment] 2023-04-20 09:48
Doesn't the generated class function resolve the name `Example`? You mean you're not sure? The examples I gave above are typical. In Xbase++ dialect only colon is used as instance membership operator, including for static members.

**Comment by RobertvanderHulst** [comment] 2023-04-20 11:33
> Looks good, except there is a bogus warning when accessing the static members via "normal" .Net syntax:
> 
> ```
> warning XS9073: Variable 'Example' has not been declared. Assuming this is a FIELD or a MEMVAR. (3 times)
> 
> PROCEDURE main()
> 	Example.staticVar := 123
> 	? Example.staticVar
> 	
> 	? Example.staticMethod()
> RETURN
> 
> CLASS Example
> EXPORTED:
>     CLASS VAR staticVar
>     INLINE CLASS METHOD staticMethod()
>     RETURN 456
> ENDCLASS
> ```
> 
> Also not sure if in the XPP dialect, it should be allowed to use also the colon operator in the above sample to access the static members. (I will run fast now :))

I will look into this. The generated code DOES access the class field and class method.

**Comment by DenGhostYY** [comment] 2023-04-21 05:25
```

**Comment by DenGhostYY** [comment] 2023-04-21 05:27
Will this example work in X# version 2.16?
```
procedure Main()
    local o
    
    o := DerivedExample():new()
    ? o:a
    ? o:Example:a // Runtime error in X# 2.14
    ? o:Name()
    ? o:Example:Name() // Runtime error in X# 2.14
    
    wait
    return
    
class DerivedExample from Example
exported:
    inline method Init()
        super:Init()
        ::a := 4
        super:a := 5
        return self
        
    inline method Name()
        return "DerivedExample"
        
    var a
endclass


class Example
exported:
    inline method Init()
        ::a := 3
        return self
        
    inline method Name()
        return "Example"
        
    var a
endclass
```

**Comment by cpyrgas** [comment] 2023-04-21 08:05
It's compiling, but isn't working at runtime. First there's an error on calling SUPER:Init(), which I think it's a bug, which should be easy to fix.

But the syntax `o:Example:a` and `o:Example:Name()` to access a (non static) var/method of a specific class in the hierarchy of the object isn't working either (runtime error) and I'm not sure if it can be fully supported. I was not aware of this syntax.

Btw, my comment above regarding `Example.staticMethod()`, is because this is the standard .Net syntax for accessing class vars/methods. I understand that this is not used by XBase++, but since it's standard .Net syntax, it is better to support it as well, as long as it does not interfere with anything else.

**Comment by DenGhostYY** [comment] 2023-04-21 11:59
We agree that this is problematic in Xbase++, but unfortunately there are many such expressions in our projects. It seems to us a good idea to try to emulate this behavior in the indicated way.

**Comment by DenGhostYY** [comment] 2023-04-24 02:47
What if you translate `o:Example:Name()` into `((Example)o):Name()`?

**Comment by RobertvanderHulst** [comment] 2023-04-24 07:49
> What if you translate `o:Example:Name()` into `((Example)o):Name()`?

That would probably work.  But it will be very difficult for the compiler to do that, since o is not declared with a type.

But the best result would be achieved if you start declaring types for your variables.
Without these types, the compiler will generate code that evaluates properties and methods at runtime (late bound).
So even when I generate the following code at compile time:

```
method DerivedExample:Example AS Example
    return super
```
Then the latebound code will generate the following code for this line:

`? o:Example:Name()`

`Send(IVarGet(o, "Example"), "Name")`

It does that because it does not know the type of `o`
The IVarGet() will return the SUPER for o, but that points to the same object as o.
And then the Send() code will call GetType() on the `o` object and will get the “Name” method declared at the DerivedExample level.

However, if you declare a type for o

` local o as DerivedExample`

Then no late bound code is needed and then it works like you expect
And you will also be rewarded with better performance and better compiler warnings/errors.

**Comment by DenGhostYY** [comment] 2023-04-24 09:24
For the transition from Xbase++ to XSharp, we need the compatibility of the constructs that are described in the XBase++ documentation. And then of course we will use typing.

**Comment by cpyrgas** [comment] 2023-06-12 09:50
Code in https://github.com/X-Sharp/XSharpPublic/issues/1215#issuecomment-1517280859 now compiles with no errors (with /vo1 and /lb enabled), but the output is:

```
         4
         5
DerivedExample
Example
```

(no matter the state of /vo3), while @DenGhostYY expects (as in xBase++):

```
         4
         5
DerivedExample
Example
```

**Comment by RobertvanderHulst** [comment] 2023-06-27 14:25
This will be VERY difficult to implement in untyped / latebound code without some major changes.

When calling:

`? o:Example:Name()`
the compiler first calls

`o:Example`

and this results in 

`NoIVarGet(o, "Example")`

The current generates a property that returns SELF/THIS as an object of type 'Example'.
But of course that object still IS an object of type `DerivedExample`, stored inside a USUAL
so for the next call to the Name() method we have a usual with an object of type `DerivedExample`
Looking for the method with the name `Name` we then get the method that is defined in the child class.

One solution would be that the Example property would return not the real DerivedExample object, 
but would somehow create a clone that is marked as `Example`. That would work if no properties of that object are updated, but I am sure people will also update the properties.

An alternative would be that we would create a new helper type that holds a value and a type, something like a 'WrappedValue' 
```
CLASS WrappedValue
     // Stores the value. This would still be the object of type DerivedExample
     PROPERTY Value as USUAL AUTO GET SET   
     // Stores the type. In this case that would be the typeof(Example)
     PROPERTY Type  AS System.Type GET SET    
END CLASS
```
And then in the late bound code in the runtime, we would have to add special handling for variables of the type WrappedValue. 
The  code would have to take the type from the Type property and not from the value.
And maybe there is already a type like this in the .Net Runtime. I am not sure, I would have to check.

This may also require other changes to the compiler. I am not sure yet.

**Comment by RobertvanderHulst** [comment] 2023-09-18 09:33
I am closing this issue. The remainder is handled in #1338

**Comment by cpyrgas** [comment] 2023-09-21 07:32
I am now getting the following runtime error when I run the code from https://github.com/X-Sharp/XSharpPublic/issues/1215#issuecomment-1517280859

```
Description :   Argument is NULL
Subsystem :     BASE
GenCode :       EG_ARG Argument error
FuncSym :       __InternalSend
Severity :      ES_ERROR
Can Default :   False
Can Retry :     False
Can Substitute :        False
Argument Number :       1
Argument :      oObject
Stack Trace :
   at XSharp.RT.OOPHelpers.DoSend(Object oObject, String cMethod, __Usual[] args, String cCaller)
   at XSharp.RT.Functions.__InternalSend(__Usual oObject, String cMethod, __Usual[] args)
   at xpp.Exe.Functions.Main(__Usual[] Xs$Args) in C:\VIDE\Projects\Project3\Applications\xpp\Prg\xpp.prg:line 5
   at xpp.Exe.Functions.Start(String[] Xs$Args)
```

**Comment by cpyrgas** [comment] 2023-09-28 15:50
Confirmed fixed

**Closed by cpyrgas** 2023-09-28 15:50 UTC
Labels: bug, Compiler, Xbase++
