### ISSUE TITLE
Passing a FLOAT to a function with e.g. a BYTE signature

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#951] opened 2022-02-04 09:34 UTC
I m wondering why this code compiles without a warning/error. Trying the same with VO results in: "Possibly dangerous automatic conversion ... 51458"

btw. none of the X# compiler options are set

		            
```
FUNCTION Start( ) AS VOID
LOCAL f := -1343.345 AS FLOAT  // "AS DOUBLE" throws an compile error

TestFloat ( f ) 

f := 12345673.89

TestFloat ( f ) 

RETURN


FUNCTION TestFloat ( n AS BYTE ) AS INT  
	? n   // shows 193 and 73
	RETURN 0
```

Karl-Heinz

**Comment by RobertvanderHulst** [comment] 2022-02-04 12:16
I am not sure what's happening here. Therefore I don't know if I have to call this a bug or an enhancement.

**Comment by cpyrgas** [comment] 2022-02-04 18:17
Hmmm, indeed something seems to have wrong regarding conversions. First of all, when /vo7 is enabled the following does not report errors or even warnings, even if /vo4 (implicit signed/unsigned convertions) is disabled:

```
// /vo7+  /vo4-
FUNCTION Start() AS VOID
LOCAL d := 0 AS DWORD
LOCAL i := 0 AS INT
d := i
i := d
```

I think in this case there should be an error, since /vo4 is disabled. If /vo4 is enabled, then correctly there's no error, but the problem is there's not a warning either, which I think was being reported in older compiler versions.


For other numeric data types the behavior seems inconsistent again, and most importantly it seems that again both /vo4 and /vo7 have the same effect on the compiler behavior in those conversions:

```
LOCAL r AS REAL4
LOCAL f AS FLOAT
LOCAL i AS INT
LOCAL d AS DWORD
LOCAL b AS BYTE

r := i // no warning/error, correct
f := i // no warning/error, correct
r := d // no warning/error, correct
f := b // no warning/error, correct

i := r // correct error XS0266: Cannot implicitly convert type 'real4' to 'int' when no options used, but no warning with /vo4 or /vo7
i := f // no error or warning at all, wrong!

b := r // error with no options, no warning with either /vo4+ or /vo7+
b := f // no error or warning at all, wrong!
b := i // error with no options, no warning with either /vo4+ or /vo7+
b := d // error with no options, no warning with either /vo4+ or /vo7+
```

So there's definitely a bug here, but please let's give this high priority, because it's a very "fragile" area in the compiler/runtime, right now it seems it's not causing problems to applications, it's only not preventing programmer errors as it should. Would be very nice to fix of course, but let's make absolutely sure that we do not break anything that does work correctly right now.

**Comment by RobertvanderHulst** [comment] 2022-02-18 16:10
The problem is not in the compiler but in the Runtime.
The conversion operators in the Float class (and also in the Currency class) convert without overflow checking.
I will add this to both numeric types.

**Comment by cpyrgas** [comment] 2022-02-18 21:30
Robert, this now makes the original code throw a runtime exception, which is indeed a lot better than giving "random" results, but the original problem remains, shouldn't the compiler report an error or warning on this code? Especially since no vo* compiler options are being used and since it does so with REAL8 instead of FLOAT?

Similarly the cases I reported in my previous notes are not affected by this change. Or did I miss a compile change, too?

**Comment by RobertvanderHulst** [comment] 2022-02-18 21:44
The compiler can't report an error because the code will sometimes run (when the values are in the correct range) and sometimes will fail.

**Comment by cpyrgas** [comment] 2022-02-18 21:51
> The compiler can't report an error because the code will sometimes run (when the values are in the correct range) and sometimes will fail.

Robert, when a REAL8 is used instead of a FLOAT, the compiler reports error XS1503: Argument 1: cannot convert from 'real8' to 'byte'. Also when REAL4 is passed to the function accepting a BYTE, a similar error is reported. Only with FLOAT no error or warning is being reported.

**Comment by RobertvanderHulst** [comment] 2022-02-18 22:29
I'll look into this. Most likely we are giving the float type a "special treatment" in the compiler.

**Comment by cpyrgas** [comment] 2022-02-18 22:36
I thought something along those lines. Just to be clear, not pressuring you at all to fix/improve any of the above, especially since they're in a fragile area and can cause side effects! Just wanted to make sure the related issues are clear.

**Comment by cpyrgas** [comment] 2022-02-19 09:54
Just another note, the above changes to the runtime have now resulted to conversions from float/currency to integer types to ALWAYS throw an exception when an overflow happens, no matter if the /ovf /fovf compiler options are passed as disabled to the compiler in the main app. But from what I see, VO does that, too (a float to int overflow always throws an error, even if overflow checking is disabled, and it probably makes sense in this case), so I think we are good.

**Comment by RobertvanderHulst** [comment] 2022-02-21 16:57
Chris,
The difference in the code 👍🏼 
```
LOCAL r AS REAL4
LOCAL f AS FLOAT
LOCAL i AS INT
LOCAL d AS DWORD
LOCAL b AS BYTE

b := r // error with no options, no warning with either /vo4+ or /vo7+
b := f // no error or warning at all, wrong!
b := i // error with no options, no warning with either /vo4+ or /vo7+
b := d // error with no options, no warning with either /vo4+ or /vo7+
```

Is caused by this:
the standard .Net built-in types do not have implicit type conversion operators. The conversions between the types are handled at the IL level. Roslyn has a built-in table that tells the compiler which IL instruction to generate for the conversion.
We are controlling the display of conversion warnings with the /vo4 and /vo7 compiler options.

The Float type is not a built-in framework type. To make the use of the float type easier we have added converters into the type from float to the various numeric framework types and back. These converters are EXPLICIT (the framework requires that).
I will see if I can make the "automatic" conversion from Float to the built-in types also dependent on the /vo4 and /vo11 options. I do not thing /vo7 has anything to do with this.

**Comment by cpyrgas** [comment] 2022-02-21 17:26
Robert, it does, because if you keep /vo4 always disabled and then test first with /vo7 enabled and then disabled, you will get different results (compiler errors). I agree it shouldn't though.

As I pointed out above, /vo7+ also has an effect even on this. Keep /vo4 disabled again and try with and without /vo7:

```
// /vo4 always off, try with /vo7+ and /vo7-
FUNCTION Start() AS VOID
LOCAL d := 0 AS DWORD
LOCAL i := 0 AS INT
d := i
i := d
```

you will get 2 errors if vo7 is disabled and no errors if it is disabled (having vo4 disabled in both cases)

**Comment by RobertvanderHulst** [comment] 2022-02-22 10:26
Chris,
you are right of course. This was not intentional but I will leave it the way it is. 
I have changed the compiler now and when you assign or pass an argument of type Float and Currency these now follow the same rules as the built-in types. So they depend on the /vo4 and /vo11 settings.
As a result 1 of the existing test cases now either require a cast or the compiler option:
C188 : Here a float is passed to a function that expects a REAL4
I will create a new compiler and will send you the download info.

**Comment by RobertvanderHulst** [comment] 2022-02-22 10:43
One more thing:
C402 now also needs vo4 or vo11:

```
FUNCTION Start() AS VOID
LOCAL nPaperLength AS INT
LOCAL nDevicePixelsPerInchY := 10 AS INT
LOCAL AbsHeight := 1234.5 AS USUAL
nPaperLength := AbsHeight/FLOAT(nDevicePixelsPerInchY)
? nPaperLength
IF nPaperLength != 123
	THROW Exception{"Incorrect result"}
END IF
```
The result of AbsHeight/Float(..) is a FLOAT and when this gets assigned to the int nPaperLength a cast is needed or one of the compiler options

**Comment by cpyrgas** [comment] 2022-02-22 11:48
Robert, makes sense, but why should /vo4 have an effect on this? I mean /vo4 is about signed/unsigned conversions, so I would expect it to only have an effect on word/int conversions, not on anything that has to do with decimal point operations. If you mean that this also is not intended, but better not touch it in the fear of breaking something else, I completely understand and agree.

Also is the new FLOAT<->REAL8 behavior intended, or was it a side effect of the FLOAT->BYTE fix? I would expect that there would be no compiler option needed to convert between those two. Especially from REAL8 -> FLOAT, as for FLOAT -> REAL8 indeed you could argue that the floating point extra info will be lost.

**Comment by RobertvanderHulst** [comment] 2022-02-22 11:52
Chris,
You are right about /vo4. But I am afraid of side effects when I correct this.

**Comment by cpyrgas** [comment] 2022-02-22 16:26
Robert, something must have gone wrong, because I still get no compiler errors for the original sample (I still get errors only if I use REAL8 instead of FLOAT)

**Comment by cpyrgas** [comment] 2022-02-23 09:24
Original code still does not produce a warning or error. Also there's a new issue:

```
// /vo4+
FUNCTION Start( ) AS VOID
	LOCAL n := 1 AS INT
	LOCAL f := 3.0 AS FLOAT
	
	n := f // OK
	n := n + f // OK
	n += f     // error XS0266: Cannot implicitly convert type 'FLOAT' to 'int'
```

**Comment by cpyrgas** [comment] 2022-03-01 19:40
Problem mostly fixed, but there's still an inconsistency: In the following, the first two lines produce a warning as expected (with /vo11 enabled), but the third one does not.

I know, this might feel like nitpicking too much :), in which case please do close the ticket.

```
/vo11+
FUNCTION Start( ) AS VOID
	LOCAL n := 1 AS INT
	LOCAL f := 3.0 AS FLOAT
	
	n := f // warning XS9020: Narrowing conversion from 'float' to 'int' may lead to loss of data or overflow errors
	n := n + f // warning XS9020: Narrowing conversion from 'float' to 'int' may lead to loss of data or overflow errors
	n += f     // no warning
```

**Comment by cpyrgas** [comment] 2022-03-07 09:00
Looks good, only thing remaining is the inconsistency with /vo4. When I compile the following with no compiler options, I get two "error XS0266: Cannot implicitly convert type 'float/real8' to 'int'", which is OK. 

But when I compile with /vo4+ and no other vo options, then I still get an error for the REAL8 assignment, but no error and not even a warning for the FLOAT assignment. I think the correct behavior would be to report on error for both lines.

When I compile with /vo11+ enabled (no matter the state of /vo4), I get for both lines a Narrowing conversion warning, which is good.

```
// /vo4+
FUNCTION Start( ) AS VOID
LOCAL n := 1 AS INT
LOCAL r := 3.0 AS REAL8
LOCAL f := 3.0 AS FLOAT
n := r // error XS0266: Cannot implicitly convert type 'real8' to 'int'.
n := f // no warning or error
```

Robert, I know you said this is a very complex area, which is better left be alone for now and I agree. But since this is still an inconsistency, should I log a new ticket for it (and maybe look into it sometime in the future) and close this one?

**Comment by RobertvanderHulst** [comment] 2022-03-07 10:30
Chris,
Yes, please create a new ticket and close this one.

**Comment by cpyrgas** [comment] 2022-03-07 13:16
Confirmed fixed!

**Closed by cpyrgas** 2022-03-07 13:16 UTC
Labels: bug, enhancement, Runtime
