### ISSUE TITLE
VS Intellisense problem with VAR and collections

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#367] opened 2020-04-24 11:42 UTC
In the following, when typing "o:", intellisense show the members of "List", not of "INT"

```
USING System.Collections.Generic
FUNCTION Start() AS VOID STRICT
	LOCAL a AS List<INT>
	VAR o := a[1]
	o:
```

**Comment by RobertvanderHulst** [comment] 2020-05-02 14:53
Duplicate of #35

**Closed** 2020-06-08 12:28 UTC
Labels: bug, vs editor
