### ISSUE TITLE
Сlass methods are not inherited (Xbase++ dialect)

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1349] opened 2023-09-18 05:16 UTC
**Describe the bug**
Сlass methods of parent class are not visible in child.

**To Reproduce**
```
procedure Main()
    ? Child():ClassMethod()
    wait
return

class Child from Parent
endclass

class Parent
exported:
    inline class method ClassMethod()
    return "ParentClassMethod"
endclass
```

**Expected behavior (XBase++ exe)**
Output
```
ParentClassMethod
```

**Actual behavior (X# exe)**
Runtime error
```
XSharp.Error
  HResult=0x80131500
  Message = No exported method
  Source = XSharp.XPP
  Stack trace:
   в XSharp.XPP.StaticClassObject.NoMethod(__Usual[] Xs$Args)
   в XSharp.RT.OOPHelpers.DoSend(Object oObject, String cMethod, __Usual[] args, String cCaller)
   в XSharp.RT.Functions.__InternalSend(__Usual oObject, String cMethod, __Usual[] args)
   в XSharpConsole.Exe.Functions.Main(__Usual[] Xs$Args) в F:\X#\XSharpConsole\XSharpConsole\Program.prg:line 11
   в XSharpConsole.Exe.Functions.Start(String[] Xs$Args)
```

**Additional context**
X# Compiler version 2.17.0.3 (release)
-dialect:xBase++ -lb -memvar -enforceself -xpp1 -vo1 -vo3 -vo5 -vo10 -vo15 -vo16

**Comment by RobertvanderHulst** [comment] 2023-09-18 07:55
Confirmed. Fixed in next build.

**Comment by RobertvanderHulst** [comment] 2023-09-18 08:04
To work around this, you can call the method on the class like this
`Child.ClassMethod()`

iow

`Type.MethodName()`

This is also "better" because the call is direct and bypasses late binding.

**Comment by cpyrgas** [comment] 2023-09-27 20:06
Confirmed fixed

**Closed by cpyrgas** 2023-09-27 20:06 UTC
Labels: bug, Runtime, Xbase++
