### ISSUE TITLE
Issues in code folding and formatting

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#975] opened 2022-02-24 07:14 UTC
In the attached example there are a few problems with code folding and formatting. There are comments everywhere describing the problem.
[TestApplication.zip](https://github.com/X-Sharp/XSharpPublic/files/8130388/TestApplication.zip)

**Comment by cpyrgas** [comment] 2022-04-28 16:04
I'm seeing some very strange indentation behavior with this test app, but maybe it's because my settings are incorrect.
@hpetriffer , what are you using for tab/indent size and style (tab/spaces)?

**Comment by hpetriffer** [comment] 2022-04-29 05:24
I have tested it again. With this setting the most parts are like in the description. One problem which is not described in the files, seems to be that the all the "do case" statements have a problem with the identation 
![image](https://user-images.githubusercontent.com/20905638/165888674-29064843-f5d3-49c9-af4e-81ffcae8bebe.png)
![image](https://user-images.githubusercontent.com/20905638/165888706-fd4d2bf6-a268-49c6-b2d6-603493071afc.png)
![image](https://user-images.githubusercontent.com/20905638/165888750-90f022fb-cab5-4514-8216-85e65c5ffe72.png)

**Comment by cpyrgas** [comment] 2022-04-29 15:20
Robert, most of the original problems are fixed now, except this code:

```
FUNCTION Test() 
	WHILE FALSE
		IF FALSE
		ENDIF
	END

	IF FALSE
	END
	
	DO WHILE TRUE
		IF TRUE
		ENDIF
	ENDDO
	
	DO CASE
	CASE FALSE
	END
	
	IF FALSE
	ENDIF
```

which results to missing collapse markers:

![VS_editor_END](https://user-images.githubusercontent.com/14542129/165974237-b71f4dc0-abb9-4994-b38b-56550e7109f6.png)

Looks like the problem is the usage of a single "END" instead of "END IF", "ENDIF", "END CASE" etc.

**Comment by RobertvanderHulst** [comment] 2022-05-01 17:01
Chris,
I saw this too and fixed it in 0785f48d9b8561d605aaf3736f2570c842a4d0a2
When I create a new installer you can check this.
Robert

**Comment by hpetriffer** [comment] 2022-05-02 05:25
> Thanks, the problem was that the existing indentation in the code was using 3 spaces in some of the prgs, but after I did a format document, then most of the problems went away. About the DO CASE, your current settings do not indent either "CASE" below "DO CASE", neither any code below "CASE", maybe this is why you see it not working correctly? I assume you'd prefer to enable at least one of the two options "Indent case content" or "Indent case label"

yes you are right...Thanks

**Comment by cpyrgas** [comment] 2022-05-12 09:04
Well, this is possibly absolute nitpicking, but when there are no empty lines between case and the next statements, collapse markers still do not appear. For example

```
DO CASE

CASE TRUE // no box
CASE 0==1 // only this one shows a collapse box

CASE 1==2 // no box
CASE FALSE // no box
END CASE
```

As I said it's probably nitpicking though, so feel free to close this if you wish.

Also DO WHILE contents still do not indent with Format Document, but this is also mentioned in https://github.com/X-Sharp/XSharpPublic/issues/923.

**Comment by RobertvanderHulst** [comment] 2022-07-04 12:42
Please retest with 2.13

**Closed** 2022-07-29 07:25 UTC
Labels: bug, vs editor

**Comment by cpyrgas** [comment] 2022-07-29 11:33
Confirmed fixed
