### ISSUE TITLE
CompilerError XS7038: Failed to emit module ...: Unable to determine specific cause of the failure.

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#736] opened 2021-07-19 14:59 UTC
When I write the following code, I'll get the compiler error `XS7038: Failed to emit module 'XsCsInteropTests': Unable to determine specific cause of the failure.`

      var aArray := array of int {5} { 1, 2, 3, 4, 5 }
      var aLen := ALen(Aarray)

      if aLen == 0
      endif 

The error is caused by the invalid variable name aLen, which is also a function name. But it was tricky to identify the location of the error, because the error message is very generic and the line number doesn't indicate the cause of the error.

**Comment by RobertvanderHulst** [comment] 2021-07-19 17:56
The problem seems to be that when resolving the type of aLen the compiler sees another symbol ALen() and thinks that this is a delegate or something like that. It then enters an infinate loop and gives up after a while
If you had compiled in case sensitive mode (like C# does) and made sure that aArray was spelled equal in the first 2 lines then the error would not have occurred.

I'll fix this to avoid this in the future.

**Comment by cpyrgas** [comment] 2021-09-05 07:55
Confirmed fixed

**Closed by cpyrgas** 2021-09-05 07:55 UTC
Labels: bug, Compiler
