### ISSUE TITLE
In some situations, information about the actual exception is lost.

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#883] opened 2021-12-09 12:46 UTC
The following example demonstrates a situation where the caller does not receive information about a valid exception. It's not even in InnerException.

```
FUNCTION Start() AS VOID STRICT

	LOCAL xError AS USUAL

	BEGIN SEQUENCE
		_CallClipFunc(#SomeFunc, {})
	RECOVER USING xError
		IF ( xError IS Error VAR oError )
			? oError:Description // XSharp.Internal.WrappedException without InvalidOperationException{ "Some exception." }
		ENDIF
	END SEQUENCE

	RETURN

FUNCTION SomeFunc() AS VOID STRICT

	LOCAL xError AS USUAL
	
	BEGIN SEQUENCE
		THROW InvalidOperationException{ "Some exception." }
	RECOVER USING xError
	END SEQUENCE

	IF ( xError IS Error .AND. CanBreak() )
		BREAK xError
	ENDIF

	RETURN
```

It looks like this happens when using the _CallClipFunc function. If you call the SomeFunc function directly, then the actual exception is not lost.

**Comment by RobertvanderHulst** [comment] 2021-12-09 13:09
The exception that you created inside the BEGIN SEQUENCE .. END is wrapped as the value inside in a WrappedException class
You will see that when you add the following code to the RECOVER USING clause in the Start funciton:

```
        if (xError is Exception var ex .and. ex:InnerException IS XSharp.Internal.WrappedException VAR wrapped)
            IF wrapped:Value IS Error VAR oError
                ? oError:Description
            ENDIF
```

We are looking into our implementation of BEGIN SEQUENCE .. END at this moment because of feedback in ticket #881 as well.

**Comment by RobertvanderHulst** [comment] 2021-12-09 13:11
The biggest question in the other ticket is if THROW InvalidOperationException{ "Some exception." } inside SomeFunc should goto the RECOVER clause, or if this should abort the begin sequence .. end sequence  (and maybe call the error handler that is installed with ErrorBlock())

**Comment by leon-ts** [comment] 2021-12-09 13:26
Robert,
All exception destinations now work correctly, including calling THROW inside BEGIN SEQUENCE ... END. The only problem is the wrappers. I already wrote in another ticket that, in my opinion, these wrappers do not carry any useful information and only confuse error analysis.

**Comment by leon-ts** [comment] 2021-12-09 13:55
Robert,
My colleagues and I like the current behavior of X# when throwing exceptions. It follows the NET concept - if an exception is thrown, the entire operation must be aborted and control must be transferred to the closest CATCH (RECOVER). In VO, this was often a problem: when an error occurred, the control remained on the problem line and the user was offered options for action, where one of the solutions was to press the "Ignore" button. As a result, the execution of the problematic code continued, which subsequently led to even greater problems (up to the loss or corruption of data in the database).
At this point, we have already adapted a lot of our X# code (transported from VO) to the NET concept of exceptions. And this code is already in production.

**Comment by RobertvanderHulst** [comment] 2021-12-09 14:27
Leonid,
You can be assured that if we change something in this area, then that change will be controllable with a compiler switch and the default value for that switch will be that the code stays the same as it is at this moment.

**Comment by RobertvanderHulst** [comment] 2022-01-17 09:17
See https://github.com/X-Sharp/XSharpPublic/issues/916 for a proposed solution

**Comment by cpyrgas** [comment] 2022-02-08 12:05
Robert, still now, in order to intercept the actual exception (thrown by BREAK in SomeFunc()) inside the RECOVER in Start(), we need to analyze the xError var and read the xError:InnerException:Value to get what really happened. This is very different to VO, in which xError gets the actual exception, so this means existing code (ported from VO) needs to be modified.

Can we do something about this? Not sure myself, I need to study more closely the WrappedException mechanism. Or did I miss something maybe?

**Comment by RobertvanderHulst** [comment] 2022-02-09 22:37
BREAK is not meant (at least not at this moment) to send an exception to the RECOVER clause but to send a Value.
BREAK stores the value in a WrappedException object.

If you want to send an Exception to the RECOVER you should use the THROW keyword.

Now (in theory) we could change the code behind the BREAK keyword to only wrap the value inside a WrappedException object when the value is not an Exception. And otherwise simply throw the exception itself
The code generated for a BREAK statement would then become

```
BREAK uValue =>THROW iif (uValue is Exception, uValue, WrappedException{uValue} )

```
That would probably work and have the effect that you ask for.
What do you think of that ?

**Comment by cpyrgas** [comment] 2022-02-10 01:06
Robert,
Well, it's not what I ask for, I'm just looking for a way to make code ported directly from VO to work the same way in X# without needing to modify it. But I think I have not understood well how BREAK and RECOVER works in VO, in my VO programs I have only used very basic BEGIN SEQUENCE constructs. Let me do some proper research and I will comment back.

**Comment by cpyrgas** [comment] 2022-02-10 12:38
Robert, OK, I had a closer look and I think VO is a total mess (also) in this area. I think in this particular ticker, @leon-ts is pointing out the inconsistency with BREAK not sending the error back on level, so I experimented with this code:


```
FUNCTION Start() AS VOID STRICT
	LOCAL xError AS USUAL
	
	LOCAL untyped AS USUAL
	LOCAL typed AS Tester
	
	typed := Tester{}
	untyped := typed
	
	? "calling late bound"
	BEGIN SEQUENCE
		untyped:Test()
	RECOVER USING xError
		? xError:Description
	END SEQUENCE
	
	? "----------------"
	? "calling early bound"
	BEGIN SEQUENCE
		typed:Test()
	RECOVER USING xError
		? "Description back to caller:", xError:Description
	END SEQUENCE

	RETURN

CLASS Tester
	METHOD Test()
		LOCAL xError AS USUAL
		LOCAL uUsual := 123 AS USUAL
		BEGIN SEQUENCE
			uUsual:Nothing()
		RECOVER USING xError
			? "Description inside method:", xError:Description
		END SEQUENCE
	
		BREAK xError
	RETURN NIL
END CLASS
```

Currently X# is inconsistent, depending on if the call is being done late bound (in which case the RECOVER block in Start() receives a WrppedException and we need to read the Value property for the message), or if it is being done early bound (in which case it receives an XSharp.Error, which gives directly the exception message). Also X# does not produce a "Retry, Ignore, Cancel" error dialog in any case).

When running the same code in VO, it displays the error dialog in both cases. And in both cases, when you click on "Ignore", the caller block receives NIL, while if you select "Cancel", then it returns an Error object with an EMPTY description!

So right now X# is very incompatible in this case to VO, but then again VO's behavior doesn't make much sense to me, so I think there's no point trying to emulate it. 


It probably wouldn't hurt to do as you suggest though Robert with BREAK => THROW, so BREAK can be better used in X# as Leonid suggests. But this needs to work for both typed and untyped nested calls. Because I tried with this simplified code which BREAKs with a simple literal value:

```
FUNCTION Start() AS VOID STRICT
	LOCAL xError AS USUAL
	
	LOCAL untyped AS USUAL
	LOCAL typed AS Tester
	
	typed := Tester{}
	untyped := typed
	
	BEGIN SEQUENCE
		untyped:Test()
	RECOVER USING xError
		? "Value returned back to late bound call:", xError
	END SEQUENCE

	BEGIN SEQUENCE
		typed:Test()
	RECOVER USING xError
		? "Value returned back to early bound call:", xError
	END SEQUENCE

CLASS Tester
	METHOD Test()
		BREAK 555
	RETURN NIL
END CLASS
```

and again I get different results, an Error object for the late bound call and a literal 555 for the early bound call. Do you both agree that the literal should be assigned to the RECOVER variable in both cases? If yes, I will add a test like that.

**Comment by cpyrgas** [comment] 2022-04-13 09:41
Confirmed fixed

**Closed by cpyrgas** 2022-04-13 09:41 UTC
Labels: bug, Runtime
