### ISSUE TITLE
Sometimes incomplete or mismatching code generated by VO Windows Editor X# 2.7 and VS 2019

### ISSUE THREAD

**Issue by ArneOrtlinghaus** [X-Sharp/XSharpPublic#553] opened 2021-01-08 08:35 UTC
[IOSMSGW.zip](https://github.com/X-Sharp/XSharpPublic/files/5786024/IOSMSGW.zip)
When using the VO Windows Editor on existing windows I had mismatching information between generated X#-Class code and the RC files. Also I had error messages that vanished only when making further changes in the VO Windows Editor. 

- Please extract the attached solution IOSMSGW. It will not compile, but this is secondary. 
- Go under tabMsgProjektverwaltung_vo.prg, select "View Code"
- Delete the complete code and save and close the file
- Open the file tabMsgProjektverwaltung_vo.xsfrm with the VO Windows Editor
- Make a small change (move a control) and save the changes. 
- Go under tabMsgProjektverwaltung_vo.prg, select "View Code" and copy the code to an external editor without changing the VS-Editor File contents
- - Open the file tabMsgProjektverwaltung_vo.xsfrm with the VO Windows Editor
- Make a small change (move a control) and save the changes. 
- Go under tabMsgProjektverwaltung_vo.prg, select "View Code" and copy the code to an external editor 
- When comparing the two files in the external editor, there should be significant differences. Especially what should miss in the first file is the line with the constant STATIC DEFINE TABMSGPROJEKTVERWALTUNG_VO_TXTSLEPRJKODE := 100

I could not reproduce more complex situations when adding controls to existing windows. It seemed that in some cases the resource constants can differ between VO-Code and resource.

**Comment by cpyrgas** [comment] 2021-01-08 09:14
Arne, when I follow your instructions 1:1, the two code files I get are completely identical. Maybe you meant I should copy the contents of the editor in the first time BEFORE I make the first change to the window? Can you please attach your two versions of the result files, so I can see exactly what you mean?

**Comment by cpyrgas** [comment] 2021-01-08 09:28
Oh, please forget the above, I can reproduce it now. Not sure what I did wrong before. Looking into this and will get back to you...

**Comment by ArneOrtlinghaus** [comment] 2021-01-08 09:33
Hi Chris,

I wish you a good new year!

For me this case is always reproduceable. I tried several times. I have the two files attached.


  *   In reality I made changes to exactly that window and when opening the program the captions of the buttons were mixed as if the constants were not the same (first I did not understand what happened).


  *   I cloned the original window and made a small changed and compiled. What happened was that the program did not compile because of the missing constant. I made another small change and the compiler error vanished.



  *   Now I tried to find a reproduceable case and it was this case. It does not seem to happen always and in every window and it seems to depend on the source already generated. So the impression is that there is an “intelligent” source code generator looking for changes to make instead of generating always the complete code and that this source code generator sometimes does not find the correct changes.


Arne

Dipl. Phys. Arne Ortlinghaus
Softwareentwicklung - Sviluppo Software
T +39 0472 057 700
arne.ortlinghaus@infominds.eu

**Comment by cpyrgas** [comment] 2021-01-08 09:40
Happy new year Arne!

I see when the problem happens and why I could not reproduce it the first time. Seems to be a problem with handling the VS editor contents, when the prg is completely empty. When you delete all the code from the file, press <Enter> a couple times to leave an additional empty line in the .prg. Now make a save in the window as you described, the contents will be correct now (the first define is not missing). Will check if this is something that needs to be fixed in the VOWED code generation or in the VS part of handling things.

**Comment by ArneOrtlinghaus** [comment] 2021-01-08 09:44
Hi Chris,

it is not a problem to work around the case I sent you.

It was more problematic to have wrong execution code once after having made some changes. Will I always be able to immediately see that something went wrong and to regenerate the code by making a small change?

I believe when fixing the case I sent you there is a good probability to fix also the other case that is not so easy to reproduce.

Arne

**Comment by cpyrgas** [comment] 2021-01-08 09:49
Hi Arne,

In this particular problem you reported, the only issue is that the first line of generated code (in this case a DEFINE) is omitted (when the file is completely empty) and apart from that, all the generated code is correct. The fix to this problem will only make sure that this first line is included in the code generation as well.

The other problem you mention sounds completely different. Even if you can't reproduce it reliably, when it does happen, can you send me the prg files in the before and after state to have a look? By comparing the contents, maybe it will give an idea about it as well...

**Comment by cpyrgas** [comment] 2021-01-08 15:22
Problem with missing define in generated code is fixed. Arne, when you have some more info/repro sample for the other problem with mismatching data in prg/rc, please do report this as well.

**Closed by cpyrgas** 2021-01-08 15:22 UTC
Labels: VO, bug, vs form editor
