### ISSUE TITLE
USE command fails with AGAIN clause (VFP)

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#235] opened 2019-10-18 21:03 UTC
In FoxPro there is the AGAIN clause if you wish create a second work area using the same DBF with a different Alias name.

In X#.VFP this AGAIN clauses causes error.

Perhaps AGAIN is not needed in X#, but it will be present in some VFP code, so need to deal with it in the compiler somehow.

```
Select 0
Use (oObject:cDbfName) Alias WA1 Shared
Select 0
Use (oObject:cDbfName) Again Alias WA2 Shared
```

**Comment by lazy-fox** [comment] 2020-03-09 13:29
Seconding Matt again. Probably most used syntax for use in vfp is
use (lcTable) ;   && might not be in varable, but literal
alias (lcAlias) ;    && might not be in varable, but literal
in  [0, Select(lcAlias)] ; && open new work area or open in work area currently used by lcAlias
again ; && does not hurt if table not already open
shared/exclusive && depending on need

**Comment by kevclark64** [comment] 2021-10-20 19:27
I notice that AGAIN still causes a compiler error.  Is that something that will be fixed, or is AGAIN not necessary in X# due to the way it handles files?

**Comment by cpyrgas** [comment] 2021-10-21 07:50
It will be fixed. Even in case that it is not necessary, it should still be accepted by the compiler/preprocessor and not throw an error. Will be done eventually, it's just the 24 hours in a day problem..

**Comment by cpyrgas** [comment] 2024-04-25 16:41
Confirmed fixed

**Closed by cpyrgas** 2024-04-25 16:41 UTC
Labels: Runtime, RDD, FoxPro, UDC, Preprocessor
