### ISSUE TITLE
VS 2022 and XS 2.13.1.1 First builds not starting together with Nuget usage

### ISSUE THREAD

**Issue by ArneOrtlinghaus** [X-Sharp/XSharpPublic#1113] opened 2022-09-08 08:51 UTC
**Describe the bug**
The first build does not start. It is necessary to try to leave VS. When the message about "build must be cancelled" appears, the build starts normally. 
This happens when Nuget Package Manager options "Allow Nuget to download missing packages and automatically check for missing packages during build in Visual Studio" are enabled. 

**To Reproduce**
Solution ACSLIB has been sent to Robert. 

**Expected behavior**
Same as with X#-Version from June: normal starting of the build. 

**Screenshots**
See attached file. 

**Additional context**
[RE VS 2022 and XS 2.13.1.1 First builds not starting.zip](https://github.com/X-Sharp/XSharpPublic/files/9525263/RE.VS.2022.and.XS.2.13.1.1.First.builds.not.starting.zip)

**Comment by RobertvanderHulst** [comment] 2022-09-08 10:47
Ok, I have found the problem.

The origin of the problem is in the VS extension for NuGet. One of the things this extension does is to add the menu option "Convert Packages.Config to PackageReferences" to files items with the name "packages.config"
The extension is hard coded to only support certain project types. The project type is determined by asking the project system for its Guid. Our Guid is "{aa6c8d78-22ff-423a-9c7c-5f2393824e04}". When the extension sees this Guid it reports that the wizard to convert the packages.config to packagereferences cannot run because the project type is not supported, even though we have implemented all the necessary plumbing in our project system.

We have reported this through the feedback feature in VS but (guess what) this has not been resolved yet (it is "under consideration"): https://developercommunity.visualstudio.com/t/The-Nuget-upgrade-utility-for-packagesc/10124742
Maybe you can add a thumbs up here too ?

Anyway, to work around this we are trying to detect that the ProjectGuid is retrieved from Nuget and then we "cheat" and return the Guid for the C# project system ( "{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}"). 
That seems to be enough because after that change the dialog to convert the packages.config to package references open and allows you to do the conversion.

What you have discovered now is that during the "restore nuget packages" phase in the build process inside VS, Nuget also queries for the ProjectGuid, and when we return the C# guid then it slows down a lot. Apparently it expects certain things then that we do not deliver.

I will make sure now that we will only fake the guid when requested from code that is run from the ContextMenu for a packages.config file. In all other cases I will return our own guid.
After that change the build will return just as fast (or just as slow) as before.

Btw: With the old and new project system there is a significant slowdown when building or cleaning the C# projects "IM.XsLib.Logging", "IM.XsLib.SqlAdoNet" and  "IM.XsLib.SqlAdoNet.Tests". 
Maybe you have an explanation for this ?

**Comment by RobertvanderHulst** [comment] 2022-09-08 11:17
This fix is included in the 2.13.2.0 installer that will be released later today

**Comment by hpetriffer** [comment] 2022-09-08 12:04
In our builds, so far, we have not seen C# projects take long to build. How did you see that?

**Comment by hpetriffer** [comment] 2022-09-08 12:31
This does not happen in our build environment

**Comment by RobertvanderHulst** [comment] 2022-09-08 12:46
> This does not happen in our build environment

Ok, no problem then.

**Comment by VolkmarR** [comment] 2022-09-08 13:19
I tested the new Beta Version 2.13.2 with our AcsLib solution. The problem is not fixed.

**Closed** 2022-09-14 06:25 UTC
Labels: MsBuild
