### ISSUE TITLE
Runtime error in XSharp.VORDDClasses.dll

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#435] opened 2020-07-08 08:48 UTC
Today I have received the following exception in the XSharp.VORDDClasses.dll:
Das Objekt des Typs "XSharp.__Float" kann nicht in Typ "System.Int32[]" umgewandelt werden.
in Void set_Item(Int32, XSharp.__Usual)
Stacktrace:   bei XSharp.__Usual.set_Item(Int32 index, __Usual value)
   bei XSharp.__ArrayBase`1.set_Item(Int32 index, Int32 index2, __Usual value)
   bei XSharp.VO.SDK.DbServer.__InitRecordBuf() in C:\XSharp\DevRt\Runtime\VOSdkTyped\Source\VOSdk\RDD_Classes_SDK\DBServer.prg:Zeile 281.
   bei XSharp.VO.SDK.DbServer..ctor(FileSpec oFS, Object lShareMode, Object lReadOnlyMode, String xDriver, __Array aRdd) in C:\XSharp\DevRt\Runtime\VOSdkTyped\Source\VOSdk\RDD_Classes_SDK\DBServer.prg:Zeile 749.

**Comment by cpyrgas** [comment] 2020-07-08 10:20
Wolfgang, can you please provide some more information? With which dbf did this happen? Is it always reproducible, or did it happen only once? Anything particular about this istuation, which could help us to reproduce the problem?

**Comment by wriedmann** [comment] 2020-07-08 11:04
until now it happened only once, and since it occurred in a Windows service, I have no more informations.
Maybe I can take the DBF and read it entirely to check it out.

**Comment by cpyrgas** [comment] 2020-07-08 12:28
But do you know which is the exact dbf that caused this? Any info about it, what is its structure, its data?

**Comment by cpyrgas** [comment] 2020-07-09 11:02
Problem had happened with the 2.3 build. Cannot reproduce it or see something int he code that might be causing it, maybe it was related to something else that was fixed since then,

**Comment by cpyrgas** [comment] 2020-07-09 13:38
Closed as requested by Wolfgang. In case it happens again in the future, with a newer build, please let us know!

**Closed by cpyrgas** 2020-07-09 13:38 UTC
Labels: Runtime, bug
