### ISSUE TITLE
Incompatible behavior when declaring global MEMVAR

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1144] opened 2022-09-26 14:47 UTC
In the new version of X# 2.13.2.2, the behavior when declaring PUBLIC memvar has changed: forced value initialization has been added (value type is not important in this case). The difference is shown below.

**Dialect:** VO

**Example:**
```
FUNCTION Func1()
	
	PUBLIC test_value
	IF Empty(test_value)
		test_value := 1
	ENDIF

	RETURN NIL

FUNCTION Func2()

	PUBLIC test_value
	IF Empty(test_value)
		test_value := 2
	ENDIF

	RETURN NIL
```

**IL (old X# 2.9.1.1, external behavior corresponds to VO):**
```
XSharp.RT.Functions.__MemVarDecl("test_value", _priv: false);
...
```

**IL (new X# 2.3.2.2):**
```
XSharp.RT.Functions.__MemVarDecl("test_value", _priv: false);
XSharp.RT.Functions.__MemVarPut("test_value", false);
...
```

As you can see from the example, the new version of X# has a new line that always initializes memvar to FALSE. This leads to the fact that when calling the functions Func1 and Func2 sequentially (the order is not important), memvar does not retain its value and is always reinitialized. This behavior does not match either VO or earlier versions of X# (eg 2.9.1.1) and breaks legacy VO code.

**Comment by Serggio** [comment] 2022-09-30 13:14
I've got the patch where the problem is fixed, but I'll let Leonid close the issue.

**Comment by cpyrgas** [comment] 2022-11-01 09:01
Confirmed fixed

**Closed by cpyrgas** 2022-11-01 09:01 UTC
Labels: bug, Compiler
