### ISSUE TITLE
Ctrl + Space (complete Word) adds Text instead of replacing the current word

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1256] opened 2023-05-12 13:04 UTC
In the following source:
```
class Test
	public method GridView_CustomSummaryCalculate(sender as Tes) as void
		return
			
end class
```

- Go with the cursor after "Tes"
- Press Ctrl+Space (complete word)
- Select the only entry Test

Now you get the following code: 
![image](https://github.com/X-Sharp/XSharpPublic/assets/20905638/3b748ef7-e451-469b-a5f0-1905f60a0ccf)

**Comment by RobertvanderHulst** [comment] 2023-05-31 13:00
I cannot reproduce that here. 
Which version of VS?
How are you "selecting" the entry from the list? Tab key, Enter Key, Mouse, Something else ?

**Comment by hpetriffer** [comment] 2023-05-31 13:19
Hansjoerg Petriffer ***@***.***) hat Ihnen eine geschützte Nachricht gesendet.
                                          Nachricht lesen            Weitere Informationen zu durch Microsoft Purview-Nachrichtenverschlüsselung geschützten Nachrichten.        
    
    
    
        
           Datenschutzbestimmungen        
    
    
        
              Weitere Informationen bei der E-Mail-Verschlüsselung.             Microsoft Corporation. One Microsoft Way, Redmond, WA 98052

**Comment by hpetriffer** [comment] 2023-05-31 13:30
At the moment on my pc CTRL+Space seems to not work anymore. On Volkmar PC it is working in the same way as described in the bug here (same Version of VS 17.6.2 and the newes X# version)

To select the entry with CTRL+Space we use the keyboard

[XSharpTests.zip](https://github.com/X-Sharp/XSharpPublic/files/11614608/XSharpTests.zip)

**Comment by cpyrgas** [comment] 2023-05-31 15:39
I'm also seeing the same behavior as in the original report. Selecting the word from the completion list with down arrow first (to highlight it), then Enter.

Also, when typing 

```
CLASS Test
METHOD Foo(o AS T) AS VOID
END CLASS
```

and the cursor is after "T", then press CTRL+SPACE, I get a list. Then typing "e" to chose the members that start with "te", but instead of showing those, the list complete collapses.

**Comment by RobertvanderHulst** [comment] 2023-06-06 10:44
This was related to the fact that there was no space between the word "Tes" and the closing parenthesis.

**Comment by RobertvanderHulst** [comment] 2023-06-06 10:49
> At the moment on my pc CTRL+Space seems to not work anymore. On Volkmar PC it is working in the same way as described in the bug here (same Version of VS 17.6.2 and the newes X# version)
> 
> To select the entry with CTRL+Space we use the keyboard
> 
> [XSharpTests.zip](https://github.com/X-Sharp/XSharpPublic/files/11614608/XSharpTests.zip)

If you see this, then you may have the PowerToys installed. Its "Peek" feature also uses the Ctrl+Space button. Change the button for PowerToys - Peek and it will work again.

**Comment by cpyrgas** [comment] 2023-06-11 16:32
Selected word is now typed correctly, ut the care is put at the wrong position, between "s" and "t" in the word "Test", instead of after the last letter. Same if you CTRL+SPACE after "te" or "t"

Also the related problem I posted in https://github.com/X-Sharp/XSharpPublic/issues/1256#issuecomment-1570471136 still remains

**Comment by cpyrgas** [comment] 2023-07-09 08:20
Confirmed fixed

**Closed by cpyrgas** 2023-07-09 08:20 UTC
Labels: bug, vs editor
